"""Streamlit dashboard for the Sevilla Hidden Gems AI pilot.

This dashboard reads the clean CSV/JSON artifacts generated by:

    python -m scripts.export_sevilla_dashboard_data \
      --output-dir data/artifacts/ai/sevilla/dashboard \
      --expected-selected 150 \
      --include-mentions \
      --include-full-review-text \
      --strict

Expected project structure:

    hidden-gems-pipeline/
    ├── dashboard/
    │   └── streamlit_app.py
    └── data/artifacts/ai/sevilla/dashboard/
        ├── dashboard_metadata.json
        ├── kpi_summary.json
        ├── candidates_detail.csv
        ├── candidates_all.csv
        ├── top_global.csv
        ├── district_summary.csv
        ├── neighborhood_summary.csv
        ├── dish_summary.csv
        ├── place_summary.csv
        ├── tier_summary.csv
        ├── quality_summary.csv
        ├── filter_options.json
        ├── data_contract.json
        ├── dashboard_export_summary.json
        └── mention_examples.csv

Run from repository root:

    streamlit run dashboard/streamlit_app.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st

try:  # Plotly gives a nicer dashboard, but the app works without it.
    import plotly.express as px
    import plotly.graph_objects as go

    HAS_PLOTLY = True
except Exception:  # pragma: no cover - optional dependency fallback
    px = None
    go = None
    HAS_PLOTLY = False


# =============================================================================
# Page configuration
# =============================================================================

st.set_page_config(
    page_title="Hidden Gems Sevilla · Piloto IA",
    page_icon="🍽️",
    layout="wide",
    initial_sidebar_state="expanded",
)

DEFAULT_DATA_DIR = Path("data/artifacts/ai/sevilla/dashboard")

TIER_ORDER = {
    "top_hidden_gem": 4,
    "strong_hidden_gem": 3,
    "promising_hidden_gem": 2,
    "exploratory_hidden_gem": 1,
    "not_selected": 0,
}

TIER_LABELS = {
    "top_hidden_gem": "Top Hidden Gem",
    "strong_hidden_gem": "Strong",
    "promising_hidden_gem": "Promising",
    "exploratory_hidden_gem": "Exploratory",
    "not_selected": "Not selected",
}

TIER_COLORS = {
    "top_hidden_gem": "#ffd166",
    "strong_hidden_gem": "#ef476f",
    "promising_hidden_gem": "#06d6a0",
    "exploratory_hidden_gem": "#118ab2",
    "not_selected": "#8d99ae",
}

MAIN_COLUMNS = [
    "hidden_gem_selected_rank",
    "hidden_gem_tier",
    "hidden_gem_score",
    "dish_display_name",
    "place_name",
    "district_name",
    "neighborhood_name",
    "mention_count",
    "review_count",
    "positive_ratio",
    "negative_ratio",
    "evidence_tier",
    "aggregate_quality_tier",
    "ranking_explanation",
]

DETAIL_COMPONENT_COLUMNS = [
    "local_sentiment_component",
    "evidence_component",
    "confidence_component",
    "positive_balance_component",
    "rarity_component",
    "local_outperformance_component",
    "hiddenness_component",
]

PENALTY_COLUMNS = [
    "negative_penalty_factor",
    "noise_penalty_factor",
    "low_evidence_penalty_factor",
]

NUMERIC_COLUMNS = [
    "hidden_gem_selected_rank",
    "hidden_gem_rank",
    "hidden_gem_score",
    "hidden_gem_score_base",
    "latitude",
    "longitude",
    "mention_count",
    "review_count",
    "positive_mentions",
    "neutral_mentions",
    "negative_mentions",
    "positive_ratio",
    "negative_ratio",
    "avg_sentiment_confidence",
    "total_signal_weight",
    "avg_rating",
    "confidence_weighted_sentiment",
    "bayesian_sentiment_score",
    "reliability_high_ratio",
    "local_sentiment_component",
    "evidence_component",
    "confidence_component",
    "positive_balance_component",
    "rarity_component",
    "local_outperformance_component",
    "hiddenness_component",
    "negative_penalty_factor",
    "noise_penalty_factor",
    "low_evidence_penalty_factor",
    "selected_count",
    "selected_places",
    "selected_dishes",
    "selected_neighborhoods",
    "selected_districts",
    "top_hidden_gem_count",
    "strong_hidden_gem_count",
    "promising_hidden_gem_count",
    "exploratory_hidden_gem_count",
    "avg_score",
    "max_score",
    "min_score",
    "total_mentions",
    "total_reviews",
    "avg_positive_ratio",
    "avg_negative_ratio",
    "candidate_count",
    "place_count",
    "dish_count",
    "avg_score_selected",
    "max_score",
    "min_score_selected",
    "total_candidates_scored",
    "selected_candidates",
    "production_ready_count",
    "sentiment_score",
    "sentiment_confidence",
    "rating_value",
]

BOOL_COLUMNS = [
    "is_selected",
    "is_production_ready",
    "is_rankable_candidate",
]


# =============================================================================
# Styling
# =============================================================================

st.markdown(
    """
    <style>
        :root {
            --hg-bg: #0f172a;
            --hg-card: #111827;
            --hg-card-soft: #1f2937;
            --hg-text: #e5e7eb;
            --hg-muted: #9ca3af;
            --hg-accent: #f59e0b;
            --hg-accent-2: #38bdf8;
            --hg-ok: #34d399;
            --hg-warn: #f97316;
            --hg-danger: #fb7185;
        }

        .main-title {
            font-size: 2.45rem;
            font-weight: 850;
            letter-spacing: -0.04em;
            margin-bottom: 0.15rem;
        }

        .subtitle {
            color: #6b7280;
            font-size: 1.05rem;
            margin-bottom: 1.2rem;
        }

        .hero-box {
            border: 1px solid rgba(148, 163, 184, 0.25);
            border-radius: 1.3rem;
            padding: 1.25rem 1.35rem;
            background: linear-gradient(135deg, rgba(245,158,11,0.12), rgba(56,189,248,0.08));
            margin-bottom: 1rem;
        }

        .pill {
            display: inline-block;
            padding: 0.28rem 0.62rem;
            border-radius: 999px;
            font-size: 0.78rem;
            font-weight: 700;
            border: 1px solid rgba(148, 163, 184, 0.35);
            background: rgba(148, 163, 184, 0.10);
            margin-right: 0.35rem;
            margin-bottom: 0.35rem;
        }

        .pilot-warning {
            border-left: 5px solid #f59e0b;
            padding: 0.85rem 1rem;
            background: rgba(245, 158, 11, 0.10);
            border-radius: 0.8rem;
            margin: 0.6rem 0 1rem 0;
        }

        .metric-card {
            border: 1px solid rgba(148, 163, 184, 0.25);
            background: rgba(255, 255, 255, 0.04);
            border-radius: 1.15rem;
            padding: 1rem 1.05rem;
            min-height: 108px;
            box-shadow: 0 8px 24px rgba(15, 23, 42, 0.08);
        }

        .metric-label {
            color: #6b7280;
            font-size: 0.82rem;
            font-weight: 650;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            margin-bottom: 0.25rem;
        }

        .metric-value {
            font-size: 1.9rem;
            font-weight: 850;
            line-height: 1.05;
        }

        .metric-subtitle {
            color: #6b7280;
            font-size: 0.82rem;
            margin-top: 0.35rem;
        }

        .candidate-card {
            border: 1px solid rgba(148, 163, 184, 0.22);
            border-radius: 1.2rem;
            padding: 1.05rem 1.15rem;
            margin-bottom: 0.78rem;
            background: rgba(255, 255, 255, 0.035);
        }

        .candidate-title {
            font-size: 1.05rem;
            font-weight: 850;
            margin-bottom: 0.22rem;
        }

        .candidate-subtitle {
            color: #6b7280;
            font-size: 0.88rem;
            margin-bottom: 0.55rem;
        }

        .score-big {
            font-size: 2.15rem;
            font-weight: 900;
            line-height: 1;
        }

        .small-muted {
            color: #6b7280;
            font-size: 0.84rem;
        }

        .section-spacer {
            margin-top: 1.25rem;
        }

        div[data-testid="stDataFrame"] {
            border-radius: 0.8rem;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


# =============================================================================
# Generic helpers
# =============================================================================


def as_path(value: str | Path) -> Path:
    return Path(str(value)).expanduser().resolve() if str(value).strip() else DEFAULT_DATA_DIR.resolve()



def file_exists(path: Path) -> bool:
    return path.exists() and path.is_file()



def safe_json_load(path: Path, default: Any) -> Any:
    if not file_exists(path):
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        st.warning(f"No se pudo leer {path.name}: {exc}")
        return default



def safe_csv_load(path: Path) -> pd.DataFrame:
    if not file_exists(path):
        return pd.DataFrame()
    try:
        df = pd.read_csv(path)
    except Exception as exc:
        st.warning(f"No se pudo leer {path.name}: {exc}")
        return pd.DataFrame()
    return normalize_dataframe(df)



def normalize_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df

    out = df.copy()
    for col in NUMERIC_COLUMNS:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")

    for col in BOOL_COLUMNS:
        if col in out.columns:
            if out[col].dtype == bool:
                out[col] = out[col].fillna(False)
            else:
                out[col] = out[col].astype(str).str.lower().isin(["true", "1", "t", "yes", "y"])

    if "hidden_gem_tier" in out.columns:
        out["tier_order"] = out["hidden_gem_tier"].map(TIER_ORDER).fillna(0).astype(int)

    return out



def fmt_int(value: Any) -> str:
    try:
        if value is None or pd.isna(value):
            return "0"
        return f"{int(round(float(value))):,}".replace(",", ".")
    except Exception:
        return "0"



def fmt_score(value: Any) -> str:
    try:
        if value is None or pd.isna(value):
            return "—"
        return f"{float(value):.1f}"
    except Exception:
        return "—"



def fmt_pct(value: Any) -> str:
    try:
        if value is None or pd.isna(value):
            return "—"
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "—"



def truncate_text(value: Any, max_len: int = 160) -> str:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return ""
    text = str(value).replace("\n", " ").replace("\r", " ").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 1] + "…"



def tier_label(tier: Any) -> str:
    return TIER_LABELS.get(str(tier), str(tier) if tier is not None else "—")



def tier_badge(tier: Any) -> str:
    tier_str = str(tier)
    color = TIER_COLORS.get(tier_str, "#64748b")
    label = tier_label(tier_str)
    return (
        f"<span class='pill' style='background:{color}22; border-color:{color}66; color:{color};'>"
        f"{label}</span>"
    )



def metric_card(label: str, value: Any, subtitle: str = "") -> None:
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
            <div class="metric-subtitle">{subtitle}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )



def section_title(title: str, subtitle: str | None = None) -> None:
    st.markdown(f"### {title}")
    if subtitle:
        st.markdown(f"<div class='small-muted'>{subtitle}</div>", unsafe_allow_html=True)



def safe_columns(df: pd.DataFrame, columns: list[str]) -> list[str]:
    return [col for col in columns if col in df.columns]



def display_table(df: pd.DataFrame, columns: list[str] | None = None, height: int = 420) -> None:
    if df.empty:
        st.info("No hay datos para mostrar con los filtros actuales.")
        return

    view = df[safe_columns(df, columns)] if columns else df
    st.dataframe(view, use_container_width=True, height=height, hide_index=True)



def plot_bar(
    df: pd.DataFrame,
    x: str,
    y: str,
    title: str | None = None,
    color: str | None = None,
    orientation: str = "v",
    height: int = 360,
) -> None:
    if df.empty or x not in df.columns or y not in df.columns:
        st.info("No hay datos suficientes para la gráfica.")
        return

    if HAS_PLOTLY:
        if orientation == "h":
            fig = px.bar(df, x=y, y=x, color=color if color in df.columns else None, orientation="h", title=title)
            fig.update_layout(yaxis={"categoryorder": "total ascending"}, height=height, margin=dict(l=10, r=10, t=50, b=10))
        else:
            fig = px.bar(df, x=x, y=y, color=color if color in df.columns else None, title=title)
            fig.update_layout(height=height, margin=dict(l=10, r=10, t=50, b=10))
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.caption(title or "")
        chart_df = df[[x, y]].set_index(x)
        st.bar_chart(chart_df, height=height)



def plot_scatter_map(df: pd.DataFrame) -> None:
    if df.empty or "latitude" not in df.columns or "longitude" not in df.columns:
        st.info("No hay coordenadas disponibles para el mapa.")
        return

    map_df = df.dropna(subset=["latitude", "longitude"]).copy()
    if map_df.empty:
        st.info("No hay coordenadas válidas para el mapa.")
        return

    if HAS_PLOTLY:
        hover_cols = [c for c in ["place_name", "dish_display_name", "hidden_gem_score", "neighborhood_name", "district_name"] if c in map_df.columns]
        fig = px.scatter_mapbox(
            map_df,
            lat="latitude",
            lon="longitude",
            color="hidden_gem_tier" if "hidden_gem_tier" in map_df.columns else None,
            size="hidden_gem_score" if "hidden_gem_score" in map_df.columns else None,
            hover_name="place_name" if "place_name" in map_df.columns else None,
            hover_data=hover_cols,
            zoom=11,
            height=520,
        )
        fig.update_layout(mapbox_style="open-street-map", margin=dict(l=0, r=0, t=0, b=0))
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.map(map_df.rename(columns={"latitude": "lat", "longitude": "lon"})[["lat", "lon"]])



def records_to_download(df: pd.DataFrame, filename: str, label: str) -> None:
    if df.empty:
        return
    csv = df.to_csv(index=False).encode("utf-8")
    st.download_button(label, csv, file_name=filename, mime="text/csv")


# =============================================================================
# Data loading
# =============================================================================


@st.cache_data(show_spinner=False)
def load_dashboard_data(data_dir_str: str) -> dict[str, Any]:
    data_dir = Path(data_dir_str)

    data = {
        "data_dir": data_dir,
        "metadata": safe_json_load(data_dir / "dashboard_metadata.json", {}),
        "kpis": safe_json_load(data_dir / "kpi_summary.json", {}),
        "filter_options": safe_json_load(data_dir / "filter_options.json", {}),
        "data_contract": safe_json_load(data_dir / "data_contract.json", {}),
        "export_summary": safe_json_load(data_dir / "dashboard_export_summary.json", {}),
        "candidates_detail": safe_csv_load(data_dir / "candidates_detail.csv"),
        "candidates_all": safe_csv_load(data_dir / "candidates_all.csv"),
        "top_global": safe_csv_load(data_dir / "top_global.csv"),
        "top_by_district": safe_csv_load(data_dir / "top_by_district.csv"),
        "top_by_neighborhood": safe_csv_load(data_dir / "top_by_neighborhood.csv"),
        "top_by_dish": safe_csv_load(data_dir / "top_by_dish.csv"),
        "district_summary": safe_csv_load(data_dir / "district_summary.csv"),
        "neighborhood_summary": safe_csv_load(data_dir / "neighborhood_summary.csv"),
        "dish_summary": safe_csv_load(data_dir / "dish_summary.csv"),
        "place_summary": safe_csv_load(data_dir / "place_summary.csv"),
        "tier_summary": safe_csv_load(data_dir / "tier_summary.csv"),
        "quality_summary": safe_csv_load(data_dir / "quality_summary.csv"),
        "mention_examples": safe_csv_load(data_dir / "mention_examples.csv"),
    }

    return data


# =============================================================================
# Filtering
# =============================================================================


def sorted_unique(df: pd.DataFrame, column: str) -> list[str]:
    if df.empty or column not in df.columns:
        return []
    values = df[column].dropna().astype(str).sort_values().unique().tolist()
    return values



def apply_filters(
    df: pd.DataFrame,
    districts: list[str],
    neighborhoods: list[str],
    dishes: list[str],
    tiers: list[str],
    evidence: list[str],
    min_score: float,
    text_search: str,
    only_top_strong: bool,
) -> pd.DataFrame:
    if df.empty:
        return df

    out = df.copy()

    if districts and "district_name" in out.columns:
        out = out[out["district_name"].astype(str).isin(districts)]

    if neighborhoods and "neighborhood_name" in out.columns:
        out = out[out["neighborhood_name"].astype(str).isin(neighborhoods)]

    if dishes and "dish_display_name" in out.columns:
        out = out[out["dish_display_name"].astype(str).isin(dishes)]

    if tiers and "hidden_gem_tier" in out.columns:
        out = out[out["hidden_gem_tier"].astype(str).isin(tiers)]

    if evidence and "evidence_tier" in out.columns:
        out = out[out["evidence_tier"].astype(str).isin(evidence)]

    if "hidden_gem_score" in out.columns:
        out = out[out["hidden_gem_score"].fillna(-1) >= float(min_score)]

    if only_top_strong and "hidden_gem_tier" in out.columns:
        out = out[out["hidden_gem_tier"].isin(["top_hidden_gem", "strong_hidden_gem"])]

    if text_search:
        query = text_search.strip().lower()
        searchable_cols = [
            col
            for col in [
                "place_name",
                "dish_display_name",
                "dish_name",
                "district_name",
                "neighborhood_name",
                "ranking_explanation",
            ]
            if col in out.columns
        ]
        if searchable_cols:
            mask = pd.Series(False, index=out.index)
            for col in searchable_cols:
                mask = mask | out[col].astype(str).str.lower().str.contains(query, na=False)
            out = out[mask]

    return out.sort_values(
        ["hidden_gem_selected_rank", "hidden_gem_score", "mention_count", "review_count"],
        ascending=[True, False, False, False],
        na_position="last",
    )



def candidate_label(row: pd.Series) -> str:
    rank = row.get("hidden_gem_selected_rank", "—")
    rank_txt = fmt_int(rank) if not pd.isna(rank) else "—"
    dish = row.get("dish_display_name", row.get("dish_name", "plato"))
    place = row.get("place_name", "local")
    score = fmt_score(row.get("hidden_gem_score"))
    neighborhood = row.get("neighborhood_name", "")
    return f"#{rank_txt} · {dish} en {place} · {score}/100 · {neighborhood}"



def get_candidate_mentions(candidate: pd.Series, mentions_df: pd.DataFrame) -> pd.DataFrame:
    if mentions_df.empty:
        return mentions_df

    out = mentions_df.copy()

    if "hidden_gem_candidate_id" in out.columns and "hidden_gem_candidate_id" in candidate.index:
        cid = str(candidate.get("hidden_gem_candidate_id"))
        matched = out[out["hidden_gem_candidate_id"].astype(str) == cid]
        if not matched.empty:
            return matched

    place_id = str(candidate.get("place_id", ""))
    dish_id = str(candidate.get("dish_id", ""))
    if "place_id" in out.columns and "dish_id" in out.columns:
        return out[(out["place_id"].astype(str) == place_id) & (out["dish_id"].astype(str) == dish_id)]

    return pd.DataFrame()


# =============================================================================
# Dashboard sections
# =============================================================================


def render_header(metadata: dict[str, Any], kpis: dict[str, Any]) -> None:
    scope = metadata.get("artifact_ranking_scope") or metadata.get("dashboard_scope") or "sevilla_pilot"
    version = metadata.get("ranking_version", "sevilla_hidden_gems_ranking_pilot_v1")
    source = metadata.get("source", "Google Places Reviews")

    st.markdown(
        """
        <div class="hero-box">
            <div class="main-title">🍽️ Hidden Gems Sevilla · Piloto IA</div>
            <div class="subtitle">
                Descubrimiento de platos destacados por local, barrio y distrito a partir de reseñas reales.
            </div>
            <span class="pill">Scope: {scope}</span>
            <span class="pill">Fuente: {source}</span>
            <span class="pill">Versión: {version}</span>
            <span class="pill">Producción: no</span>
        </div>
        """.format(scope=scope, source=source, version=version),
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="pilot-warning">
            <strong>Nota de interpretación:</strong> este dashboard muestra el piloto IA de Sevilla. Los resultados son trazables y consultables,
            pero todavía están marcados como <code>is_production_ready = false</code>. Sirven para demo, análisis y revisión antes de producción.
        </div>
        """,
        unsafe_allow_html=True,
    )



def render_kpi_cards(kpis: dict[str, Any]) -> None:
    cols = st.columns(6)
    with cols[0]:
        metric_card("Candidatos", fmt_int(kpis.get("selected_candidates")), "seleccionados")
    with cols[1]:
        metric_card("Locales", fmt_int(kpis.get("selected_places")), "con plato destacado")
    with cols[2]:
        metric_card("Platos", fmt_int(kpis.get("selected_dishes")), "distintos")
    with cols[3]:
        metric_card("Barrios", fmt_int(kpis.get("selected_neighborhoods")), "cubiertos")
    with cols[4]:
        metric_card("Distritos", fmt_int(kpis.get("selected_districts")), "cubiertos")
    with cols[5]:
        metric_card("Score máx.", fmt_score(kpis.get("max_score")), "sobre 100")



def render_top_cards(df: pd.DataFrame, n: int = 6) -> None:
    if df.empty:
        st.info("No hay candidatos para mostrar.")
        return

    top = df.head(n).copy()
    for idx in range(0, len(top), 3):
        cols = st.columns(3)
        for col, (_, row) in zip(cols, top.iloc[idx : idx + 3].iterrows()):
            with col:
                st.markdown(
                    f"""
                    <div class="candidate-card">
                        <div>{tier_badge(row.get('hidden_gem_tier'))}</div>
                        <div class="candidate-title">#{fmt_int(row.get('hidden_gem_selected_rank'))} · {row.get('dish_display_name', row.get('dish_name', 'Plato'))}</div>
                        <div class="candidate-subtitle">{row.get('place_name', 'Local')} · {row.get('neighborhood_name', '')} · {row.get('district_name', '')}</div>
                        <div class="score-big">{fmt_score(row.get('hidden_gem_score'))}</div>
                        <div class="small-muted">{fmt_int(row.get('mention_count'))} menciones · {fmt_int(row.get('review_count'))} reviews · {fmt_pct(row.get('positive_ratio'))} positivas</div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )



def render_overview(data: dict[str, Any], filtered_df: pd.DataFrame) -> None:
    kpis = data["kpis"]
    tier_summary = data["tier_summary"]
    district_summary = data["district_summary"]
    dish_summary = data["dish_summary"]

    render_kpi_cards(kpis)

    st.markdown("<div class='section-spacer'></div>", unsafe_allow_html=True)
    col_a, col_b = st.columns([1.3, 1])

    with col_a:
        section_title("Top Hidden Gems", "Primeros candidatos del ranking global del piloto.")
        render_top_cards(filtered_df, n=6)

    with col_b:
        section_title("Distribución por tier")
        if not tier_summary.empty:
            plot_bar(tier_summary.sort_values("candidate_count", ascending=False), "hidden_gem_tier", "candidate_count", "Candidatos por tier")
        else:
            st.info("No hay resumen de tiers.")

    col_c, col_d = st.columns(2)
    with col_c:
        section_title("Candidatos por distrito")
        if not district_summary.empty:
            district_plot = district_summary.sort_values("selected_count", ascending=True)
            plot_bar(district_plot, "district_name", "selected_count", "Distribución territorial", orientation="h")
    with col_d:
        section_title("Platos más frecuentes")
        if not dish_summary.empty:
            top_dishes = dish_summary.sort_values("selected_count", ascending=True).tail(12)
            plot_bar(top_dishes, "dish_display_name", "selected_count", "Platos con más candidatos", orientation="h")



def render_explorer(filtered_df: pd.DataFrame) -> None:
    section_title("Explorador de candidatos", "Tabla consultable con los candidatos filtrados.")
    display_table(filtered_df, MAIN_COLUMNS, height=560)

    col1, col2, col3 = st.columns(3)
    with col1:
        records_to_download(filtered_df, "hidden_gems_filtrados.csv", "Descargar candidatos filtrados")
    with col2:
        if not filtered_df.empty:
            st.metric("Resultados filtrados", fmt_int(len(filtered_df)))
    with col3:
        if not filtered_df.empty and "hidden_gem_score" in filtered_df.columns:
            st.metric("Score medio filtrado", fmt_score(filtered_df["hidden_gem_score"].mean()))



def render_territory(data: dict[str, Any], filtered_df: pd.DataFrame) -> None:
    district_summary = data["district_summary"]
    neighborhood_summary = data["neighborhood_summary"]
    top_by_neighborhood = data["top_by_neighborhood"]

    section_title("Mapa de candidatos", "Puntos geográficos de los candidatos seleccionados.")
    plot_scatter_map(filtered_df)

    st.markdown("<div class='section-spacer'></div>", unsafe_allow_html=True)
    col1, col2 = st.columns(2)

    with col1:
        section_title("Resumen por distrito")
        display_table(
            district_summary,
            [
                "district_name",
                "selected_count",
                "selected_places",
                "selected_dishes",
                "selected_neighborhoods",
                "avg_score",
                "max_score",
                "total_mentions",
                "total_reviews",
            ],
            height=420,
        )

    with col2:
        section_title("Barrios con más candidatos")
        if not neighborhood_summary.empty:
            top_neigh = neighborhood_summary.sort_values("selected_count", ascending=True).tail(15)
            plot_bar(top_neigh, "neighborhood_name", "selected_count", "Top barrios", orientation="h")

    section_title("Top por barrio")
    display_table(
        top_by_neighborhood,
        [
            "district_name",
            "neighborhood_name",
            "rank_in_neighborhood",
            "hidden_gem_score",
            "place_name",
            "dish_display_name",
            "hidden_gem_tier",
            "mention_count",
            "review_count",
            "ranking_explanation",
        ],
        height=520,
    )



def render_dishes_places(data: dict[str, Any]) -> None:
    dish_summary = data["dish_summary"]
    place_summary = data["place_summary"]
    top_by_dish = data["top_by_dish"]

    col1, col2 = st.columns(2)
    with col1:
        section_title("Resumen por plato")
        display_table(
            dish_summary.sort_values(["selected_count", "max_score"], ascending=[False, False]) if not dish_summary.empty else dish_summary,
            [
                "dish_display_name",
                "selected_count",
                "selected_places",
                "selected_districts",
                "selected_neighborhoods",
                "avg_score",
                "max_score",
                "total_mentions",
                "total_reviews",
            ],
            height=520,
        )

    with col2:
        section_title("Locales con más platos destacados")
        display_table(
            place_summary.sort_values(["selected_count", "max_score"], ascending=[False, False]) if not place_summary.empty else place_summary,
            [
                "place_name",
                "district_name",
                "neighborhood_name",
                "selected_count",
                "selected_dishes",
                "best_dish_name",
                "best_dish_score",
                "avg_score",
                "max_score",
            ],
            height=520,
        )

    section_title("Top locales por plato")
    display_table(
        top_by_dish,
        [
            "dish_display_name",
            "rank_for_dish",
            "hidden_gem_selected_rank",
            "hidden_gem_score",
            "place_name",
            "district_name",
            "neighborhood_name",
            "hidden_gem_tier",
            "mention_count",
            "review_count",
            "ranking_explanation",
        ],
        height=520,
    )



def render_candidate_detail(filtered_df: pd.DataFrame, mentions_df: pd.DataFrame) -> None:
    if filtered_df.empty:
        st.info("No hay candidatos disponibles con los filtros actuales.")
        return

    section_title("Detalle de candidato", "Explicabilidad del score, evidencia y reseñas asociadas.")

    labels = [candidate_label(row) for _, row in filtered_df.iterrows()]
    selected_label = st.selectbox("Selecciona un candidato", labels, index=0)
    selected_idx = labels.index(selected_label)
    candidate = filtered_df.iloc[selected_idx]

    st.markdown(
        f"""
        <div class="candidate-card">
            <div>{tier_badge(candidate.get('hidden_gem_tier'))}</div>
            <div class="candidate-title">#{fmt_int(candidate.get('hidden_gem_selected_rank'))} · {candidate.get('dish_display_name', candidate.get('dish_name', 'Plato'))} en {candidate.get('place_name', 'Local')}</div>
            <div class="candidate-subtitle">{candidate.get('neighborhood_name', '')} · {candidate.get('district_name', '')} · {candidate.get('address_text', '')}</div>
            <div class="score-big">{fmt_score(candidate.get('hidden_gem_score'))}/100</div>
            <div class="small-muted">{truncate_text(candidate.get('ranking_explanation'), 300)}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    tab_summary, tab_score, tab_reviews = st.tabs(["Resumen", "Componentes del score", "Menciones y reseñas"])

    with tab_summary:
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Menciones", fmt_int(candidate.get("mention_count")))
        with col2:
            st.metric("Reviews", fmt_int(candidate.get("review_count")))
        with col3:
            st.metric("Ratio positivo", fmt_pct(candidate.get("positive_ratio")))
        with col4:
            st.metric("Confianza media", fmt_score(candidate.get("avg_sentiment_confidence")))

        col5, col6 = st.columns(2)
        with col5:
            st.write("**Evidencia**")
            st.write(candidate.get("evidence_tier", "—"))
            st.write("**Calidad agregada**")
            st.write(candidate.get("aggregate_quality_tier", "—"))
        with col6:
            st.write("**Estado de producción**")
            st.write("No producción" if not bool(candidate.get("is_production_ready", False)) else "Producción")
            st.write("**Revisión humana**")
            st.write(candidate.get("human_review_status", "—"))

    with tab_score:
        component_values = []
        for col in DETAIL_COMPONENT_COLUMNS:
            if col in candidate.index and not pd.isna(candidate.get(col)):
                component_values.append({"component": col, "value": float(candidate.get(col))})

        penalty_values = []
        for col in PENALTY_COLUMNS:
            if col in candidate.index and not pd.isna(candidate.get(col)):
                penalty_values.append({"penalty": col, "value": float(candidate.get(col))})

        col1, col2 = st.columns(2)
        with col1:
            st.write("**Componentes positivos / señales**")
            comp_df = pd.DataFrame(component_values)
            if not comp_df.empty:
                plot_bar(comp_df.sort_values("value", ascending=True), "component", "value", "Componentes del score", orientation="h")
            else:
                st.info("No hay componentes disponibles.")

        with col2:
            st.write("**Factores de penalización**")
            pen_df = pd.DataFrame(penalty_values)
            if not pen_df.empty:
                plot_bar(pen_df.sort_values("value", ascending=True), "penalty", "value", "Penalizaciones", orientation="h")
            else:
                st.info("No hay penalizaciones disponibles.")

        display_cols = safe_columns(pd.DataFrame([candidate]), DETAIL_COMPONENT_COLUMNS + PENALTY_COLUMNS)
        if display_cols:
            st.dataframe(pd.DataFrame([candidate])[display_cols], hide_index=True, use_container_width=True)

    with tab_reviews:
        candidate_mentions = get_candidate_mentions(candidate, mentions_df)
        if candidate_mentions.empty:
            st.info("No hay ejemplos de menciones/reseñas exportados para este candidato.")
            st.caption("Vuelve a generar el export con --include-mentions y, si quieres reseñas completas, --include-full-review-text.")
            return

        st.write(f"**Ejemplos exportados:** {len(candidate_mentions)}")

        display_table(
            candidate_mentions,
            [
                "rating_value",
                "sentiment_label",
                "sentiment_score",
                "sentiment_confidence",
                "sentiment_reliability_tier",
                "mention_text",
                "context_sentence",
            ],
            height=260,
        )

        st.markdown("#### Detalle de reseñas")
        for idx, row in candidate_mentions.reset_index(drop=True).iterrows():
            sentiment = row.get("sentiment_label", "—")
            rating = fmt_score(row.get("rating_value"))
            mention = row.get("mention_text", "")
            title = f"Reseña {idx + 1} · rating {rating} · sentimiento {sentiment} · mención: {mention}"
            with st.expander(title):
                st.write("**Contexto de la mención**")
                st.write(row.get("context_sentence", "Sin contexto disponible."))

                if "review_text_raw" in row.index and str(row.get("review_text_raw", "")).strip():
                    st.write("**Reseña completa**")
                    st.write(row.get("review_text_raw"))
                else:
                    st.caption("La reseña completa no está exportada. Genera el dashboard data con --include-full-review-text.")



def render_quality(data: dict[str, Any]) -> None:
    quality_summary = data["quality_summary"]
    export_summary = data["export_summary"]
    data_contract = data["data_contract"]

    section_title("Calidad del piloto", "Checks principales y limitaciones operativas.")

    if not quality_summary.empty:
        display_table(quality_summary, None, height=420)
    else:
        st.info("No hay quality_summary.csv disponible.")

    st.markdown("#### Summary del export")
    if export_summary:
        st.json(export_summary)
    else:
        st.info("No hay dashboard_export_summary.json disponible.")

    st.markdown("#### Contrato de datos")
    if data_contract:
        with st.expander("Ver contrato de datos completo"):
            st.json(data_contract)
    else:
        st.info("No hay data_contract.json disponible.")

    st.markdown(
        """
        <div class="pilot-warning">
            <strong>Limitaciones clave:</strong><br>
            Google Places no devuelve necesariamente todas las reseñas históricas de cada local. El ranking se basa en la evidencia disponible,
            está pensado como piloto y todos los candidatos siguen marcados como no producción.
        </div>
        """,
        unsafe_allow_html=True,
    )


# =============================================================================
# Main app
# =============================================================================


def main() -> None:
    with st.sidebar:
        st.markdown("## ⚙️ Configuración")
        data_dir_input = st.text_input("Carpeta de datos del dashboard", value=str(DEFAULT_DATA_DIR))
        data_dir = as_path(data_dir_input)

        if st.button("Recargar datos"):
            st.cache_data.clear()
            st.rerun()

        st.caption("Los datos deben generarse previamente con `scripts.export_sevilla_dashboard_data`.")

    if not data_dir.exists():
        st.error(f"No existe la carpeta de datos: {data_dir}")
        st.stop()

    data = load_dashboard_data(str(data_dir))
    candidates_detail = data["candidates_detail"]
    candidates_all = data["candidates_all"]

    if candidates_detail.empty:
        st.error("No se encontró `candidates_detail.csv` o está vacío. Ejecuta primero el exportador del dashboard.")
        st.stop()

    metadata = data["metadata"]
    kpis = data["kpis"]

    render_header(metadata, kpis)

    with st.sidebar:
        st.markdown("## 🔎 Filtros")
        use_all = st.checkbox("Incluir candidatos no seleccionados", value=False)
        base_df = candidates_all if use_all and not candidates_all.empty else candidates_detail

        district_options = sorted_unique(base_df, "district_name")
        selected_districts = st.multiselect("Distrito", district_options)

        neighborhood_options_df = base_df
        if selected_districts and "district_name" in neighborhood_options_df.columns:
            neighborhood_options_df = neighborhood_options_df[neighborhood_options_df["district_name"].astype(str).isin(selected_districts)]
        neighborhood_options = sorted_unique(neighborhood_options_df, "neighborhood_name")
        selected_neighborhoods = st.multiselect("Barrio", neighborhood_options)

        dish_options = sorted_unique(base_df, "dish_display_name")
        selected_dishes = st.multiselect("Plato", dish_options)

        tier_options = [tier for tier in TIER_ORDER if tier in sorted_unique(base_df, "hidden_gem_tier")]
        selected_tiers = st.multiselect("Tier", tier_options, format_func=tier_label)

        evidence_options = sorted_unique(base_df, "evidence_tier")
        selected_evidence = st.multiselect("Evidencia", evidence_options)

        score_min_available = float(base_df["hidden_gem_score"].min()) if "hidden_gem_score" in base_df.columns else 0.0
        score_max_available = float(base_df["hidden_gem_score"].max()) if "hidden_gem_score" in base_df.columns else 100.0

        if math.isnan(score_min_available) or math.isinf(score_min_available):
            score_min_available = 0.0
        if math.isnan(score_max_available) or math.isinf(score_max_available):
            score_max_available = 100.0

        default_min_score = float(max(0.0, math.floor(score_min_available)))

        min_score = st.slider(
            "Score mínimo",
            min_value=0.0,
            max_value=100.0,
            value=default_min_score,
            step=1.0,
        )

        only_top_strong = st.checkbox("Mostrar solo Top + Strong", value=False)
        text_search = st.text_input("Buscar texto", placeholder="local, plato, barrio...")

    base_df = candidates_all if use_all and not candidates_all.empty else candidates_detail
    filtered_df = apply_filters(
        base_df,
        districts=selected_districts,
        neighborhoods=selected_neighborhoods,
        dishes=selected_dishes,
        tiers=selected_tiers,
        evidence=selected_evidence,
        min_score=min_score,
        text_search=text_search,
        only_top_strong=only_top_strong,
    )

    render_kpi_cards(kpis)

    st.markdown("---")
    tabs = st.tabs(
        [
            "🏠 Resumen",
            "🔎 Explorador",
            "🗺️ Territorio",
            "🍽️ Platos y locales",
            "🧾 Detalle",
            "✅ Calidad",
        ]
    )

    with tabs[0]:
        render_overview(data, filtered_df)

    with tabs[1]:
        render_explorer(filtered_df)

    with tabs[2]:
        render_territory(data, filtered_df)

    with tabs[3]:
        render_dishes_places(data)

    with tabs[4]:
        render_candidate_detail(filtered_df, data["mention_examples"])

    with tabs[5]:
        render_quality(data)


if __name__ == "__main__":
    main()
