"""Streamlit dashboard for the Hidden Gems Yelp AI prototype.

This dashboard reads the clean CSV/JSON artifacts generated by:

    python -m scripts.export_yelp_dashboard_data \
      --output-dir data/artifacts/ai/yelp/dashboard \
      --expected-selected 622 \
      --top-global-limit 9999 \
      --top-per-group 9999 \
      --include-mentions \
      --include-full-review-text \
      --strict

Expected project structure:

    hidden-gems-pipeline/
    ├── dashboard/
    │   └── streamlit_yelp_app.py
    └── data/artifacts/ai/yelp/dashboard/
        ├── dashboard_metadata.json
        ├── kpi_summary.json
        ├── candidates_detail.csv
        ├── candidates_all.csv
        ├── top_global.csv
        ├── top_by_city.csv
        ├── top_by_state.csv
        ├── top_by_dish.csv
        ├── city_summary.csv
        ├── state_summary.csv
        ├── dish_summary.csv
        ├── place_summary.csv
        ├── tier_summary.csv
        ├── quality_summary.csv
        ├── filter_options.json
        ├── data_contract.json
        ├── dashboard_export_summary.json
        └── mention_examples.csv

Run from repository root:

    streamlit run dashboard/streamlit_yelp_app.py

Important:
    Yelp is an AI benchmark/prototype. It is not a Sevilla production ranking.
    If mention_examples.csv contains review_text_raw, do not commit that artifact.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Iterable

import pandas as pd
import streamlit as st

try:
    import plotly.express as px
    import plotly.graph_objects as go

    HAS_PLOTLY = True
except Exception:  # pragma: no cover - optional dependency fallback
    px = None
    go = None
    HAS_PLOTLY = False


# =============================================================================
# Page configuration
# =============================================================================

st.set_page_config(
    page_title="Hidden Gems Yelp · AI Prototype",
    page_icon="🧪",
    layout="wide",
    initial_sidebar_state="expanded",
)

DEFAULT_DATA_DIR = Path("data/artifacts/ai/yelp/dashboard")

TIER_ORDER = {
    "top_hidden_gem": 4,
    "strong_hidden_gem": 3,
    "promising_hidden_gem": 2,
    "exploratory_hidden_gem": 1,
    "not_selected": 0,
}

TIER_LABELS = {
    "top_hidden_gem": "Top Hidden Gem",
    "strong_hidden_gem": "Strong",
    "promising_hidden_gem": "Promising",
    "exploratory_hidden_gem": "Exploratory",
    "not_selected": "Not selected",
}

TIER_COLORS = {
    "top_hidden_gem": "#ffd166",
    "strong_hidden_gem": "#ef476f",
    "promising_hidden_gem": "#06d6a0",
    "exploratory_hidden_gem": "#118ab2",
    "not_selected": "#8d99ae",
}

MAIN_COLUMNS = [
    "hidden_gem_selected_rank",
    "hidden_gem_tier",
    "hidden_gem_score",
    "dish_dashboard_name",
    "place_name",
    "inferred_city",
    "inferred_state",
    "mention_count",
    "review_count",
    "positive_ratio",
    "negative_ratio",
    "avg_sentiment_confidence",
    "evidence_tier",
    "aggregate_quality_tier",
    "ranking_explanation",
]

DETAIL_COMPONENT_COLUMNS = [
    "local_sentiment_component",
    "evidence_component",
    "confidence_component",
    "positive_balance_component",
    "rarity_component",
    "local_outperformance_component",
    "hiddenness_component",
]

PENALTY_COLUMNS = [
    "negative_penalty_factor",
    "beverage_penalty_factor",
    "noise_penalty_factor",
    "low_evidence_penalty_factor",
]

NUMERIC_COLUMNS = [
    "hidden_gem_selected_rank",
    "hidden_gem_rank",
    "hidden_gem_score",
    "hidden_gem_score_base",
    "latitude",
    "longitude",
    "mention_count",
    "review_count",
    "positive_mentions",
    "neutral_mentions",
    "negative_mentions",
    "positive_ratio",
    "negative_ratio",
    "avg_ner_confidence",
    "avg_sentiment_confidence",
    "avg_signal_weight",
    "total_signal_weight",
    "avg_rating",
    "confidence_weighted_sentiment",
    "bayesian_sentiment_score",
    "reliability_high_ratio",
    "high_reliability_mentions",
    "medium_reliability_mentions",
    "low_reliability_mentions",
    "local_sentiment_component",
    "evidence_component",
    "confidence_component",
    "positive_balance_component",
    "rarity_component",
    "local_outperformance_component",
    "hiddenness_component",
    "preliminary_component",
    "negative_penalty_factor",
    "beverage_penalty_factor",
    "noise_penalty_factor",
    "low_evidence_penalty_factor",
    "selected_count",
    "selected_places",
    "selected_dishes",
    "selected_cities",
    "selected_states",
    "candidate_count",
    "place_count",
    "dish_count",
    "city_count",
    "state_count",
    "top_hidden_gem_count",
    "strong_hidden_gem_count",
    "promising_hidden_gem_count",
    "exploratory_hidden_gem_count",
    "avg_score",
    "max_score",
    "min_score",
    "total_mentions",
    "total_reviews",
    "avg_positive_ratio",
    "avg_negative_ratio",
    "avg_score_selected",
    "max_score",
    "min_score_selected",
    "total_candidates_scored",
    "selected_candidates",
    "production_ready_count",
    "mention_examples_rows",
    "sentiment_score",
    "sentiment_confidence",
    "rating_value",
]

BOOL_COLUMNS = [
    "is_selected",
    "is_production_ready",
    "is_rankable_candidate",
]


# =============================================================================
# Styling
# =============================================================================

st.markdown(
    """
    <style>
        .main-title {
            font-size: 2.55rem;
            font-weight: 850;
            letter-spacing: -0.045em;
            margin-bottom: 0.15rem;
        }

        .subtitle {
            color: #64748b;
            font-size: 1.05rem;
            margin-bottom: 1rem;
        }

        .hero-box {
            border: 1px solid rgba(148, 163, 184, 0.24);
            border-radius: 1.35rem;
            padding: 1.2rem 1.35rem;
            background: linear-gradient(135deg, rgba(59,130,246,0.12), rgba(236,72,153,0.08));
            margin-bottom: 1rem;
        }

        .benchmark-warning {
            border-left: 5px solid #3b82f6;
            padding: 0.85rem 1rem;
            background: rgba(59, 130, 246, 0.10);
            border-radius: 0.8rem;
            margin: 0.6rem 0 1rem 0;
        }

        .pill {
            display: inline-block;
            padding: 0.28rem 0.62rem;
            border-radius: 999px;
            font-size: 0.78rem;
            font-weight: 700;
            border: 1px solid rgba(148, 163, 184, 0.35);
            background: rgba(148, 163, 184, 0.10);
            margin-right: 0.35rem;
            margin-bottom: 0.35rem;
        }

        .metric-card {
            border: 1px solid rgba(148, 163, 184, 0.25);
            background: rgba(255, 255, 255, 0.035);
            border-radius: 1.1rem;
            padding: 1rem;
            min-height: 110px;
        }

        .metric-label {
            color: #64748b;
            font-size: 0.82rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }

        .metric-value {
            font-size: 1.75rem;
            font-weight: 850;
            margin-top: 0.18rem;
        }

        .candidate-card {
            border: 1px solid rgba(148, 163, 184, 0.22);
            border-radius: 1.05rem;
            padding: 1rem 1rem 0.8rem 1rem;
            background: rgba(255, 255, 255, 0.035);
            margin-bottom: 0.75rem;
        }

        .small-muted {
            color: #64748b;
            font-size: 0.88rem;
        }

        .score-badge {
            display: inline-block;
            padding: 0.25rem 0.55rem;
            border-radius: 0.7rem;
            font-weight: 800;
            background: rgba(59, 130, 246, 0.12);
            border: 1px solid rgba(59, 130, 246, 0.25);
        }

        .review-box {
            border: 1px solid rgba(148, 163, 184, 0.25);
            border-radius: 0.9rem;
            padding: 0.85rem 1rem;
            background: rgba(15, 23, 42, 0.035);
            margin-bottom: 0.75rem;
        }

        .stTabs [data-baseweb="tab-list"] {
            gap: 0.35rem;
        }

        .stTabs [data-baseweb="tab"] {
            border-radius: 999px;
            padding: 0.45rem 0.9rem;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


# =============================================================================
# Data helpers
# =============================================================================


def normalize_path(value: str | Path) -> Path:
    return Path(str(value).strip()).expanduser()


@st.cache_data(show_spinner=False)
def load_json(path: str) -> dict[str, Any]:
    p = Path(path)
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


@st.cache_data(show_spinner=False)
def load_csv(path: str) -> pd.DataFrame:
    p = Path(path)
    if not p.exists():
        return pd.DataFrame()
    df = pd.read_csv(p)
    return normalize_dataframe(df)



def normalize_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    out = df.copy()

    for col in NUMERIC_COLUMNS:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")

    for col in BOOL_COLUMNS:
        if col in out.columns:
            if out[col].dtype == bool:
                out[col] = out[col].fillna(False)
            else:
                out[col] = out[col].astype(str).str.lower().isin(["true", "1", "t", "yes", "y"])

    if "dish_dashboard_name" not in out.columns:
        if "dish_display_name" in out.columns:
            out["dish_dashboard_name"] = out["dish_display_name"].fillna(out.get("dish_name", ""))
        elif "dish_name" in out.columns:
            out["dish_dashboard_name"] = out["dish_name"]
        else:
            out["dish_dashboard_name"] = ""

    if "inferred_city" not in out.columns:
        out["inferred_city"] = out.get("city", "")
    if "inferred_state" not in out.columns:
        out["inferred_state"] = out.get("state", "")

    if "hidden_gem_tier_order" not in out.columns and "hidden_gem_tier" in out.columns:
        out["hidden_gem_tier_order"] = out["hidden_gem_tier"].map(TIER_ORDER).fillna(0).astype(int)

    return out



def load_dashboard_data(data_dir: Path) -> dict[str, Any]:
    files = {
        "metadata": "dashboard_metadata.json",
        "kpis": "kpi_summary.json",
        "export_summary": "dashboard_export_summary.json",
        "filter_options": "filter_options.json",
        "data_contract": "data_contract.json",
        "candidates_detail": "candidates_detail.csv",
        "candidates_all": "candidates_all.csv",
        "top_global": "top_global.csv",
        "top_by_city": "top_by_city.csv",
        "top_by_state": "top_by_state.csv",
        "top_by_dish": "top_by_dish.csv",
        "city_summary": "city_summary.csv",
        "state_summary": "state_summary.csv",
        "dish_summary": "dish_summary.csv",
        "place_summary": "place_summary.csv",
        "tier_summary": "tier_summary.csv",
        "quality_summary": "quality_summary.csv",
        "mention_examples": "mention_examples.csv",
    }

    data: dict[str, Any] = {}
    for key, filename in files.items():
        path = data_dir / filename
        if filename.endswith(".json"):
            data[key] = load_json(str(path))
        else:
            data[key] = load_csv(str(path))
    return data



def safe_int(value: Any, default: int = 0) -> int:
    try:
        if pd.isna(value):
            return default
        return int(value)
    except Exception:
        return default



def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default
        return float(value)
    except Exception:
        return default



def format_number(value: Any, decimals: int = 0) -> str:
    num = safe_float(value, 0.0)
    if decimals == 0:
        return f"{num:,.0f}".replace(",", ".")
    return f"{num:,.{decimals}f}".replace(",", "X").replace(".", ",").replace("X", ".")



def pct(value: Any) -> str:
    return f"{safe_float(value, 0.0) * 100:.1f}%"



def get_kpi(kpis: dict[str, Any], key: str, fallback: Any = 0) -> Any:
    if key in kpis:
        return kpis[key]
    nested = kpis.get("kpis")
    if isinstance(nested, dict):
        return nested.get(key, fallback)
    return fallback



def first_existing(df: pd.DataFrame, candidates: Iterable[str]) -> str | None:
    for col in candidates:
        if col in df.columns:
            return col
    return None



def subset_columns(df: pd.DataFrame, columns: list[str]) -> list[str]:
    return [c for c in columns if c in df.columns]



def shorten(text: Any, max_len: int = 160) -> str:
    if text is None or (isinstance(text, float) and math.isnan(text)):
        return ""
    s = str(text).replace("\n", " ").replace("\r", " ").strip()
    if len(s) <= max_len:
        return s
    return s[: max_len - 1] + "…"



def tier_label(tier: str) -> str:
    return TIER_LABELS.get(str(tier), str(tier))



def tier_badge_html(tier: str) -> str:
    color = TIER_COLORS.get(str(tier), "#94a3b8")
    label = tier_label(str(tier))
    return f'<span class="pill" style="border-color:{color}; color:{color};">{label}</span>'



def metric_card(label: str, value: Any, help_text: str | None = None) -> None:
    tooltip = f'<div class="small-muted">{help_text}</div>' if help_text else ""
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
            {tooltip}
        </div>
        """,
        unsafe_allow_html=True,
    )



def render_top_cards(df: pd.DataFrame, max_cards: int = 6) -> None:
    if df.empty:
        st.info("No hay candidatos con los filtros actuales.")
        return

    for _, row in df.head(max_cards).iterrows():
        rank = safe_int(row.get("hidden_gem_selected_rank"), 0)
        score = safe_float(row.get("hidden_gem_score"), 0.0)
        dish = row.get("dish_dashboard_name") or row.get("dish_display_name") or row.get("dish_name") or "Plato"
        place = row.get("place_name", "Local")
        city = row.get("inferred_city", "")
        state = row.get("inferred_state", "")
        explanation = shorten(row.get("ranking_explanation", ""), 300)
        mentions = safe_int(row.get("mention_count"), 0)
        reviews = safe_int(row.get("review_count"), 0)
        pos = pct(row.get("positive_ratio", 0.0))
        neg = pct(row.get("negative_ratio", 0.0))
        tier = str(row.get("hidden_gem_tier", ""))

        st.markdown(
            f"""
            <div class="candidate-card">
                <div style="display:flex; justify-content:space-between; gap:1rem; align-items:flex-start;">
                    <div>
                        <div class="small-muted">#{rank} · {city}, {state}</div>
                        <h4 style="margin:0.1rem 0 0.25rem 0;">{dish} en {place}</h4>
                        {tier_badge_html(tier)}
                    </div>
                    <div class="score-badge">{score:.1f}/100</div>
                </div>
                <div class="small-muted" style="margin-top:0.35rem;">
                    {mentions} menciones · {reviews} reviews · {pos} positivas · {neg} negativas
                </div>
                <p style="margin:0.55rem 0 0 0;">{explanation}</p>
            </div>
            """,
            unsafe_allow_html=True,
        )



def render_bar_chart(
    df: pd.DataFrame,
    x: str,
    y: str,
    title: str,
    color: str | None = None,
    top_n: int = 25,
    chart_key: str | None = None,
) -> None:
    if df.empty or x not in df.columns or y not in df.columns:
        st.info("No hay datos suficientes para esta gráfica.")
        return

    plot_df = df[[x, y] + ([color] if color and color in df.columns else [])].dropna(subset=[x, y]).copy()
    plot_df = plot_df.sort_values(y, ascending=False).head(top_n)
    if plot_df.empty:
        st.info("No hay datos suficientes para esta gráfica.")
        return

    if HAS_PLOTLY:
        fig = px.bar(
            plot_df,
            x=x,
            y=y,
            color=color if color in plot_df.columns else None,
            title=title,
            text=y,
        )
        fig.update_layout(height=440, xaxis_title="", yaxis_title="", showlegend=bool(color and color in plot_df.columns))
        fig.update_xaxes(tickangle=-35)
        st.plotly_chart(fig, use_container_width=True, key=chart_key or f"bar_{x}_{y}_{title}")
    else:
        st.bar_chart(plot_df.set_index(x)[y])



def render_pie_or_bar_tiers(
    tier_df: pd.DataFrame,
    candidates_df: pd.DataFrame,
    chart_key: str = "tier_distribution_chart",
) -> None:
    if tier_df.empty and candidates_df.empty:
        st.info("No hay datos de tiers.")
        return

    if tier_df.empty:
        tier_df = (
            candidates_df.groupby("hidden_gem_tier", dropna=False)
            .agg(candidate_count=("hidden_gem_candidate_id", "count"), avg_score=("hidden_gem_score", "mean"))
            .reset_index()
        )
    count_col = first_existing(tier_df, ["candidate_count", "selected_count", "count"])
    if count_col is None or "hidden_gem_tier" not in tier_df.columns:
        st.dataframe(tier_df, use_container_width=True)
        return

    tier_df = tier_df.copy()
    tier_df["tier_label"] = tier_df["hidden_gem_tier"].map(tier_label)
    tier_df["tier_order"] = tier_df["hidden_gem_tier"].map(TIER_ORDER).fillna(0)
    tier_df = tier_df.sort_values("tier_order", ascending=False)

    if HAS_PLOTLY:
        fig = px.pie(
            tier_df,
            names="tier_label",
            values=count_col,
            title="Distribución por tier del ranking Yelp prototype",
            hole=0.45,
        )
        fig.update_layout(height=430)
        st.plotly_chart(fig, use_container_width=True, key=chart_key)
    else:
        st.bar_chart(tier_df.set_index("tier_label")[count_col])



def candidate_option_label(row: pd.Series) -> str:
    rank = safe_int(row.get("hidden_gem_selected_rank"), 0)
    score = safe_float(row.get("hidden_gem_score"), 0.0)
    dish = row.get("dish_dashboard_name") or row.get("dish_display_name") or row.get("dish_name") or "Plato"
    place = row.get("place_name", "Local")
    city = row.get("inferred_city", "")
    state = row.get("inferred_state", "")
    return f"#{rank} · {dish} · {place} · {city}, {state} · {score:.1f}"



def get_candidate_mentions(mentions_df: pd.DataFrame, candidate_id: str, place_id: str, dish_id: str) -> pd.DataFrame:
    if mentions_df.empty:
        return pd.DataFrame()
    if "hidden_gem_candidate_id" in mentions_df.columns:
        out = mentions_df[mentions_df["hidden_gem_candidate_id"].astype(str) == str(candidate_id)].copy()
        if not out.empty:
            return out
    place_mask = mentions_df.get("place_id", pd.Series(dtype=str)).astype(str) == str(place_id)
    dish_mask = mentions_df.get("dish_id", pd.Series(dtype=str)).astype(str) == str(dish_id)
    return mentions_df[place_mask & dish_mask].copy()


# =============================================================================
# Filtering
# =============================================================================


def apply_filters(
    df: pd.DataFrame,
    states: list[str],
    cities: list[str],
    dishes: list[str],
    tiers: list[str],
    evidence: list[str],
    min_score: float,
    only_top_strong: bool,
    query: str,
) -> pd.DataFrame:
    if df.empty:
        return df
    out = df.copy()

    if states and "inferred_state" in out.columns:
        out = out[out["inferred_state"].isin(states)]
    if cities and "inferred_city" in out.columns:
        out = out[out["inferred_city"].isin(cities)]
    if dishes and "dish_dashboard_name" in out.columns:
        out = out[out["dish_dashboard_name"].isin(dishes)]
    if tiers and "hidden_gem_tier" in out.columns:
        out = out[out["hidden_gem_tier"].isin(tiers)]
    if evidence and "evidence_tier" in out.columns:
        out = out[out["evidence_tier"].isin(evidence)]
    if "hidden_gem_score" in out.columns:
        out = out[out["hidden_gem_score"].fillna(0) >= float(min_score)]
    if only_top_strong and "hidden_gem_tier" in out.columns:
        out = out[out["hidden_gem_tier"].isin(["top_hidden_gem", "strong_hidden_gem"])]

    if query:
        q = query.strip().lower()
        if q:
            search_cols = [
                c
                for c in ["place_name", "dish_dashboard_name", "dish_name", "inferred_city", "inferred_state", "address_text"]
                if c in out.columns
            ]
            if search_cols:
                mask = pd.Series(False, index=out.index)
                for col in search_cols:
                    mask = mask | out[col].astype(str).str.lower().str.contains(q, na=False)
                out = out[mask]

    sort_cols = [c for c in ["hidden_gem_selected_rank", "hidden_gem_score", "mention_count", "review_count"] if c in out.columns]
    if sort_cols:
        out = out.sort_values(sort_cols, ascending=[True] + [False] * (len(sort_cols) - 1), na_position="last")
    return out.reset_index(drop=True)


# =============================================================================
# Sections
# =============================================================================


def render_header(metadata: dict[str, Any], export_summary: dict[str, Any]) -> None:
    st.markdown('<div class="main-title">🧪 Hidden Gems · Yelp AI Prototype</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="subtitle">Dashboard de validación IA a gran escala: reviews de Yelp → platos → sentimiento → señales → ranking.</div>',
        unsafe_allow_html=True,
    )

    ranking_scope = metadata.get("ranking_scope") or export_summary.get("filters", {}).get("ranking_scope", "yelp_prototype")
    ranking_version = metadata.get("ranking_version") or export_summary.get("filters", {}).get("ranking_version", "hidden_gems_ranking_v1")
    generated_at = metadata.get("generated_at") or export_summary.get("generated_at", "")

    st.markdown(
        f"""
        <div class="hero-box">
            <span class="pill">ranking_scope = {ranking_scope}</span>
            <span class="pill">version = {ranking_version}</span>
            <span class="pill">generated_at = {generated_at}</span>
            <span class="pill">is_production_ready = false</span>
        </div>
        <div class="benchmark-warning">
            <strong>Importante:</strong> este dashboard representa el benchmark/prototipo IA sobre Yelp Open Dataset.
            No es un ranking productivo de Sevilla ni debe mezclarse con el dashboard local Sevilla.
        </div>
        """,
        unsafe_allow_html=True,
    )



def render_kpis(kpis: dict[str, Any]) -> None:
    cols = st.columns(6)
    with cols[0]:
        metric_card("Candidatos", format_number(get_kpi(kpis, "selected_candidates")), "Hidden Gems seleccionados en Yelp prototype")
    with cols[1]:
        metric_card("Locales", format_number(get_kpi(kpis, "selected_places")), "Locales con candidatos seleccionados")
    with cols[2]:
        metric_card("Platos", format_number(get_kpi(kpis, "selected_dishes")), "Platos distintos en el ranking")
    with cols[3]:
        metric_card("Ciudades", format_number(get_kpi(kpis, "selected_cities")), "Ciudades representadas en Yelp")
    with cols[4]:
        metric_card("Menciones", format_number(get_kpi(kpis, "total_mentions_selected")), "Menciones de platos asociadas al ranking")
    with cols[5]:
        metric_card("Score máximo", format_number(get_kpi(kpis, "max_score"), 1), "Mejor score del prototipo")

    cols2 = st.columns(4)
    with cols2[0]:
        st.metric("Top Hidden Gems", format_number(get_kpi(kpis, "top_hidden_gem_count")))
    with cols2[1]:
        st.metric("Strong", format_number(get_kpi(kpis, "strong_hidden_gem_count")))
    with cols2[2]:
        st.metric("Promising", format_number(get_kpi(kpis, "promising_hidden_gem_count")))
    with cols2[3]:
        st.metric("Exploratory", format_number(get_kpi(kpis, "exploratory_hidden_gem_count")))



def render_ranking_tab(filtered: pd.DataFrame, all_selected: pd.DataFrame, tier_summary: pd.DataFrame) -> None:
    st.subheader("Top Hidden Gems Yelp Prototype")
    left, right = st.columns([1.1, 1])

    with left:
        render_top_cards(filtered, max_cards=8)

    with right:
        render_pie_or_bar_tiers(tier_summary, all_selected, chart_key="overview_tier_distribution")

    st.markdown("### Tabla exploradora")
    display_cols = subset_columns(filtered, MAIN_COLUMNS)
    table_df = filtered[display_cols].copy() if display_cols else filtered.copy()
    if "ranking_explanation" in table_df.columns:
        table_df["ranking_explanation"] = table_df["ranking_explanation"].map(lambda x: shorten(x, 180))
    st.dataframe(table_df, use_container_width=True, height=520)



def render_geo_tab(filtered: pd.DataFrame, city_summary: pd.DataFrame, state_summary: pd.DataFrame) -> None:
    st.subheader("Exploración geográfica del prototipo")
    st.caption("Yelp no representa barrios de Sevilla. Aquí se explora por ciudad y estado del dataset Yelp.")

    col1, col2 = st.columns(2)
    with col1:
        city_col = first_existing(city_summary, ["inferred_city", "city", "city_name"])
        count_col = first_existing(city_summary, ["selected_count", "candidate_count", "count"])
        if city_col and count_col:
            render_bar_chart(city_summary, city_col, count_col, "Top ciudades por candidatos", top_n=20, chart_key="territory_top_cities")
        else:
            st.dataframe(city_summary, use_container_width=True)

    with col2:
        state_col = first_existing(state_summary, ["inferred_state", "state", "state_name"])
        count_col = first_existing(state_summary, ["selected_count", "candidate_count", "count"])
        if state_col and count_col:
            render_bar_chart(state_summary, state_col, count_col, "Top estados por candidatos", top_n=20, chart_key="territory_top_states")
        else:
            st.dataframe(state_summary, use_container_width=True)

    st.markdown("### Mapa de candidatos")
    map_df = filtered.dropna(subset=["latitude", "longitude"]).copy() if {"latitude", "longitude"}.issubset(filtered.columns) else pd.DataFrame()
    if map_df.empty:
        st.info("No hay coordenadas disponibles con los filtros actuales.")
    elif HAS_PLOTLY:
        map_df["hover_label"] = (
            map_df["dish_dashboard_name"].astype(str)
            + " · "
            + map_df["place_name"].astype(str)
            + " · "
            + map_df["inferred_city"].astype(str)
            + ", "
            + map_df["inferred_state"].astype(str)
        )
        fig = px.scatter_map(
            map_df,
            lat="latitude",
            lon="longitude",
            color="hidden_gem_tier",
            size="hidden_gem_score",
            hover_name="hover_label",
            hover_data={
                "hidden_gem_score": ":.2f",
                "mention_count": True,
                "review_count": True,
                "positive_ratio": ":.2%",
                "latitude": False,
                "longitude": False,
            },
            zoom=3,
            height=560,
            title="Candidatos geolocalizados del prototipo Yelp",
        )
        fig.update_layout(mapbox_style="open-street-map", legend_title_text="Tier")
        st.plotly_chart(fig, use_container_width=True, key="territory_map_candidates")
    else:
        st.map(map_df.rename(columns={"latitude": "lat", "longitude": "lon"})[["lat", "lon"]])

    st.markdown("### Resumen por ciudad")
    st.dataframe(city_summary, use_container_width=True, height=360)

    st.markdown("### Resumen por estado")
    st.dataframe(state_summary, use_container_width=True, height=300)



def render_dish_tab(filtered: pd.DataFrame, dish_summary: pd.DataFrame) -> None:
    st.subheader("Exploración por plato")

    count_col = first_existing(dish_summary, ["selected_count", "candidate_count", "count"])
    dish_col = first_existing(dish_summary, ["dish_dashboard_name", "dish_display_name", "dish_name"])
    max_col = first_existing(dish_summary, ["max_score", "max_hidden_gem_score"])

    col1, col2 = st.columns(2)
    with col1:
        if dish_col and count_col:
            render_bar_chart(dish_summary, dish_col, count_col, "Platos con más candidatos", top_n=25, chart_key="dish_most_candidates")
        else:
            st.dataframe(dish_summary, use_container_width=True)
    with col2:
        if dish_col and max_col:
            render_bar_chart(dish_summary, dish_col, max_col, "Platos por score máximo", top_n=25, chart_key="dish_max_score")
        else:
            st.dataframe(dish_summary, use_container_width=True)

    st.markdown("### Top locales por plato con filtros actuales")
    display_cols = subset_columns(
        filtered,
        [
            "dish_dashboard_name",
            "hidden_gem_selected_rank",
            "hidden_gem_score",
            "place_name",
            "inferred_city",
            "inferred_state",
            "hidden_gem_tier",
            "mention_count",
            "review_count",
            "positive_ratio",
            "evidence_tier",
        ],
    )
    st.dataframe(filtered[display_cols], use_container_width=True, height=520)



def render_place_tab(filtered: pd.DataFrame, place_summary: pd.DataFrame) -> None:
    st.subheader("Exploración por local")

    count_col = first_existing(place_summary, ["selected_count", "candidate_count", "count"])
    place_col = first_existing(place_summary, ["place_name", "place_canonical_name"])
    max_col = first_existing(place_summary, ["max_score", "max_hidden_gem_score"])

    col1, col2 = st.columns(2)
    with col1:
        if place_col and count_col:
            render_bar_chart(place_summary, place_col, count_col, "Locales con más platos candidatos", top_n=25, chart_key="place_most_dishes")
        else:
            st.dataframe(place_summary, use_container_width=True)
    with col2:
        if place_col and max_col:
            render_bar_chart(place_summary, place_col, max_col, "Locales por mejor score", top_n=25, chart_key="place_max_score")
        else:
            st.dataframe(place_summary, use_container_width=True)

    st.markdown("### Resumen por local")
    st.dataframe(place_summary, use_container_width=True, height=520)



def render_detail_tab(filtered: pd.DataFrame, mention_examples: pd.DataFrame) -> None:
    st.subheader("Detalle de candidato")
    if filtered.empty:
        st.info("No hay candidatos con los filtros actuales.")
        return

    options_df = filtered.copy().reset_index(drop=True)
    labels = [candidate_option_label(row) for _, row in options_df.iterrows()]
    selected_label = st.selectbox("Selecciona un candidato", labels, index=0)
    selected_idx = labels.index(selected_label)
    row = options_df.iloc[selected_idx]

    dish = row.get("dish_dashboard_name") or row.get("dish_display_name") or row.get("dish_name") or "Plato"
    place = row.get("place_name", "Local")
    city = row.get("inferred_city", "")
    state = row.get("inferred_state", "")
    score = safe_float(row.get("hidden_gem_score"), 0.0)
    tier = str(row.get("hidden_gem_tier", ""))

    st.markdown(
        f"""
        <div class="candidate-card">
            <div class="small-muted">{city}, {state}</div>
            <h2 style="margin:0.1rem 0 0.3rem 0;">{dish} en {place}</h2>
            {tier_badge_html(tier)}
            <span class="score-badge">{score:.1f}/100</span>
            <p style="margin-top:0.75rem;">{row.get("ranking_explanation", "")}</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    cols = st.columns(5)
    cols[0].metric("Menciones", format_number(row.get("mention_count")))
    cols[1].metric("Reviews", format_number(row.get("review_count")))
    cols[2].metric("Positivas", pct(row.get("positive_ratio")))
    cols[3].metric("Negativas", pct(row.get("negative_ratio")))
    cols[4].metric("Confianza", pct(row.get("avg_sentiment_confidence")))

    st.markdown("### Componentes del score")
    component_cols = [c for c in DETAIL_COMPONENT_COLUMNS if c in row.index]
    if component_cols:
        comp_df = pd.DataFrame(
            {"component": component_cols, "value": [safe_float(row.get(c), 0.0) for c in component_cols]}
        )
        if HAS_PLOTLY:
            fig = px.bar(comp_df, x="component", y="value", text="value", title="Componentes normalizados")
            fig.update_traces(texttemplate="%{text:.2f}")
            fig.update_layout(height=360, xaxis_title="", yaxis_title="")
            fig.update_xaxes(tickangle=-30)
            st.plotly_chart(fig, use_container_width=True, key="candidate_score_components")
        else:
            st.bar_chart(comp_df.set_index("component")["value"])

    st.markdown("### Penalizaciones")
    penalty_cols = [c for c in PENALTY_COLUMNS if c in row.index]
    if penalty_cols:
        penalty_df = pd.DataFrame(
            {"penalty": penalty_cols, "factor": [safe_float(row.get(c), 0.0) for c in penalty_cols]}
        )
        st.dataframe(penalty_df, use_container_width=True, hide_index=True)

    st.markdown("### Datos técnicos")
    technical_cols = subset_columns(
        pd.DataFrame([row]),
        [
            "hidden_gem_candidate_id",
            "place_id",
            "dish_id",
            "dish_place_signal_id",
            "ranking_version",
            "ranking_scope",
            "aggregate_quality_tier",
            "evidence_tier",
            "avg_ner_confidence",
            "bayesian_sentiment_score",
            "total_signal_weight",
            "avg_rating",
            "human_review_status",
            "is_production_ready",
        ],
    )
    st.dataframe(pd.DataFrame([row])[technical_cols].T.rename(columns={0: "value"}), use_container_width=True)

    st.markdown("### Menciones y reseñas asociadas")
    candidate_mentions = get_candidate_mentions(
        mention_examples,
        candidate_id=str(row.get("hidden_gem_candidate_id", "")),
        place_id=str(row.get("place_id", "")),
        dish_id=str(row.get("dish_id", "")),
    )
    if candidate_mentions.empty:
        st.info("No hay menciones exportadas para este candidato. Regenera con --include-mentions si quieres ver ejemplos.")
        return

    mention_cols = subset_columns(
        candidate_mentions,
        [
            "rating_value",
            "review_language",
            "review_created_at",
            "mention_text",
            "sentiment_label",
            "sentiment_score",
            "sentiment_confidence",
            "sentiment_reliability_tier",
            "sentiment_reason",
            "target_clause_context",
            "near_mention_context",
            "context_sentence",
        ],
    )
    compact = candidate_mentions[mention_cols].copy()
    for text_col in ["target_clause_context", "near_mention_context", "context_sentence"]:
        if text_col in compact.columns:
            compact[text_col] = compact[text_col].map(lambda x: shorten(x, 220))
    st.dataframe(compact, use_container_width=True, height=360)

    if "review_text_raw" in candidate_mentions.columns:
        st.markdown("#### Reseñas completas")
        st.caption("Las reseñas completas se muestran solo bajo demanda. No subas este CSV a Git si contiene texto completo.")
        for i, (_, mention_row) in enumerate(candidate_mentions.iterrows(), start=1):
            label = (
                f"Review {i} · rating {mention_row.get('rating_value', '')} · "
                f"{mention_row.get('sentiment_label', '')} · confianza {safe_float(mention_row.get('sentiment_confidence'), 0.0):.2f}"
            )
            with st.expander(label):
                st.write(mention_row.get("review_text_raw", ""))



def render_quality_tab(
    metadata: dict[str, Any],
    export_summary: dict[str, Any],
    quality_summary: pd.DataFrame,
    data_contract: dict[str, Any],
) -> None:
    st.subheader("Calidad, checks y limitaciones")

    checks = export_summary.get("checks", {}) if isinstance(export_summary, dict) else {}
    if checks:
        check_rows = [
            {"check": key, "status": bool(value), "value": value}
            for key, value in checks.items()
        ]
        check_df = pd.DataFrame(check_rows)
        st.dataframe(check_df, use_container_width=True, hide_index=True)
    elif not quality_summary.empty:
        st.dataframe(quality_summary, use_container_width=True)
    else:
        st.info("No se encontró quality_summary ni checks en dashboard_export_summary.json.")

    st.markdown("### Limitaciones del prototipo Yelp")
    st.markdown(
        """
        - Yelp se usa como **benchmark/prototipo IA**, no como fuente productiva de Sevilla.
        - El ranking usa `ranking_scope = yelp_prototype` y `is_production_ready = false`.
        - La geografía disponible es ciudad/estado, no barrios de Sevilla.
        - El corpus principal está en inglés y puede tener sesgos geográficos del dataset Yelp.
        - Las reseñas completas solo deben usarse para revisión local o académica, no para publicar artefactos pesados.
        """
    )

    with st.expander("Metadata"):
        st.json(metadata)

    with st.expander("Dashboard export summary"):
        st.json(export_summary)

    with st.expander("Data contract"):
        st.json(data_contract)


# =============================================================================
# Main
# =============================================================================


def main() -> None:
    with st.sidebar:
        st.header("⚙️ Configuración")
        data_dir_input = st.text_input("Carpeta de datos", value=str(DEFAULT_DATA_DIR))
        data_dir = normalize_path(data_dir_input)

        st.caption("Genera estos datos con `scripts/export_yelp_dashboard_data.py`.")

    data = load_dashboard_data(data_dir)
    metadata = data["metadata"]
    kpis = data["kpis"]
    export_summary = data["export_summary"]
    data_contract = data["data_contract"]

    candidates_all: pd.DataFrame = data["candidates_all"]
    candidates_detail: pd.DataFrame = data["candidates_detail"]
    top_global_file: pd.DataFrame = data["top_global"]
    city_summary: pd.DataFrame = data["city_summary"]
    state_summary: pd.DataFrame = data["state_summary"]
    dish_summary: pd.DataFrame = data["dish_summary"]
    place_summary: pd.DataFrame = data["place_summary"]
    tier_summary: pd.DataFrame = data["tier_summary"]
    quality_summary: pd.DataFrame = data["quality_summary"]
    mention_examples: pd.DataFrame = data["mention_examples"]

    if candidates_all.empty and candidates_detail.empty:
        st.error(
            "No se encontraron candidates_all.csv ni candidates_detail.csv. "
            "Ejecuta primero scripts/export_yelp_dashboard_data.py."
        )
        st.code(
            "python -m scripts.export_yelp_dashboard_data `\n"
            "  --output-dir data/artifacts/ai/yelp/dashboard `\n"
            "  --expected-selected 622 `\n"
            "  --include-mentions `\n"
            "  --strict"
        )
        return

    base_df = candidates_detail if not candidates_detail.empty else candidates_all
    selected_df = base_df[base_df.get("is_selected", True) == True].copy() if "is_selected" in base_df.columns else base_df.copy()

    render_header(metadata, export_summary)
    render_kpis(kpis)

    # Sidebar filters after data load
    with st.sidebar:
        st.divider()
        st.header("🔎 Filtros")
        include_all = st.checkbox("Incluir no seleccionados", value=False, help="Yelp prototype normalmente tiene 622 seleccionados.")
        working_df = candidates_all.copy() if include_all and not candidates_all.empty else selected_df.copy()

        state_options = sorted([x for x in working_df.get("inferred_state", pd.Series(dtype=str)).dropna().astype(str).unique() if x])
        selected_states = st.multiselect("Estado", state_options, default=[])

        city_source = working_df
        if selected_states and "inferred_state" in city_source.columns:
            city_source = city_source[city_source["inferred_state"].isin(selected_states)]
        city_options = sorted([x for x in city_source.get("inferred_city", pd.Series(dtype=str)).dropna().astype(str).unique() if x])
        selected_cities = st.multiselect("Ciudad", city_options, default=[])

        dish_options = sorted([x for x in working_df.get("dish_dashboard_name", pd.Series(dtype=str)).dropna().astype(str).unique() if x])
        selected_dishes = st.multiselect("Plato", dish_options, default=[])

        tier_options = [t for t in TIER_ORDER.keys() if t in set(working_df.get("hidden_gem_tier", pd.Series(dtype=str)).astype(str))]
        selected_tiers = st.multiselect("Tier", tier_options, default=[])

        evidence_options = sorted([x for x in working_df.get("evidence_tier", pd.Series(dtype=str)).dropna().astype(str).unique() if x])
        selected_evidence = st.multiselect("Evidencia", evidence_options, default=[])

        score_series = working_df.get("hidden_gem_score", pd.Series([0.0]))
        score_min_available = safe_float(score_series.min(), 0.0)
        default_min_score = float(max(0.0, math.floor(score_min_available)))
        min_score = st.slider(
            "Score mínimo",
            min_value=0.0,
            max_value=100.0,
            value=default_min_score,
            step=1.0,
        )

        only_top_strong = st.checkbox("Solo Top + Strong", value=False)
        search_query = st.text_input("Búsqueda libre", value="", placeholder="local, plato, ciudad, estado...")

        st.divider()
        st.caption("Este dashboard no consulta PostgreSQL directamente; lee CSV/JSON exportados.")

    working_df = candidates_all.copy() if include_all and not candidates_all.empty else selected_df.copy()
    filtered = apply_filters(
        working_df,
        states=selected_states,
        cities=selected_cities,
        dishes=selected_dishes,
        tiers=selected_tiers,
        evidence=selected_evidence,
        min_score=min_score,
        only_top_strong=only_top_strong,
        query=search_query,
    )

    st.markdown("---")
    fcols = st.columns(5)
    fcols[0].metric("Filtrados", format_number(len(filtered)))
    fcols[1].metric("Locales", format_number(filtered["place_id"].nunique() if "place_id" in filtered.columns else 0))
    fcols[2].metric("Platos", format_number(filtered["dish_id"].nunique() if "dish_id" in filtered.columns else 0))
    fcols[3].metric("Ciudades", format_number(filtered["inferred_city"].nunique() if "inferred_city" in filtered.columns else 0))
    fcols[4].metric("Estados", format_number(filtered["inferred_state"].nunique() if "inferred_state" in filtered.columns else 0))

    tab_overview, tab_ranking, tab_geo, tab_dish, tab_place, tab_detail, tab_quality = st.tabs(
        [
            "📌 Resumen",
            "🏆 Ranking",
            "🌎 Ciudades/Estados",
            "🍽️ Platos",
            "🏪 Locales",
            "🔍 Detalle",
            "✅ Calidad",
        ]
    )

    with tab_overview:
        st.subheader("Resumen del benchmark IA")
        st.markdown(
            """
            Este panel muestra la validación a gran escala del flujo IA de Hidden Gems sobre Yelp:
            detección de platos, sentimiento por mención, agregación local-plato y ranking explicable.
            """
        )
        col1, col2 = st.columns([1, 1])
        with col1:
            render_pie_or_bar_tiers(tier_summary, selected_df, chart_key="quality_tier_distribution")
        with col2:
            city_col = first_existing(city_summary, ["inferred_city", "city", "city_name"])
            count_col = first_existing(city_summary, ["selected_count", "candidate_count", "count"])
            if city_col and count_col:
                render_bar_chart(city_summary, city_col, count_col, "Ciudades con más candidatos", top_n=15, chart_key="quality_top_cities")
            else:
                st.dataframe(city_summary, use_container_width=True)

        st.markdown("### Top 10 global")
        render_top_cards(filtered, max_cards=10)

    with tab_ranking:
        render_ranking_tab(filtered, selected_df, tier_summary)

    with tab_geo:
        render_geo_tab(filtered, city_summary, state_summary)

    with tab_dish:
        render_dish_tab(filtered, dish_summary)

    with tab_place:
        render_place_tab(filtered, place_summary)

    with tab_detail:
        render_detail_tab(filtered, mention_examples)

    with tab_quality:
        render_quality_tab(metadata, export_summary, quality_summary, data_contract)


if __name__ == "__main__":
    main()
