"""
Check an AI review export JSONL generated by scripts.export_reviews_for_ai.

This script validates the exported review corpus before using it in the
Hidden Gems AI prototype pipeline.

Typical usage in PowerShell:

python -m scripts.check_ai_review_export `
  --input-path data/artifacts/ai/sevilla/reviews_for_ai_google_places.jsonl `
  --summary-path data/artifacts/ai/sevilla/reviews_for_ai_google_places_summary.json `
  --report-path data/artifacts/ai/sevilla/check_reviews_for_ai_google_places.json
"""

from __future__ import annotations

import argparse
import json
import logging
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


LOGGER = logging.getLogger(__name__)

REQUIRED_FIELDS = [
    "review_id",
    "place_id",
    "place_source_ref_id",
    "source_system_code",
    "source_review_id",
    "source_place_record_id",
    "place_name",
    "rating_value",
    "review_language",
    "text",
    "is_operational_review",
    "is_training_eligible",
]

RECOMMENDED_FIELDS = [
    "district_id",
    "district_name",
    "neighborhood_id",
    "neighborhood_name",
    "address_text",
    "city",
    "review_created_at",
    "text_normalized",
    "place_latitude",
    "place_longitude",
    "text_length_chars",
]

SEVILLA_BBOX = {
    "south": 37.30,
    "north": 37.46,
    "west": -6.08,
    "east": -5.88,
}


def configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(payload, file, ensure_ascii=False, indent=2)
        file.write("\n")


def iter_jsonl(path: Path) -> Iterable[tuple[int, dict[str, Any] | None, str | None]]:
    with path.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            raw = line.strip()
            if not raw:
                yield line_number, None, "empty_line"
                continue
            try:
                row = json.loads(raw)
            except json.JSONDecodeError as exc:
                yield line_number, None, f"invalid_json: {exc}"
                continue
            if not isinstance(row, dict):
                yield line_number, None, "json_value_is_not_object"
                continue
            yield line_number, row, None


def is_blank(value: Any) -> bool:
    return value is None or (isinstance(value, str) and value.strip() == "")


def safe_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def in_bbox(lat: Any, lon: Any, bbox: dict[str, float]) -> bool | None:
    lat_f = safe_float(lat)
    lon_f = safe_float(lon)
    if lat_f is None or lon_f is None:
        return None
    return bbox["south"] <= lat_f <= bbox["north"] and bbox["west"] <= lon_f <= bbox["east"]


def top_counter(counter: Counter, limit: int = 20) -> dict[str, int]:
    return {str(key): int(value) for key, value in counter.most_common(limit)}


def describe_lengths(lengths: list[int]) -> dict[str, Any]:
    if not lengths:
        return {"min": None, "max": None, "mean": None}
    return {
        "min": min(lengths),
        "max": max(lengths),
        "mean": round(sum(lengths) / len(lengths), 4),
    }


def validate_export(
    input_path: Path,
    summary_path: Path | None,
    expected_source_code: str | None,
    expected_language: str | None,
    min_rows: int,
    min_text_length: int | None,
    require_neighborhood: bool,
    check_sevilla_bbox: bool,
    top_n: int,
) -> dict[str, Any]:
    if not input_path.exists():
        raise FileNotFoundError(f"No existe el JSONL de entrada: {input_path}")

    LOGGER.info("Validando export JSONL: %s", input_path)

    total_rows = 0
    invalid_line_count = 0
    invalid_line_samples: list[dict[str, Any]] = []

    review_ids: Counter = Counter()
    source_review_ids: Counter = Counter()
    place_ids: Counter = Counter()
    place_source_ref_ids: Counter = Counter()
    neighborhood_ids: Counter = Counter()
    district_ids: Counter = Counter()

    source_counts: Counter = Counter()
    language_counts: Counter = Counter()
    rating_counts: Counter = Counter()
    district_counts: Counter = Counter()
    neighborhood_counts: Counter = Counter()
    place_counts: Counter = Counter()

    missing_required: Counter = Counter()
    missing_recommended: Counter = Counter()
    invalid_rating_count = 0
    invalid_boolean_count = 0
    text_too_short_count = 0
    text_length_mismatch_count = 0
    rows_without_text = 0
    rows_without_neighborhood = 0
    rows_without_district = 0
    rows_without_coordinates = 0
    rows_outside_sevilla_bbox = 0
    rows_with_non_expected_source = 0
    rows_with_non_expected_language = 0
    rows_not_operational = 0
    rows_not_training_eligible = 0

    text_lengths: list[int] = []
    sample_rows: list[dict[str, Any]] = []

    for line_number, row, error in iter_jsonl(input_path):
        if error is not None:
            invalid_line_count += 1
            if len(invalid_line_samples) < 10:
                invalid_line_samples.append({"line_number": line_number, "error": error})
            continue

        assert row is not None
        total_rows += 1

        if len(sample_rows) < 5:
            sample_rows.append(row)

        for field in REQUIRED_FIELDS:
            if field not in row or is_blank(row.get(field)):
                missing_required[field] += 1

        for field in RECOMMENDED_FIELDS:
            if field not in row or is_blank(row.get(field)):
                missing_recommended[field] += 1

        review_id = row.get("review_id")
        source_review_id = row.get("source_review_id")
        place_id = row.get("place_id")
        place_source_ref_id = row.get("place_source_ref_id")
        neighborhood_id = row.get("neighborhood_id")
        district_id = row.get("district_id")

        if not is_blank(review_id):
            review_ids[str(review_id)] += 1
        if not is_blank(source_review_id):
            source_review_ids[str(source_review_id)] += 1
        if not is_blank(place_id):
            place_ids[str(place_id)] += 1
        if not is_blank(place_source_ref_id):
            place_source_ref_ids[str(place_source_ref_id)] += 1
        if not is_blank(neighborhood_id):
            neighborhood_ids[str(neighborhood_id)] += 1
        if not is_blank(district_id):
            district_ids[str(district_id)] += 1

        source_code = row.get("source_system_code")
        language = row.get("review_language")
        rating = safe_float(row.get("rating_value"))
        district_name = row.get("district_name")
        neighborhood_name = row.get("neighborhood_name")
        place_name = row.get("place_name")

        if not is_blank(source_code):
            source_counts[str(source_code)] += 1
        if expected_source_code and source_code != expected_source_code:
            rows_with_non_expected_source += 1

        if not is_blank(language):
            language_counts[str(language)] += 1
        if expected_language and language != expected_language:
            rows_with_non_expected_language += 1

        if rating is None:
            invalid_rating_count += 1
        else:
            rating_counts[str(rating)] += 1

        if not is_blank(district_name):
            district_counts[str(district_name)] += 1
        if not is_blank(neighborhood_name):
            neighborhood_counts[str(neighborhood_name)] += 1
        if not is_blank(place_name):
            place_counts[str(place_name)] += 1

        text = row.get("text")
        if is_blank(text):
            rows_without_text += 1
            text_len = 0
        else:
            text_len = len(str(text))
            text_lengths.append(text_len)

        if min_text_length is not None and text_len < min_text_length:
            text_too_short_count += 1

        exported_text_len = row.get("text_length_chars")
        exported_text_len_f = safe_float(exported_text_len)
        if exported_text_len is not None and exported_text_len_f is not None:
            if int(exported_text_len_f) != text_len:
                text_length_mismatch_count += 1

        if is_blank(neighborhood_id) or is_blank(neighborhood_name):
            rows_without_neighborhood += 1
        if is_blank(district_id) or is_blank(district_name):
            rows_without_district += 1

        is_operational = row.get("is_operational_review")
        is_training = row.get("is_training_eligible")
        if not isinstance(is_operational, bool) or not isinstance(is_training, bool):
            invalid_boolean_count += 1
        if is_operational is not True:
            rows_not_operational += 1
        if is_training is not True:
            rows_not_training_eligible += 1

        bbox_result = in_bbox(row.get("place_latitude"), row.get("place_longitude"), SEVILLA_BBOX)
        if bbox_result is None:
            rows_without_coordinates += 1
        elif check_sevilla_bbox and bbox_result is False:
            rows_outside_sevilla_bbox += 1

    duplicate_review_id_count = sum(count - 1 for count in review_ids.values() if count > 1)
    duplicate_source_review_id_count = sum(count - 1 for count in source_review_ids.values() if count > 1)

    summary_payload: dict[str, Any] | None = None
    summary_comparison: dict[str, Any] = {}
    if summary_path:
        if summary_path.exists():
            summary_payload = read_json(summary_path)
            summary_comparison = {
                "summary_file_exists": True,
                "total_exported_matches": summary_payload.get("total_exported") == total_rows,
                "unique_review_id_count_matches": summary_payload.get("unique_review_id_count") == len(review_ids),
                "unique_source_review_id_count_matches": summary_payload.get("unique_source_review_id_count") == len(source_review_ids),
                "unique_place_id_count_matches": summary_payload.get("unique_place_id_count") == len(place_ids),
                "unique_neighborhood_id_count_matches": summary_payload.get("unique_neighborhood_id_count") == len(neighborhood_ids),
                "unique_district_id_count_matches": summary_payload.get("unique_district_id_count") == len(district_ids),
            }
        else:
            summary_comparison = {"summary_file_exists": False}

    checks = {
        "input_file_exists": input_path.exists(),
        "has_rows": total_rows > 0,
        "meets_min_rows": total_rows >= min_rows,
        "invalid_json_is_zero": invalid_line_count == 0,
        "all_required_fields_present": not missing_required,
        "review_ids_are_unique": duplicate_review_id_count == 0 and len(review_ids) == total_rows,
        "source_review_ids_are_unique": duplicate_source_review_id_count == 0 and len(source_review_ids) == total_rows,
        "all_have_text": rows_without_text == 0,
        "all_meet_min_text_length": text_too_short_count == 0,
        "all_ratings_valid": invalid_rating_count == 0,
        "all_boolean_flags_valid": invalid_boolean_count == 0,
        "all_are_operational_reviews": rows_not_operational == 0,
        "all_are_training_eligible": rows_not_training_eligible == 0,
        "all_match_expected_source_when_provided": rows_with_non_expected_source == 0,
        "all_match_expected_language_when_provided": rows_with_non_expected_language == 0,
        "all_have_neighborhood_when_required": (not require_neighborhood) or rows_without_neighborhood == 0,
        "all_have_district": rows_without_district == 0,
        "all_have_coordinates": rows_without_coordinates == 0,
        "all_coordinates_inside_sevilla_bbox_when_checked": (not check_sevilla_bbox) or rows_outside_sevilla_bbox == 0,
        "text_length_field_matches_text": text_length_mismatch_count == 0,
    }

    checks.update({f"summary_{key}": value for key, value in summary_comparison.items()})

    report = {
        "script": "scripts.check_ai_review_export",
        "version": "ai_review_export_check_v1",
        "generated_at": utc_now_iso(),
        "input_path": str(input_path),
        "summary_path": str(summary_path) if summary_path else None,
        "totals": {
            "rows": total_rows,
            "invalid_line_count": invalid_line_count,
            "unique_review_id_count": len(review_ids),
            "unique_source_review_id_count": len(source_review_ids),
            "unique_place_id_count": len(place_ids),
            "unique_place_source_ref_id_count": len(place_source_ref_ids),
            "unique_neighborhood_id_count": len(neighborhood_ids),
            "unique_district_id_count": len(district_ids),
            "duplicate_review_id_count": duplicate_review_id_count,
            "duplicate_source_review_id_count": duplicate_source_review_id_count,
        },
        "quality": {
            "missing_required": dict(missing_required),
            "missing_recommended": dict(missing_recommended),
            "rows_without_text": rows_without_text,
            "text_too_short_count": text_too_short_count,
            "text_length_mismatch_count": text_length_mismatch_count,
            "invalid_rating_count": invalid_rating_count,
            "invalid_boolean_count": invalid_boolean_count,
            "rows_without_neighborhood": rows_without_neighborhood,
            "rows_without_district": rows_without_district,
            "rows_without_coordinates": rows_without_coordinates,
            "rows_outside_sevilla_bbox": rows_outside_sevilla_bbox,
            "rows_with_non_expected_source": rows_with_non_expected_source,
            "rows_with_non_expected_language": rows_with_non_expected_language,
            "rows_not_operational": rows_not_operational,
            "rows_not_training_eligible": rows_not_training_eligible,
        },
        "distributions": {
            "source_system_counts": top_counter(source_counts, top_n),
            "language_counts": top_counter(language_counts, top_n),
            "rating_counts": top_counter(rating_counts, top_n),
            "district_counts": top_counter(district_counts, top_n),
            "neighborhood_counts": top_counter(neighborhood_counts, top_n),
            "top_places_by_review_count": top_counter(place_counts, top_n),
        },
        "text_length_chars": describe_lengths(text_lengths),
        "summary_comparison": summary_comparison,
        "invalid_line_samples": invalid_line_samples,
        "sample_rows": sample_rows,
        "parameters": {
            "expected_source_code": expected_source_code,
            "expected_language": expected_language,
            "min_rows": min_rows,
            "min_text_length": min_text_length,
            "require_neighborhood": require_neighborhood,
            "check_sevilla_bbox": check_sevilla_bbox,
            "sevilla_bbox": SEVILLA_BBOX,
            "top_n": top_n,
        },
        "checks": checks,
        "overall_passed": all(bool(value) for value in checks.values()),
    }

    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate a Hidden Gems AI review export JSONL.")
    parser.add_argument("--input-path", required=True, type=Path, help="Path to reviews_for_ai JSONL.")
    parser.add_argument("--summary-path", type=Path, help="Optional summary JSON generated by export_reviews_for_ai.")
    parser.add_argument("--report-path", type=Path, help="Optional output path for the check report JSON.")
    parser.add_argument("--expected-source-code", default="google_places", help="Expected source_system_code. Use empty string to disable.")
    parser.add_argument("--expected-language", help="Expected language code. Example: es")
    parser.add_argument("--min-rows", type=int, default=1, help="Minimum number of rows expected.")
    parser.add_argument("--min-text-length", type=int, default=20, help="Minimum text length expected.")
    parser.add_argument("--require-neighborhood", action="store_true", help="Fail if any row lacks neighborhood.")
    parser.add_argument("--check-sevilla-bbox", action="store_true", help="Check coordinates against a broad Sevilla bbox.")
    parser.add_argument("--top-n", type=int, default=20, help="Number of top values to keep in distributions.")
    return parser.parse_args()


def main() -> None:
    configure_logging()
    args = parse_args()

    expected_source_code = args.expected_source_code.strip() if args.expected_source_code else None

    report = validate_export(
        input_path=args.input_path,
        summary_path=args.summary_path,
        expected_source_code=expected_source_code,
        expected_language=args.expected_language,
        min_rows=args.min_rows,
        min_text_length=args.min_text_length,
        require_neighborhood=args.require_neighborhood,
        check_sevilla_bbox=args.check_sevilla_bbox,
        top_n=args.top_n,
    )

    if args.report_path:
        write_json(args.report_path, report)
        LOGGER.info("Informe guardado en: %s", args.report_path)

    LOGGER.info("Resultado global: %s", "OK" if report["overall_passed"] else "WARNING/ERROR")
    print(json.dumps({
        "overall_passed": report["overall_passed"],
        "totals": report["totals"],
        "quality": report["quality"],
        "text_length_chars": report["text_length_chars"],
        "distributions": {
            "source_system_counts": report["distributions"]["source_system_counts"],
            "language_counts": report["distributions"]["language_counts"],
            "rating_counts": report["distributions"]["rating_counts"],
        },
        "checks": report["checks"],
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
