"""Load AI aggregated dish-place signals and Hidden Gems ranking into PostgreSQL.

This script imports the downstream AI artifacts generated by notebooks 10 and 11:

    dish_business_ranking_candidates_v1.csv
    hidden_gems_selected_candidates_v1.csv

It loads two tables:

    hidden_gems.dish_place_signal
    hidden_gems.hidden_gem_candidate

Prerequisites:

1. The AI schema must exist: db/ddl/07_ai_module.sql.
2. The dish catalog and aliases must already be loaded.
3. Yelp core places and reviews must already be loaded.
4. Dish mentions and mention sentiments should already be loaded.

Recommended execution from repository root.

PowerShell dry-run:
    python -m scripts.load_ai_signals_and_ranking `
      --business-signals-path data/artifacts/ai/aggregation/dish_business_ranking_candidates_v1.csv `
      --ranking-path data/artifacts/ai/ranking/hidden_gems_selected_candidates_v1.csv `
      --dry-run

PowerShell real load:
    python -m scripts.load_ai_signals_and_ranking `
      --business-signals-path data/artifacts/ai/aggregation/dish_business_ranking_candidates_v1.csv `
      --ranking-path data/artifacts/ai/ranking/hidden_gems_selected_candidates_v1.csv

Optional report:
    python -m scripts.load_ai_signals_and_ranking `
      --business-signals-path data/artifacts/ai/aggregation/dish_business_ranking_candidates_v1.csv `
      --ranking-path data/artifacts/ai/ranking/hidden_gems_selected_candidates_v1.csv `
      --report-path data/artifacts/ai/ranking/load_ai_signals_and_ranking_report.json

The script is idempotent:

- dish_place_signal is upserted by (place_id, dish_id, ai_pipeline_run_id, signal_version).
- hidden_gem_candidate is upserted by (place_id, dish_id, ai_pipeline_run_id, ranking_version, ranking_scope).
"""

from __future__ import annotations

import argparse
import ast
import json
import re
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import Connection

try:
    from tqdm.auto import tqdm
except Exception:  # pragma: no cover
    def tqdm(iterable, **_: Any):
        return iterable

from src.db.database import engine


# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

DEFAULT_SCHEMA = "hidden_gems"
DEFAULT_SOURCE_CODE = "yelp_open_dataset"

DEFAULT_SIGNAL_RUN_CODE = "ai_run_yelp_signal_aggregation_v1_import"
DEFAULT_RANKING_RUN_CODE = "ai_run_yelp_hidden_gems_ranking_v1_import"

DEFAULT_SIGNAL_VERSION = "signal_aggregation_v1"
DEFAULT_RANKING_VERSION = "hidden_gems_ranking_v1"
DEFAULT_RANKING_SCOPE = "yelp_prototype"

SCHEMA_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")

VALID_AGGREGATE_QUALITY_TIERS = {"high", "medium", "low"}
VALID_EVIDENCE_TIERS = {"strong", "solid", "emerging", "weak"}
VALID_HIDDEN_GEM_TIERS = {
    "top_hidden_gem",
    "strong_hidden_gem",
    "promising_hidden_gem",
    "exploratory_hidden_gem",
    "not_selected",
}
VALID_RANKING_SCOPES = {"yelp_prototype", "sevilla_global", "sevilla_neighborhood", "manual_review", "other"}
VALID_HUMAN_REVIEW_STATUS = {"not_reviewed", "pending", "approved", "rejected", "corrected"}


# -----------------------------------------------------------------------------
# Data classes
# -----------------------------------------------------------------------------

@dataclass
class SignalInputStats:
    rows_total: int = 0
    rows_considered: int = 0
    skipped_missing_required_fields: int = 0
    skipped_missing_place_mapping: int = 0
    skipped_missing_dish_mapping: int = 0
    skipped_invalid_counts: int = 0
    skipped_invalid_tiers: int = 0


@dataclass
class RankingInputStats:
    rows_total: int = 0
    rows_considered: int = 0
    skipped_missing_required_fields: int = 0
    skipped_missing_place_mapping: int = 0
    skipped_missing_dish_mapping: int = 0
    skipped_missing_signal_mapping: int = 0
    skipped_invalid_score: int = 0
    skipped_invalid_tier: int = 0


@dataclass
class LoadStats:
    signals_upserted: int = 0
    hidden_gem_candidates_upserted: int = 0
    dry_run: bool = False


# -----------------------------------------------------------------------------
# Generic helpers
# -----------------------------------------------------------------------------


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def validate_schema_name(schema: str) -> str:
    schema = str(schema).strip()
    if not SCHEMA_RE.match(schema):
        raise ValueError(f"Invalid PostgreSQL schema name: {schema!r}")
    return schema


def qname(schema: str, table: str) -> str:
    schema = validate_schema_name(schema)
    return f'"{schema}"."{table}"'


def normalize_space(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def normalize_lower(value: Any) -> str:
    return normalize_space(value).lower()


def truncate(value: Any, max_len: int) -> str | None:
    value = normalize_space(value)
    if not value:
        return None
    return value[:max_len]


def safe_float(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, float) and pd.isna(value):
        return None
    try:
        return float(value)
    except Exception:
        return None


def safe_int(value: Any) -> int | None:
    value_float = safe_float(value)
    if value_float is None:
        return None
    try:
        return int(value_float)
    except Exception:
        return None


def safe_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    if isinstance(value, float) and pd.isna(value):
        return default
    value_str = str(value).strip().lower()
    if value_str in {"true", "1", "yes", "y", "t"}:
        return True
    if value_str in {"false", "0", "no", "n", "f"}:
        return False
    return default


def clamp_float(value: Any, min_value: float, max_value: float) -> float | None:
    value_float = safe_float(value)
    if value_float is None:
        return None
    return max(min_value, min(max_value, value_float))


def non_negative_int(value: Any, default: int = 0) -> int:
    value_int = safe_int(value)
    if value_int is None:
        return default
    return max(0, value_int)


def ratio_value(value: Any) -> float | None:
    return clamp_float(value, 0.0, 1.0)


def score_minus_one_to_one(value: Any) -> float | None:
    return clamp_float(value, -1.0, 1.0)


def score_zero_to_hundred(value: Any) -> float | None:
    return clamp_float(value, 0.0, 100.0)


def parse_list_like(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, float) and pd.isna(value):
        return []
    if isinstance(value, list):
        return [normalize_space(v) for v in value if normalize_space(v)]
    if isinstance(value, tuple):
        return [normalize_space(v) for v in value if normalize_space(v)]

    value_str = str(value).strip()
    if not value_str:
        return []

    try:
        parsed = json.loads(value_str)
        if isinstance(parsed, list):
            return [normalize_space(v) for v in parsed if normalize_space(v)]
    except Exception:
        pass

    try:
        parsed = ast.literal_eval(value_str)
        if isinstance(parsed, list):
            return [normalize_space(v) for v in parsed if normalize_space(v)]
    except Exception:
        pass

    if value_str.startswith("[") and value_str.endswith("]"):
        inner = value_str[1:-1].strip()
        if not inner:
            return []
        return [part.strip().strip("'").strip('"') for part in inner.split(",") if part.strip()]

    return [value_str]


def json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, default=str)


def read_csv_records(path: Path, max_rows: int | None = None) -> tuple[list[dict[str, Any]], list[str]]:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    df = pd.read_csv(path, nrows=max_rows, keep_default_na=False)
    return df.to_dict(orient="records"), df.columns.tolist()


def write_json_report(path: Path, report: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False, default=str)
    print(f"Report written to: {path}")


# -----------------------------------------------------------------------------
# Database helpers
# -----------------------------------------------------------------------------


def get_source_system_id(conn: Connection, schema: str, source_code: str) -> str:
    row = conn.execute(
        text(
            f"""
            SELECT source_system_id
            FROM {qname(schema, 'source_system')}
            WHERE source_code = :source_code
            """
        ),
        {"source_code": source_code},
    ).mappings().first()

    if row is None:
        raise RuntimeError(f"source_system not found for source_code={source_code!r}")

    return str(row["source_system_id"])


def upsert_ai_pipeline_run(
    conn: Connection,
    schema: str,
    *,
    run_code: str,
    run_type: str,
    input_artifacts: list[dict[str, Any]],
    output_artifacts: list[dict[str, Any]],
    config: dict[str, Any],
    metrics: dict[str, Any] | None = None,
    notes: str | None = None,
) -> str:
    now = utc_now()
    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'ai_pipeline_run')} (
                run_code,
                run_type,
                status,
                started_at,
                finished_at,
                duration_seconds,
                input_artifacts_json,
                output_artifacts_json,
                config_json,
                metrics_json,
                notes
            )
            VALUES (
                :run_code,
                :run_type,
                'completed',
                :started_at,
                :finished_at,
                0,
                CAST(:input_artifacts_json AS jsonb),
                CAST(:output_artifacts_json AS jsonb),
                CAST(:config_json AS jsonb),
                CAST(:metrics_json AS jsonb),
                :notes
            )
            ON CONFLICT (run_code) DO UPDATE SET
                run_type = EXCLUDED.run_type,
                status = EXCLUDED.status,
                finished_at = EXCLUDED.finished_at,
                duration_seconds = EXCLUDED.duration_seconds,
                input_artifacts_json = EXCLUDED.input_artifacts_json,
                output_artifacts_json = EXCLUDED.output_artifacts_json,
                config_json = EXCLUDED.config_json,
                metrics_json = EXCLUDED.metrics_json,
                notes = EXCLUDED.notes
            RETURNING ai_pipeline_run_id
            """
        ),
        {
            "run_code": run_code,
            "run_type": run_type,
            "started_at": now,
            "finished_at": now,
            "input_artifacts_json": json_dumps(input_artifacts),
            "output_artifacts_json": json_dumps(output_artifacts),
            "config_json": json_dumps(config),
            "metrics_json": json_dumps(metrics or {}),
            "notes": notes,
        },
    ).mappings().one()

    return str(row["ai_pipeline_run_id"])


def load_place_mapping(conn: Connection, schema: str, source_system_id: str) -> dict[str, str]:
    print("Loading Yelp business_id -> place_id mapping...")
    rows = conn.execute(
        text(
            f"""
            SELECT source_record_id, place_id
            FROM {qname(schema, 'place_source_ref')}
            WHERE source_system_id = :source_system_id
              AND source_record_id IS NOT NULL
            """
        ),
        {"source_system_id": source_system_id},
    ).mappings().all()

    mapping = {str(row["source_record_id"]): str(row["place_id"]) for row in rows}
    print(f"Place mapping loaded: {len(mapping):,}")
    return mapping


def load_dish_mapping(conn: Connection, schema: str) -> dict[str, str]:
    print("Loading dish mapping...")
    rows = conn.execute(
        text(
            f"""
            SELECT dish_id, normalized_name
            FROM {qname(schema, 'dish')}
            WHERE is_active = TRUE
            """
        )
    ).mappings().all()

    mapping = {str(row["normalized_name"]).strip().lower(): str(row["dish_id"]) for row in rows}
    print(f"Dish mapping loaded: {len(mapping):,}")
    return mapping


def load_existing_signal_mapping(
    conn: Connection,
    schema: str,
    *,
    ai_pipeline_run_id: str,
    signal_version: str,
) -> dict[tuple[str, str], str]:
    rows = conn.execute(
        text(
            f"""
            SELECT dish_place_signal_id, place_id, dish_id
            FROM {qname(schema, 'dish_place_signal')}
            WHERE ai_pipeline_run_id = :ai_pipeline_run_id
              AND signal_version = :signal_version
            """
        ),
        {
            "ai_pipeline_run_id": ai_pipeline_run_id,
            "signal_version": signal_version,
        },
    ).mappings().all()

    return {(str(row["place_id"]), str(row["dish_id"])): str(row["dish_place_signal_id"]) for row in rows}


# -----------------------------------------------------------------------------
# Row preparation
# -----------------------------------------------------------------------------


def build_signal_quality_flags(row: dict[str, Any]) -> list[str]:
    flags = parse_list_like(row.get("dish_name_quality_flags"))

    if safe_bool(row.get("is_hard_noise_dish_name"), default=False):
        flags.append("hard_noise_dish_name")

    if safe_bool(row.get("is_possible_beverage"), default=False):
        flags.append("possible_beverage")

    if not safe_bool(row.get("is_ranking_ready_v1"), default=False):
        flags.append("not_ranking_ready_v1")

    candidate_tier = normalize_lower(row.get("preliminary_candidate_tier_v1"))
    if candidate_tier:
        flags.append(f"candidate_tier:{candidate_tier}")

    return sorted(set(flag for flag in flags if flag))


def build_ranking_quality_flags(row: dict[str, Any]) -> list[str]:
    flags = parse_list_like(row.get("dish_name_quality_flags"))

    if safe_bool(row.get("is_hard_noise_dish_name"), default=False):
        flags.append("hard_noise_dish_name")

    if safe_bool(row.get("is_possible_beverage"), default=False):
        flags.append("possible_beverage")

    tier = normalize_lower(row.get("hidden_gem_tier_v1"))
    if tier:
        flags.append(f"hidden_gem_tier:{tier}")

    return sorted(set(flag for flag in flags if flag))


def validate_and_prepare_signal(
    row: dict[str, Any],
    *,
    place_mapping: dict[str, str],
    dish_mapping: dict[str, str],
    signal_run_id: str,
    signal_version: str,
) -> tuple[dict[str, Any] | None, str | None]:
    business_id = normalize_space(row.get("business_id"))
    canonical_name = normalize_lower(row.get("canonical_dish_name_v2"))

    if not business_id or not canonical_name:
        return None, "missing_required_fields"

    place_id = place_mapping.get(business_id)
    if place_id is None:
        return None, "missing_place_mapping"

    dish_id = dish_mapping.get(canonical_name)
    if dish_id is None:
        return None, "missing_dish_mapping"

    mention_count = non_negative_int(row.get("mention_count"))
    review_count = non_negative_int(row.get("review_count"))
    positive_mentions = non_negative_int(row.get("positive_mentions"))
    neutral_mentions = non_negative_int(row.get("neutral_mentions"))
    negative_mentions = non_negative_int(row.get("negative_mentions"))

    if positive_mentions + neutral_mentions + negative_mentions > mention_count:
        return None, "invalid_counts"

    high_rel = non_negative_int(row.get("high_reliability_mentions"))
    medium_rel = non_negative_int(row.get("medium_reliability_mentions"))
    low_rel = non_negative_int(row.get("low_reliability_mentions"))

    if high_rel + medium_rel + low_rel > mention_count:
        return None, "invalid_counts"

    aggregate_quality_tier = normalize_lower(row.get("aggregate_quality_tier")) or None
    if aggregate_quality_tier not in VALID_AGGREGATE_QUALITY_TIERS:
        aggregate_quality_tier = None

    evidence_tier = normalize_lower(row.get("business_dish_evidence_tier")) or None
    if evidence_tier not in VALID_EVIDENCE_TIERS:
        return None, "invalid_tiers"

    params = {
        "place_id": place_id,
        "dish_id": dish_id,
        "ai_pipeline_run_id": signal_run_id,
        "signal_version": signal_version,
        "mention_count": mention_count,
        "review_count": review_count,
        "positive_mentions": positive_mentions,
        "neutral_mentions": neutral_mentions,
        "negative_mentions": negative_mentions,
        "positive_ratio": ratio_value(row.get("positive_ratio")),
        "negative_ratio": ratio_value(row.get("negative_ratio")),
        "avg_ner_confidence": ratio_value(row.get("avg_ner_confidence")),
        "avg_sentiment_confidence": ratio_value(row.get("avg_sentiment_confidence")),
        "avg_signal_weight": safe_float(row.get("avg_signal_weight")),
        "total_signal_weight": safe_float(row.get("total_signal_weight")),
        "avg_rating": clamp_float(row.get("avg_rating"), 0.0, 5.0),
        "avg_sentiment_score_raw": clamp_float(row.get("avg_sentiment_score_raw"), -5.0, 5.0),
        "confidence_weighted_sentiment": score_minus_one_to_one(row.get("confidence_weighted_sentiment")),
        "bayesian_sentiment_score": score_minus_one_to_one(row.get("bayesian_sentiment_score")),
        "reliability_high_ratio": ratio_value(row.get("reliability_high_ratio")),
        "high_reliability_mentions": high_rel,
        "medium_reliability_mentions": medium_rel,
        "low_reliability_mentions": low_rel,
        "aggregate_quality_tier": aggregate_quality_tier,
        "evidence_tier": evidence_tier,
        "is_rankable_candidate": safe_bool(row.get("is_ranking_ready_v1"), default=False),
        "quality_flags": json_dumps(build_signal_quality_flags(row)),
    }

    return params, None


def validate_and_prepare_ranking(
    row: dict[str, Any],
    *,
    place_mapping: dict[str, str],
    dish_mapping: dict[str, str],
    signal_mapping: dict[tuple[str, str], str],
    ranking_run_id: str,
    ranking_version: str,
    ranking_scope: str,
) -> tuple[dict[str, Any] | None, str | None]:
    business_id = normalize_space(row.get("business_id"))
    canonical_name = normalize_lower(row.get("canonical_dish_name_v2"))

    if not business_id or not canonical_name:
        return None, "missing_required_fields"

    place_id = place_mapping.get(business_id)
    if place_id is None:
        return None, "missing_place_mapping"

    dish_id = dish_mapping.get(canonical_name)
    if dish_id is None:
        return None, "missing_dish_mapping"

    signal_id = signal_mapping.get((place_id, dish_id))
    if signal_id is None:
        return None, "missing_signal_mapping"

    hidden_gem_score = score_zero_to_hundred(row.get("hidden_gem_score_v1"))
    if hidden_gem_score is None:
        return None, "invalid_score"

    hidden_gem_tier = normalize_lower(row.get("hidden_gem_tier_v1"))
    if hidden_gem_tier not in VALID_HIDDEN_GEM_TIERS:
        return None, "invalid_tier"

    is_selected = safe_bool(row.get("is_hidden_gem_candidate_v1"), default=(hidden_gem_tier != "not_selected"))
    selected_rank = safe_int(row.get("hidden_gem_selected_rank_v1"))
    if is_selected and selected_rank is None:
        # Constraint requires selected rank when selected.
        selected_rank = safe_int(row.get("hidden_gem_rank_v1")) or 1

    params = {
        "place_id": place_id,
        "dish_id": dish_id,
        "dish_place_signal_id": signal_id,
        "neighborhood_id": None,
        "district_id": None,
        "ai_pipeline_run_id": ranking_run_id,
        "ranking_version": ranking_version,
        "ranking_scope": ranking_scope,
        "hidden_gem_score": hidden_gem_score,
        "hidden_gem_score_base": score_zero_to_hundred(row.get("hidden_gem_score_base_v1")),
        "hidden_gem_rank": safe_int(row.get("hidden_gem_rank_v1")),
        "hidden_gem_selected_rank": selected_rank,
        "hidden_gem_tier": hidden_gem_tier,
        "is_selected": is_selected,
        "local_sentiment_component": ratio_value(row.get("local_sentiment_component")),
        "evidence_component": ratio_value(row.get("evidence_component")),
        "confidence_component": ratio_value(row.get("confidence_component")),
        "positive_balance_component": ratio_value(row.get("positive_balance_component")),
        "rarity_component": ratio_value(row.get("rarity_component")),
        "local_outperformance_component": ratio_value(row.get("local_outperformance_component")),
        "hiddenness_component": ratio_value(row.get("hiddenness_component")),
        "preliminary_component": ratio_value(row.get("preliminary_component")),
        "negative_penalty_factor": ratio_value(row.get("negative_penalty_factor_final")),
        "beverage_penalty_factor": ratio_value(row.get("beverage_penalty_factor_final")),
        "noise_penalty_factor": ratio_value(row.get("noise_penalty_factor_final")),
        "low_evidence_penalty_factor": ratio_value(row.get("low_evidence_penalty_factor_final")),
        "ranking_explanation": normalize_space(row.get("ranking_explanation_v1")) or None,
        "ranking_config_json": json_dumps({
            "ranking_version": ranking_version,
            "ranking_scope": ranking_scope,
            "source": "notebook_11_hidden_gems_ranking_v1",
            "business_id": business_id,
            "canonical_dish_name_v2": canonical_name,
        }),
        "quality_flags": json_dumps(build_ranking_quality_flags(row)),
        "is_production_ready": False,
        "human_review_status": "not_reviewed",
    }

    return params, None


# -----------------------------------------------------------------------------
# Upserts
# -----------------------------------------------------------------------------


def upsert_dish_place_signal(conn: Connection, schema: str, params: dict[str, Any]) -> str:
    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish_place_signal')} (
                place_id,
                dish_id,
                ai_pipeline_run_id,
                signal_version,
                mention_count,
                review_count,
                positive_mentions,
                neutral_mentions,
                negative_mentions,
                positive_ratio,
                negative_ratio,
                avg_ner_confidence,
                avg_sentiment_confidence,
                avg_signal_weight,
                total_signal_weight,
                avg_rating,
                avg_sentiment_score_raw,
                confidence_weighted_sentiment,
                bayesian_sentiment_score,
                reliability_high_ratio,
                high_reliability_mentions,
                medium_reliability_mentions,
                low_reliability_mentions,
                aggregate_quality_tier,
                evidence_tier,
                is_rankable_candidate,
                quality_flags
            )
            VALUES (
                :place_id,
                :dish_id,
                :ai_pipeline_run_id,
                :signal_version,
                :mention_count,
                :review_count,
                :positive_mentions,
                :neutral_mentions,
                :negative_mentions,
                :positive_ratio,
                :negative_ratio,
                :avg_ner_confidence,
                :avg_sentiment_confidence,
                :avg_signal_weight,
                :total_signal_weight,
                :avg_rating,
                :avg_sentiment_score_raw,
                :confidence_weighted_sentiment,
                :bayesian_sentiment_score,
                :reliability_high_ratio,
                :high_reliability_mentions,
                :medium_reliability_mentions,
                :low_reliability_mentions,
                :aggregate_quality_tier,
                :evidence_tier,
                :is_rankable_candidate,
                CAST(:quality_flags AS jsonb)
            )
            ON CONFLICT (place_id, dish_id, ai_pipeline_run_id, signal_version)
            DO UPDATE SET
                mention_count = EXCLUDED.mention_count,
                review_count = EXCLUDED.review_count,
                positive_mentions = EXCLUDED.positive_mentions,
                neutral_mentions = EXCLUDED.neutral_mentions,
                negative_mentions = EXCLUDED.negative_mentions,
                positive_ratio = EXCLUDED.positive_ratio,
                negative_ratio = EXCLUDED.negative_ratio,
                avg_ner_confidence = EXCLUDED.avg_ner_confidence,
                avg_sentiment_confidence = EXCLUDED.avg_sentiment_confidence,
                avg_signal_weight = EXCLUDED.avg_signal_weight,
                total_signal_weight = EXCLUDED.total_signal_weight,
                avg_rating = EXCLUDED.avg_rating,
                avg_sentiment_score_raw = EXCLUDED.avg_sentiment_score_raw,
                confidence_weighted_sentiment = EXCLUDED.confidence_weighted_sentiment,
                bayesian_sentiment_score = EXCLUDED.bayesian_sentiment_score,
                reliability_high_ratio = EXCLUDED.reliability_high_ratio,
                high_reliability_mentions = EXCLUDED.high_reliability_mentions,
                medium_reliability_mentions = EXCLUDED.medium_reliability_mentions,
                low_reliability_mentions = EXCLUDED.low_reliability_mentions,
                aggregate_quality_tier = EXCLUDED.aggregate_quality_tier,
                evidence_tier = EXCLUDED.evidence_tier,
                is_rankable_candidate = EXCLUDED.is_rankable_candidate,
                quality_flags = EXCLUDED.quality_flags
            RETURNING dish_place_signal_id
            """
        ),
        params,
    ).mappings().one()

    return str(row["dish_place_signal_id"])


def upsert_hidden_gem_candidate(conn: Connection, schema: str, params: dict[str, Any]) -> str:
    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'hidden_gem_candidate')} (
                place_id,
                dish_id,
                dish_place_signal_id,
                neighborhood_id,
                district_id,
                ai_pipeline_run_id,
                ranking_version,
                ranking_scope,
                hidden_gem_score,
                hidden_gem_score_base,
                hidden_gem_rank,
                hidden_gem_selected_rank,
                hidden_gem_tier,
                is_selected,
                local_sentiment_component,
                evidence_component,
                confidence_component,
                positive_balance_component,
                rarity_component,
                local_outperformance_component,
                hiddenness_component,
                preliminary_component,
                negative_penalty_factor,
                beverage_penalty_factor,
                noise_penalty_factor,
                low_evidence_penalty_factor,
                ranking_explanation,
                ranking_config_json,
                quality_flags,
                is_production_ready,
                human_review_status
            )
            VALUES (
                :place_id,
                :dish_id,
                :dish_place_signal_id,
                :neighborhood_id,
                :district_id,
                :ai_pipeline_run_id,
                :ranking_version,
                :ranking_scope,
                :hidden_gem_score,
                :hidden_gem_score_base,
                :hidden_gem_rank,
                :hidden_gem_selected_rank,
                :hidden_gem_tier,
                :is_selected,
                :local_sentiment_component,
                :evidence_component,
                :confidence_component,
                :positive_balance_component,
                :rarity_component,
                :local_outperformance_component,
                :hiddenness_component,
                :preliminary_component,
                :negative_penalty_factor,
                :beverage_penalty_factor,
                :noise_penalty_factor,
                :low_evidence_penalty_factor,
                :ranking_explanation,
                CAST(:ranking_config_json AS jsonb),
                CAST(:quality_flags AS jsonb),
                :is_production_ready,
                :human_review_status
            )
            ON CONFLICT (place_id, dish_id, ai_pipeline_run_id, ranking_version, ranking_scope)
            DO UPDATE SET
                dish_place_signal_id = EXCLUDED.dish_place_signal_id,
                neighborhood_id = EXCLUDED.neighborhood_id,
                district_id = EXCLUDED.district_id,
                hidden_gem_score = EXCLUDED.hidden_gem_score,
                hidden_gem_score_base = EXCLUDED.hidden_gem_score_base,
                hidden_gem_rank = EXCLUDED.hidden_gem_rank,
                hidden_gem_selected_rank = EXCLUDED.hidden_gem_selected_rank,
                hidden_gem_tier = EXCLUDED.hidden_gem_tier,
                is_selected = EXCLUDED.is_selected,
                local_sentiment_component = EXCLUDED.local_sentiment_component,
                evidence_component = EXCLUDED.evidence_component,
                confidence_component = EXCLUDED.confidence_component,
                positive_balance_component = EXCLUDED.positive_balance_component,
                rarity_component = EXCLUDED.rarity_component,
                local_outperformance_component = EXCLUDED.local_outperformance_component,
                hiddenness_component = EXCLUDED.hiddenness_component,
                preliminary_component = EXCLUDED.preliminary_component,
                negative_penalty_factor = EXCLUDED.negative_penalty_factor,
                beverage_penalty_factor = EXCLUDED.beverage_penalty_factor,
                noise_penalty_factor = EXCLUDED.noise_penalty_factor,
                low_evidence_penalty_factor = EXCLUDED.low_evidence_penalty_factor,
                ranking_explanation = EXCLUDED.ranking_explanation,
                ranking_config_json = EXCLUDED.ranking_config_json,
                quality_flags = EXCLUDED.quality_flags,
                is_production_ready = EXCLUDED.is_production_ready,
                human_review_status = EXCLUDED.human_review_status
            RETURNING hidden_gem_candidate_id
            """
        ),
        params,
    ).mappings().one()

    return str(row["hidden_gem_candidate_id"])


# -----------------------------------------------------------------------------
# Main loading logic
# -----------------------------------------------------------------------------


def run_loader(args: argparse.Namespace) -> dict[str, Any]:
    schema = validate_schema_name(args.schema)
    source_code = args.source_code

    if args.ranking_scope not in VALID_RANKING_SCOPES:
        raise ValueError(f"Invalid ranking scope: {args.ranking_scope}")

    business_signals_records: list[dict[str, Any]] = []
    ranking_records: list[dict[str, Any]] = []
    business_signals_columns: list[str] = []
    ranking_columns: list[str] = []

    if args.business_signals_path:
        business_signals_records, business_signals_columns = read_csv_records(
            Path(args.business_signals_path),
            max_rows=args.max_signal_rows,
        )

    if args.ranking_path:
        ranking_records, ranking_columns = read_csv_records(
            Path(args.ranking_path),
            max_rows=args.max_ranking_rows,
        )

    signal_stats = SignalInputStats(
        rows_total=len(business_signals_records),
        rows_considered=len(business_signals_records),
    )
    ranking_stats = RankingInputStats(
        rows_total=len(ranking_records),
        rows_considered=len(ranking_records),
    )
    load_stats = LoadStats(dry_run=args.dry_run)

    with engine.connect() as conn:
        tx = conn.begin()

        try:
            source_system_id = get_source_system_id(conn, schema, source_code)
            place_mapping = load_place_mapping(conn, schema, source_system_id)
            dish_mapping = load_dish_mapping(conn, schema)

            signal_run_id = "00000000-0000-0000-0000-000000000000"
            ranking_run_id = "00000000-0000-0000-0000-000000000000"

            if not args.dry_run:
                signal_run_id = upsert_ai_pipeline_run(
                    conn,
                    schema,
                    run_code=args.signal_run_code,
                    run_type="signal_aggregation",
                    input_artifacts=[{"path": str(args.business_signals_path), "kind": "dish_business_ranking_candidates"}],
                    output_artifacts=[{"table": f"{schema}.dish_place_signal"}],
                    config={
                        "signal_version": args.signal_version,
                        "source_code": source_code,
                        "ranking_scope": args.ranking_scope,
                    },
                    metrics={"input_rows": len(business_signals_records)},
                    notes="Import of Yelp prototype dish-place signals generated by notebook 10. Not production Sevilla data.",
                )

                ranking_run_id = upsert_ai_pipeline_run(
                    conn,
                    schema,
                    run_code=args.ranking_run_code,
                    run_type="hidden_gems_ranking",
                    input_artifacts=[{"path": str(args.ranking_path), "kind": "hidden_gems_selected_candidates"}],
                    output_artifacts=[{"table": f"{schema}.hidden_gem_candidate"}],
                    config={
                        "ranking_version": args.ranking_version,
                        "ranking_scope": args.ranking_scope,
                        "source_code": source_code,
                    },
                    metrics={"input_rows": len(ranking_records)},
                    notes="Import of Yelp prototype Hidden Gems ranking generated by notebook 11. Not production Sevilla data.",
                )

            signal_mapping: dict[tuple[str, str], str] = {}

            if business_signals_records:
                print("Preparing/loading dish_place_signal rows...")
                for row in tqdm(business_signals_records, desc="Signals"):
                    params, skip_reason = validate_and_prepare_signal(
                        row,
                        place_mapping=place_mapping,
                        dish_mapping=dish_mapping,
                        signal_run_id=signal_run_id,
                        signal_version=args.signal_version,
                    )

                    if skip_reason:
                        if skip_reason == "missing_required_fields":
                            signal_stats.skipped_missing_required_fields += 1
                        elif skip_reason == "missing_place_mapping":
                            signal_stats.skipped_missing_place_mapping += 1
                        elif skip_reason == "missing_dish_mapping":
                            signal_stats.skipped_missing_dish_mapping += 1
                        elif skip_reason == "invalid_counts":
                            signal_stats.skipped_invalid_counts += 1
                        elif skip_reason == "invalid_tiers":
                            signal_stats.skipped_invalid_tiers += 1
                        continue

                    assert params is not None

                    if args.dry_run:
                        load_stats.signals_upserted += 1
                        signal_mapping[(params["place_id"], params["dish_id"])] = "dry-run-signal-id"
                    else:
                        signal_id = upsert_dish_place_signal(conn, schema, params)
                        load_stats.signals_upserted += 1
                        signal_mapping[(params["place_id"], params["dish_id"])] = signal_id

            elif not args.dry_run:
                signal_mapping = load_existing_signal_mapping(
                    conn,
                    schema,
                    ai_pipeline_run_id=signal_run_id,
                    signal_version=args.signal_version,
                )

            if ranking_records:
                print("Preparing/loading hidden_gem_candidate rows...")
                for row in tqdm(ranking_records, desc="Ranking"):
                    params, skip_reason = validate_and_prepare_ranking(
                        row,
                        place_mapping=place_mapping,
                        dish_mapping=dish_mapping,
                        signal_mapping=signal_mapping,
                        ranking_run_id=ranking_run_id,
                        ranking_version=args.ranking_version,
                        ranking_scope=args.ranking_scope,
                    )

                    if skip_reason:
                        if skip_reason == "missing_required_fields":
                            ranking_stats.skipped_missing_required_fields += 1
                        elif skip_reason == "missing_place_mapping":
                            ranking_stats.skipped_missing_place_mapping += 1
                        elif skip_reason == "missing_dish_mapping":
                            ranking_stats.skipped_missing_dish_mapping += 1
                        elif skip_reason == "missing_signal_mapping":
                            ranking_stats.skipped_missing_signal_mapping += 1
                        elif skip_reason == "invalid_score":
                            ranking_stats.skipped_invalid_score += 1
                        elif skip_reason == "invalid_tier":
                            ranking_stats.skipped_invalid_tier += 1
                        continue

                    assert params is not None

                    if args.dry_run:
                        load_stats.hidden_gem_candidates_upserted += 1
                    else:
                        upsert_hidden_gem_candidate(conn, schema, params)
                        load_stats.hidden_gem_candidates_upserted += 1

            if args.dry_run:
                tx.rollback()
            else:
                tx.commit()

        except Exception:
            tx.rollback()
            raise

    report = {
        "schema": schema,
        "source_code": source_code,
        "business_signals_path": str(args.business_signals_path) if args.business_signals_path else None,
        "ranking_path": str(args.ranking_path) if args.ranking_path else None,
        "signal_version": args.signal_version,
        "ranking_version": args.ranking_version,
        "ranking_scope": args.ranking_scope,
        "dry_run": args.dry_run,
        "columns_detected": {
            "business_signals": business_signals_columns,
            "ranking": ranking_columns,
        },
        "input_stats": {
            "signals": asdict(signal_stats),
            "ranking": asdict(ranking_stats),
        },
        "load_stats": asdict(load_stats),
        "readiness_after_this_step": {
            "dish_place_signals_loaded_or_validated": load_stats.signals_upserted,
            "hidden_gem_candidates_loaded_or_validated": load_stats.hidden_gem_candidates_upserted,
            "ready_for_querying_ai_ranking": (
                load_stats.signals_upserted > 0
                and load_stats.hidden_gem_candidates_upserted > 0
                and signal_stats.skipped_missing_place_mapping == 0
                and signal_stats.skipped_missing_dish_mapping == 0
                and ranking_stats.skipped_missing_signal_mapping == 0
                and ranking_stats.skipped_missing_place_mapping == 0
                and ranking_stats.skipped_missing_dish_mapping == 0
            ),
        },
    }

    return report


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Load AI dish-place signals and Hidden Gems ranking artifacts into PostgreSQL."
    )

    parser.add_argument("--business-signals-path", type=Path, required=True)
    parser.add_argument("--ranking-path", type=Path, required=True)
    parser.add_argument("--schema", default=DEFAULT_SCHEMA)
    parser.add_argument("--source-code", default=DEFAULT_SOURCE_CODE)
    parser.add_argument("--signal-run-code", default=DEFAULT_SIGNAL_RUN_CODE)
    parser.add_argument("--ranking-run-code", default=DEFAULT_RANKING_RUN_CODE)
    parser.add_argument("--signal-version", default=DEFAULT_SIGNAL_VERSION)
    parser.add_argument("--ranking-version", default=DEFAULT_RANKING_VERSION)
    parser.add_argument("--ranking-scope", default=DEFAULT_RANKING_SCOPE)
    parser.add_argument("--max-signal-rows", type=int, default=None)
    parser.add_argument("--max-ranking-rows", type=int, default=None)
    parser.add_argument("--report-path", type=Path, default=None)
    parser.add_argument("--dry-run", action="store_true")

    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    report = run_loader(args)

    print("\n" + "=" * 96)
    print("AI signals and ranking load summary")
    print("=" * 96)
    print(json.dumps(report, indent=2, ensure_ascii=False, default=str)[:12000])

    if args.report_path:
        write_json_report(args.report_path, report)


if __name__ == "__main__":
    main()
