"""Load the AI dish catalog and aliases into PostgreSQL.

This script imports the outputs generated by the Hidden Gems AI normalization module:

- dish_catalog_seed_v2.csv  -> hidden_gems.dish
- dish_aliases_seed_v2.csv  -> hidden_gems.dish_alias

It also seeds the AI model/method versions used across the experimental AI flow and
creates/updates one ai_pipeline_run record for the catalog import.

Recommended execution from the repository root:

Windows PowerShell:
    python -m scripts.load_ai_dish_catalog `
      --catalog-path data/artifacts/ai/normalization/dish_catalog_seed_v2.csv `
      --aliases-path data/artifacts/ai/normalization/dish_aliases_seed_v2.csv `
      --summary-path data/artifacts/ai/normalization/dish_normalization_summary_v2.json

Linux/macOS:
    python -m scripts.load_ai_dish_catalog \
      --catalog-path data/artifacts/ai/normalization/dish_catalog_seed_v2.csv \
      --aliases-path data/artifacts/ai/normalization/dish_aliases_seed_v2.csv \
      --summary-path data/artifacts/ai/normalization/dish_normalization_summary_v2.json

The script is idempotent: it uses upserts and can be executed more than once.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import Connection

try:
    from tqdm.auto import tqdm
except Exception:  # pragma: no cover - tqdm is optional at runtime
    def tqdm(iterable, **_: Any):
        return iterable

from src.config.settings import settings
from src.db.database import engine


# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

ALLOWED_SCHEMA_PATTERN = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")
MAX_VARCHAR_150 = 150
MAX_VARCHAR_255 = 255
MAX_VARCHAR_100 = 100
MAX_VARCHAR_50 = 50
MAX_VARCHAR_10 = 10

ALLOWED_DISH_REVIEW_STATUS = {
    "pending",
    "approved",
    "rejected",
    "needs_merge",
    "needs_split",
}

ALLOWED_ALIAS_TYPES = {
    "canonical",
    "surface_variant",
    "translation",
    "manual_alias",
    "synonym",
    "misspelling",
}

MODEL_VERSION_DEFINITIONS = [
    {
        "model_code": "dish_ner_transformer_v1",
        "model_name": "Dish NER Transformer v1",
        "model_type": "transformer",
        "task_name": "dish_detection",
        "version_label": "v1",
        "description": "Transformer-based token classification model for detecting dish mentions in review text.",
        "framework_name": "transformers",
        "base_model_name": "bert-base-uncased",
        "language_scope": "en",
        "training_dataset_name": "yelp_dish_ner_bio_high_precision_with_negatives",
    },
    {
        "model_code": "dish_normalization_rule_based_v2",
        "model_name": "Dish Normalization Rule-Based v2",
        "model_type": "rule_based",
        "task_name": "dish_normalization",
        "version_label": "v2",
        "description": "Rule-based dish normalization layer with curated overrides, alias generation and catalog seeding.",
        "framework_name": "python_rules",
        "base_model_name": None,
        "language_scope": "en",
        "training_dataset_name": "yelp_dish_mentions_model_v1_full",
    },
    {
        "model_code": "mention_sentiment_hybrid_v1_1",
        "model_name": "Mention Sentiment Hybrid v1.1",
        "model_type": "hybrid",
        "task_name": "mention_sentiment",
        "version_label": "v1.1",
        "description": "Hybrid aspect-level sentiment method combining local context, target clause, lexicons, priors and reliability tiers.",
        "framework_name": "python_rules",
        "base_model_name": None,
        "language_scope": "en",
        "training_dataset_name": "yelp_dish_mentions_normalized_v2",
    },
    {
        "model_code": "signal_aggregation_v1",
        "model_name": "Dish Signal Aggregation v1",
        "model_type": "aggregation",
        "task_name": "signal_aggregation",
        "version_label": "v1",
        "description": "Aggregation layer for converting mention-level signals into dish-place/business-level metrics.",
        "framework_name": "pandas",
        "base_model_name": None,
        "language_scope": "en",
        "training_dataset_name": "dish_mentions_with_sentiment_hybrid_v1",
    },
    {
        "model_code": "hidden_gems_ranking_v1",
        "model_name": "Hidden Gems Ranking v1",
        "model_type": "ranking",
        "task_name": "hidden_gems_ranking",
        "version_label": "v1",
        "description": "Explainable scoring formula combining sentiment, evidence, confidence, hiddenness and quality penalties.",
        "framework_name": "pandas",
        "base_model_name": None,
        "language_scope": "en",
        "training_dataset_name": "dish_business_ranking_candidates_v1",
    },
]


# -----------------------------------------------------------------------------
# Data classes
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class LoadStats:
    catalog_rows: int
    alias_rows: int
    dishes_upserted: int
    aliases_upserted: int
    aliases_skipped_missing_dish: int


# -----------------------------------------------------------------------------
# Generic helpers
# -----------------------------------------------------------------------------

def validate_schema_name(schema: str) -> str:
    schema = str(schema).strip()
    if not ALLOWED_SCHEMA_PATTERN.match(schema):
        raise ValueError(f"Invalid PostgreSQL schema name: {schema!r}")
    return schema


def qname(schema: str, table: str) -> str:
    schema = validate_schema_name(schema)
    return f'"{schema}"."{table}"'


def read_json_file(path: Path | None) -> dict[str, Any]:
    if path is None:
        return {}

    if not path.exists():
        raise FileNotFoundError(f"Summary file not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object in {path}")

    return data


def json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, default=str)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def normalize_space(value: Any) -> str:
    if value is None or pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def truncate(value: Any, max_len: int) -> str | None:
    value = normalize_space(value)
    if not value:
        return None
    return value[:max_len]


def none_if_nan(value: Any) -> Any:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except Exception:
        pass
    return value


def safe_int(value: Any, default: int | None = None) -> int | None:
    value = none_if_nan(value)
    if value is None:
        return default
    try:
        return int(value)
    except Exception:
        return default


def safe_float(value: Any, default: float | None = None) -> float | None:
    value = none_if_nan(value)
    if value is None:
        return default
    try:
        return float(value)
    except Exception:
        return default


def clamp_float(value: Any, min_value: float, max_value: float, default: float | None = None) -> float | None:
    parsed = safe_float(value, default=default)
    if parsed is None:
        return None
    return max(min_value, min(max_value, parsed))


def slugify(value: str, fallback: str = "dish") -> str:
    value = normalize_space(value).lower()
    value = value.replace("&", " and ")
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    if not value:
        value = fallback
    if value[0].isdigit():
        value = f"dish_{value}"
    return value[:MAX_VARCHAR_150].strip("_") or fallback


def build_unique_dish_codes(catalog_df: pd.DataFrame) -> dict[str, str]:
    """Return canonical_name -> unique dish_code."""

    used_codes: set[str] = set()
    mapping: dict[str, str] = {}

    for canonical_name in catalog_df["canonical_dish_name_clean"].tolist():
        base_code = slugify(canonical_name)
        code = base_code
        suffix = 2

        while code in used_codes:
            suffix_text = f"_{suffix}"
            code = f"{base_code[:MAX_VARCHAR_150 - len(suffix_text)]}{suffix_text}"
            suffix += 1

        used_codes.add(code)
        mapping[canonical_name] = code

    return mapping


def to_display_name(value: str) -> str:
    value = normalize_space(value)
    if not value:
        return ""
    # .title() is acceptable for this first seed catalog, but keep small words readable.
    return value.title()


def normalize_review_status(value: Any) -> str:
    value = normalize_space(value).lower()
    if value in ALLOWED_DISH_REVIEW_STATUS:
        return value
    if value in {"not_reviewed", "", "none", "nan"}:
        return "pending"
    return "pending"


def normalize_alias_type(value: Any) -> str:
    value = normalize_space(value).lower()
    if value in ALLOWED_ALIAS_TYPES:
        return value
    return "surface_variant"


# -----------------------------------------------------------------------------
# Input validation
# -----------------------------------------------------------------------------

def load_catalog(path: Path, limit: int | None = None) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Catalog CSV not found: {path}")

    df = pd.read_csv(path)
    if limit is not None:
        df = df.head(limit).copy()

    required_cols = {
        "canonical_dish_name",
    }
    missing = sorted(required_cols - set(df.columns))
    if missing:
        raise ValueError(f"Catalog CSV is missing required columns: {missing}")

    df["canonical_dish_name_clean"] = df["canonical_dish_name"].apply(normalize_space).str.lower()
    df = df[df["canonical_dish_name_clean"].str.len() > 0].copy()
    df = df.drop_duplicates(subset=["canonical_dish_name_clean"], keep="first").reset_index(drop=True)

    if df.empty:
        raise ValueError("Catalog CSV has no valid dish rows after cleaning.")

    return df


def load_aliases(path: Path, limit: int | None = None) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Aliases CSV not found: {path}")

    df = pd.read_csv(path)
    if limit is not None:
        df = df.head(limit).copy()

    required_cols = {
        "canonical_dish_name",
        "alias_text",
    }
    missing = sorted(required_cols - set(df.columns))
    if missing:
        raise ValueError(f"Aliases CSV is missing required columns: {missing}")

    df["canonical_dish_name_clean"] = df["canonical_dish_name"].apply(normalize_space).str.lower()
    df["alias_text_clean"] = df["alias_text"].apply(normalize_space)
    df["alias_normalized_clean"] = df["alias_text_clean"].str.lower()

    df = df[
        (df["canonical_dish_name_clean"].str.len() > 0)
        & (df["alias_text_clean"].str.len() > 0)
        & (df["alias_normalized_clean"].str.len() > 0)
    ].copy()

    df = df.drop_duplicates(
        subset=["canonical_dish_name_clean", "alias_normalized_clean"],
        keep="first",
    ).reset_index(drop=True)

    return df


# -----------------------------------------------------------------------------
# DB operations
# -----------------------------------------------------------------------------

def upsert_ai_model_version(conn: Connection, schema: str, definition: dict[str, Any]) -> str:
    sql = text(
        f"""
        INSERT INTO {qname(schema, 'ai_model_version')} (
            model_code,
            model_name,
            model_type,
            task_name,
            version_label,
            description,
            framework_name,
            base_model_name,
            language_scope,
            training_dataset_name,
            training_artifact_path,
            metrics_json,
            config_json,
            is_active
        ) VALUES (
            :model_code,
            :model_name,
            :model_type,
            :task_name,
            :version_label,
            :description,
            :framework_name,
            :base_model_name,
            :language_scope,
            :training_dataset_name,
            :training_artifact_path,
            CAST(:metrics_json AS jsonb),
            CAST(:config_json AS jsonb),
            TRUE
        )
        ON CONFLICT (model_code)
        DO UPDATE SET
            model_name = EXCLUDED.model_name,
            model_type = EXCLUDED.model_type,
            task_name = EXCLUDED.task_name,
            version_label = EXCLUDED.version_label,
            description = EXCLUDED.description,
            framework_name = EXCLUDED.framework_name,
            base_model_name = EXCLUDED.base_model_name,
            language_scope = EXCLUDED.language_scope,
            training_dataset_name = EXCLUDED.training_dataset_name,
            training_artifact_path = EXCLUDED.training_artifact_path,
            metrics_json = EXCLUDED.metrics_json,
            config_json = EXCLUDED.config_json,
            is_active = TRUE
        RETURNING ai_model_version_id::text;
        """
    )

    params = {
        **definition,
        "training_artifact_path": definition.get("training_artifact_path"),
        "metrics_json": json_dumps(definition.get("metrics_json", {})),
        "config_json": json_dumps(definition.get("config_json", {})),
    }

    return str(conn.execute(sql, params).scalar_one())


def upsert_ai_pipeline_run(
    conn: Connection,
    schema: str,
    *,
    run_code: str,
    run_type: str,
    status: str,
    input_artifacts: list[dict[str, Any]],
    output_artifacts: list[dict[str, Any]],
    config_json: dict[str, Any],
    metrics_json: dict[str, Any],
    notes: str,
) -> str:
    now = utc_now()

    sql = text(
        f"""
        INSERT INTO {qname(schema, 'ai_pipeline_run')} (
            run_code,
            run_type,
            status,
            started_at,
            finished_at,
            duration_seconds,
            input_artifacts_json,
            output_artifacts_json,
            config_json,
            metrics_json,
            notes
        ) VALUES (
            :run_code,
            :run_type,
            :status,
            :started_at,
            :finished_at,
            :duration_seconds,
            CAST(:input_artifacts_json AS jsonb),
            CAST(:output_artifacts_json AS jsonb),
            CAST(:config_json AS jsonb),
            CAST(:metrics_json AS jsonb),
            :notes
        )
        ON CONFLICT (run_code)
        DO UPDATE SET
            run_type = EXCLUDED.run_type,
            status = EXCLUDED.status,
            finished_at = EXCLUDED.finished_at,
            duration_seconds = EXCLUDED.duration_seconds,
            input_artifacts_json = EXCLUDED.input_artifacts_json,
            output_artifacts_json = EXCLUDED.output_artifacts_json,
            config_json = EXCLUDED.config_json,
            metrics_json = EXCLUDED.metrics_json,
            notes = EXCLUDED.notes
        RETURNING ai_pipeline_run_id::text;
        """
    )

    params = {
        "run_code": run_code,
        "run_type": run_type,
        "status": status,
        "started_at": now,
        "finished_at": now,
        "duration_seconds": 0,
        "input_artifacts_json": json_dumps(input_artifacts),
        "output_artifacts_json": json_dumps(output_artifacts),
        "config_json": json_dumps(config_json),
        "metrics_json": json_dumps(metrics_json),
        "notes": notes,
    }

    return str(conn.execute(sql, params).scalar_one())


def upsert_dish(
    conn: Connection,
    schema: str,
    *,
    dish_code: str,
    canonical_name: str,
    normalized_name: str,
    display_name: str,
    language_code: str,
    source_ai_run_id: str,
    source_model_version_id: str,
    review_status: str,
) -> str:
    sql = text(
        f"""
        INSERT INTO {qname(schema, 'dish')} (
            dish_code,
            canonical_name,
            normalized_name,
            display_name,
            language_code,
            source_ai_run_id,
            source_model_version_id,
            is_active,
            is_reviewed,
            review_status,
            description
        ) VALUES (
            :dish_code,
            :canonical_name,
            :normalized_name,
            :display_name,
            :language_code,
            CAST(:source_ai_run_id AS uuid),
            CAST(:source_model_version_id AS uuid),
            TRUE,
            :is_reviewed,
            :review_status,
            :description
        )
        ON CONFLICT (dish_code)
        DO UPDATE SET
            canonical_name = EXCLUDED.canonical_name,
            normalized_name = EXCLUDED.normalized_name,
            display_name = EXCLUDED.display_name,
            language_code = EXCLUDED.language_code,
            source_ai_run_id = EXCLUDED.source_ai_run_id,
            source_model_version_id = EXCLUDED.source_model_version_id,
            is_active = TRUE,
            is_reviewed = EXCLUDED.is_reviewed,
            review_status = EXCLUDED.review_status,
            description = EXCLUDED.description
        RETURNING dish_id::text;
        """
    )

    review_status = normalize_review_status(review_status)
    params = {
        "dish_code": truncate(dish_code, MAX_VARCHAR_150),
        "canonical_name": truncate(canonical_name, MAX_VARCHAR_255),
        "normalized_name": truncate(normalized_name, MAX_VARCHAR_255),
        "display_name": truncate(display_name, MAX_VARCHAR_255),
        "language_code": truncate(language_code or "en", MAX_VARCHAR_10),
        "source_ai_run_id": source_ai_run_id,
        "source_model_version_id": source_model_version_id,
        "is_reviewed": review_status in {"approved", "rejected", "needs_merge", "needs_split"},
        "review_status": review_status,
        "description": "Seed dish created from AI normalization catalog artifacts.",
    }

    return str(conn.execute(sql, params).scalar_one())


def upsert_dish_alias(
    conn: Connection,
    schema: str,
    *,
    dish_id: str,
    alias_text: str,
    alias_normalized: str,
    alias_language_code: str,
    alias_type: str,
    alias_source: str | None,
    mention_count: int | None,
    review_count: int | None,
    business_count: int | None,
    avg_confidence: float | None,
    source_ai_run_id: str,
    source_model_version_id: str,
) -> str:
    sql = text(
        f"""
        INSERT INTO {qname(schema, 'dish_alias')} (
            dish_id,
            alias_text,
            alias_normalized,
            alias_language_code,
            alias_type,
            alias_source,
            mention_count,
            review_count,
            business_count,
            avg_confidence,
            source_ai_run_id,
            source_model_version_id,
            is_active,
            is_reviewed
        ) VALUES (
            CAST(:dish_id AS uuid),
            :alias_text,
            :alias_normalized,
            :alias_language_code,
            :alias_type,
            :alias_source,
            :mention_count,
            :review_count,
            :business_count,
            :avg_confidence,
            CAST(:source_ai_run_id AS uuid),
            CAST(:source_model_version_id AS uuid),
            TRUE,
            FALSE
        )
        ON CONFLICT (dish_id, alias_normalized, alias_language_code)
        DO UPDATE SET
            alias_text = EXCLUDED.alias_text,
            alias_type = EXCLUDED.alias_type,
            alias_source = EXCLUDED.alias_source,
            mention_count = EXCLUDED.mention_count,
            review_count = EXCLUDED.review_count,
            business_count = EXCLUDED.business_count,
            avg_confidence = EXCLUDED.avg_confidence,
            source_ai_run_id = EXCLUDED.source_ai_run_id,
            source_model_version_id = EXCLUDED.source_model_version_id,
            is_active = TRUE
        RETURNING dish_alias_id::text;
        """
    )

    params = {
        "dish_id": dish_id,
        "alias_text": truncate(alias_text, MAX_VARCHAR_255),
        "alias_normalized": truncate(alias_normalized, MAX_VARCHAR_255),
        "alias_language_code": truncate(alias_language_code or "en", MAX_VARCHAR_10),
        "alias_type": truncate(normalize_alias_type(alias_type), MAX_VARCHAR_50),
        "alias_source": truncate(alias_source, MAX_VARCHAR_100),
        "mention_count": safe_int(mention_count, default=None),
        "review_count": safe_int(review_count, default=None),
        "business_count": safe_int(business_count, default=None),
        "avg_confidence": clamp_float(avg_confidence, 0.0, 1.0, default=None),
        "source_ai_run_id": source_ai_run_id,
        "source_model_version_id": source_model_version_id,
    }

    return str(conn.execute(sql, params).scalar_one())


def load_ai_dish_catalog(
    *,
    catalog_path: Path,
    aliases_path: Path,
    summary_path: Path | None,
    schema: str,
    run_code: str,
    dry_run: bool,
    limit: int | None,
) -> LoadStats:
    schema = validate_schema_name(schema)

    catalog_df = load_catalog(catalog_path, limit=limit)
    aliases_df = load_aliases(aliases_path, limit=limit)
    summary = read_json_file(summary_path)

    dish_code_map = build_unique_dish_codes(catalog_df)

    print("Catalog rows:", len(catalog_df))
    print("Alias rows:", len(aliases_df))
    print("Schema:", schema)
    print("Run code:", run_code)
    print("Dry run:", dry_run)

    if dry_run:
        print("\nDRY RUN: no database writes will be performed.")
        print("\nCatalog preview:")
        print(catalog_df.head(10).to_string(index=False))
        print("\nAliases preview:")
        print(aliases_df.head(10).to_string(index=False))
        return LoadStats(
            catalog_rows=len(catalog_df),
            alias_rows=len(aliases_df),
            dishes_upserted=0,
            aliases_upserted=0,
            aliases_skipped_missing_dish=0,
        )

    input_artifacts = [
        {"type": "csv", "role": "dish_catalog", "path": str(catalog_path)},
        {"type": "csv", "role": "dish_aliases", "path": str(aliases_path)},
    ]

    if summary_path is not None:
        input_artifacts.append({"type": "json", "role": "normalization_summary", "path": str(summary_path)})

    output_artifacts = [
        {"type": "postgres_table", "role": "dish_catalog", "table": f"{schema}.dish"},
        {"type": "postgres_table", "role": "dish_aliases", "table": f"{schema}.dish_alias"},
        {"type": "postgres_table", "role": "ai_model_version", "table": f"{schema}.ai_model_version"},
        {"type": "postgres_table", "role": "ai_pipeline_run", "table": f"{schema}.ai_pipeline_run"},
    ]

    config_json = {
        "loader": "scripts.load_ai_dish_catalog",
        "catalog_path": str(catalog_path),
        "aliases_path": str(aliases_path),
        "summary_path": str(summary_path) if summary_path else None,
        "dish_code_strategy": "slugified_canonical_dish_name",
        "upsert_strategy": {
            "dish": "ON CONFLICT (dish_code) DO UPDATE",
            "dish_alias": "ON CONFLICT (dish_id, alias_normalized, alias_language_code) DO UPDATE",
        },
    }

    metrics_json = {
        "source_summary": summary,
        "loader_input": {
            "catalog_rows": len(catalog_df),
            "alias_rows": len(aliases_df),
        },
    }

    dish_id_by_canonical_name: dict[str, str] = {}
    aliases_upserted = 0
    aliases_skipped_missing_dish = 0

    with engine.begin() as conn:
        model_ids: dict[str, str] = {}

        print("\nUpserting AI model versions...")
        for definition in MODEL_VERSION_DEFINITIONS:
            model_id = upsert_ai_model_version(conn, schema, definition)
            model_ids[definition["model_code"]] = model_id
            print(f"  {definition['model_code']} -> {model_id}")

        normalizer_model_id = model_ids["dish_normalization_rule_based_v2"]

        print("\nUpserting AI pipeline run...")
        run_id = upsert_ai_pipeline_run(
            conn,
            schema,
            run_code=run_code,
            run_type="dish_normalization",
            status="completed",
            input_artifacts=input_artifacts,
            output_artifacts=output_artifacts,
            config_json=config_json,
            metrics_json=metrics_json,
            notes="Database import of dish catalog and aliases generated by the AI normalization v2 notebook.",
        )
        print(f"  {run_code} -> {run_id}")

        print("\nUpserting dishes...")
        for row in tqdm(catalog_df.to_dict(orient="records"), total=len(catalog_df), desc="dish"):
            canonical_name = row["canonical_dish_name_clean"]
            language_code = normalize_space(row.get("language", "en")).lower() or "en"
            review_status = normalize_review_status(row.get("manual_review_status", "pending"))
            dish_code = dish_code_map[canonical_name]

            dish_id = upsert_dish(
                conn,
                schema,
                dish_code=dish_code,
                canonical_name=canonical_name,
                normalized_name=canonical_name,
                display_name=to_display_name(canonical_name),
                language_code=language_code,
                source_ai_run_id=run_id,
                source_model_version_id=normalizer_model_id,
                review_status=review_status,
            )

            dish_id_by_canonical_name[canonical_name] = dish_id

        print("\nUpserting aliases...")
        for row in tqdm(aliases_df.to_dict(orient="records"), total=len(aliases_df), desc="dish_alias"):
            canonical_name = row["canonical_dish_name_clean"]
            dish_id = dish_id_by_canonical_name.get(canonical_name)

            if dish_id is None:
                aliases_skipped_missing_dish += 1
                continue

            upsert_dish_alias(
                conn,
                schema,
                dish_id=dish_id,
                alias_text=row["alias_text_clean"],
                alias_normalized=row["alias_normalized_clean"],
                alias_language_code=normalize_space(row.get("alias_language", "en")).lower() or "en",
                alias_type=row.get("alias_type", "surface_variant"),
                alias_source=row.get("alias_source"),
                mention_count=row.get("mention_count"),
                review_count=row.get("review_count"),
                business_count=row.get("business_count"),
                avg_confidence=row.get("avg_confidence"),
                source_ai_run_id=run_id,
                source_model_version_id=normalizer_model_id,
            )
            aliases_upserted += 1

    stats = LoadStats(
        catalog_rows=len(catalog_df),
        alias_rows=len(aliases_df),
        dishes_upserted=len(dish_id_by_canonical_name),
        aliases_upserted=aliases_upserted,
        aliases_skipped_missing_dish=aliases_skipped_missing_dish,
    )

    print("\nLoad completed.")
    print(json.dumps(stats.__dict__, indent=2, ensure_ascii=False))

    return stats


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Load the AI dish catalog and aliases into PostgreSQL."
    )

    parser.add_argument(
        "--catalog-path",
        type=Path,
        required=True,
        help="Path to dish_catalog_seed_v2.csv.",
    )
    parser.add_argument(
        "--aliases-path",
        type=Path,
        required=True,
        help="Path to dish_aliases_seed_v2.csv.",
    )
    parser.add_argument(
        "--summary-path",
        type=Path,
        default=None,
        help="Optional path to dish_normalization_summary_v2.json.",
    )
    parser.add_argument(
        "--schema",
        default=settings.pgschema,
        help=f"Target PostgreSQL schema. Default: {settings.pgschema}.",
    )
    parser.add_argument(
        "--run-code",
        default="ai_run_yelp_dish_normalization_v2_catalog_import",
        help="ai_pipeline_run.run_code to create/update.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional row limit for testing.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs and show previews without writing to the database.",
    )

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        load_ai_dish_catalog(
            catalog_path=args.catalog_path,
            aliases_path=args.aliases_path,
            summary_path=args.summary_path,
            schema=args.schema,
            run_code=args.run_code,
            dry_run=args.dry_run,
            limit=args.limit,
        )
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
