"""Load Sevilla AI pilot artifacts into PostgreSQL.

This script imports the local Sevilla Hidden Gems pilot generated by notebooks 12-17.
It is designed to follow the same flow as the existing AI loaders in the repository,
but adapted to the Spanish/Sevilla prototype artifacts.

It loads, in order:

1. hidden_gems.ai_model_version
2. hidden_gems.ai_pipeline_run
3. hidden_gems.dish
4. hidden_gems.dish_alias
5. hidden_gems.dish_mention
6. hidden_gems.dish_mention_sentiment
7. hidden_gems.dish_place_signal
8. hidden_gems.hidden_gem_candidate

Important note about ranking_scope:
The current 07_ai_module.sql constraint normally allows:
  yelp_prototype, sevilla_global, sevilla_neighborhood, manual_review, other
The notebook artifact uses ranking_scope_v1='sevilla_pilot'. By default this loader stores
that value inside ranking_config_json and uses db_ranking_scope='other' to respect the DB
constraint. If you later update the DB constraint to include 'sevilla_pilot', you can adapt
--db-ranking-scope accordingly.

Recommended dry-run from repository root:

python -m scripts.load_sevilla_ai_pilot_outputs `
  --dry-run

Recommended real load:

python -m scripts.load_sevilla_ai_pilot_outputs `
  --report-path data/artifacts/ai/sevilla/load_sevilla_ai_pilot_outputs_report.json

Optional, if you only want to load selected ranking candidates instead of all scored pairs:

python -m scripts.load_sevilla_ai_pilot_outputs `
  --ranking-path data/artifacts/ai/sevilla/ranking/sevilla_hidden_gems_selected_candidates_v1.jsonl
"""

from __future__ import annotations

import argparse
import ast
import csv
import json
import math
import re
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from sqlalchemy import text
from sqlalchemy.engine import Connection

try:
    from tqdm.auto import tqdm
except Exception:  # pragma: no cover
    def tqdm(iterable: Iterable, **_: Any):
        return iterable

from src.db.database import engine


# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------

DEFAULT_SCHEMA = "hidden_gems"
DEFAULT_SOURCE_CODE = "google_places"

DEFAULT_BASE_DIR = Path("data/artifacts/ai/sevilla")
DEFAULT_CATALOG_PATH = DEFAULT_BASE_DIR / "dish_normalization/sevilla_dish_catalog_v1.csv"
DEFAULT_ALIASES_PATH = DEFAULT_BASE_DIR / "dish_normalization/sevilla_dish_aliases_v1.csv"
DEFAULT_MENTIONS_PATH = DEFAULT_BASE_DIR / "sentiment/sevilla_dish_mentions_with_sentiment_v1.jsonl"
DEFAULT_SIGNALS_PATH = DEFAULT_BASE_DIR / "aggregation/sevilla_place_dish_signals_v1.jsonl"
DEFAULT_RANKING_PATH = DEFAULT_BASE_DIR / "ranking/sevilla_hidden_gems_candidates_all_v1.jsonl"
DEFAULT_REPORT_PATH = DEFAULT_BASE_DIR / "load_sevilla_ai_pilot_outputs_report.json"

DEFAULT_DISH_DETECTION_MODEL_CODE = "sevilla_dish_detection_hybrid_v1"
DEFAULT_DISH_NORMALIZATION_MODEL_CODE = "sevilla_dish_normalization_hybrid_v1"
DEFAULT_SENTIMENT_MODEL_CODE = "sevilla_mention_sentiment_hybrid_v1"
DEFAULT_AGGREGATION_MODEL_CODE = "sevilla_signal_aggregation_v1"
DEFAULT_RANKING_MODEL_CODE = "sevilla_hidden_gems_ranking_pilot_v1"

DEFAULT_CATALOG_RUN_CODE = "ai_run_sevilla_dish_catalog_v1"
DEFAULT_MENTION_RUN_CODE = "ai_run_sevilla_dish_mentions_v1"
DEFAULT_SENTIMENT_RUN_CODE = "ai_run_sevilla_mention_sentiment_v1"
DEFAULT_AGGREGATION_RUN_CODE = "ai_run_sevilla_signal_aggregation_v1"
DEFAULT_RANKING_RUN_CODE = "ai_run_sevilla_hidden_gems_ranking_pilot_v1"

DEFAULT_SIGNAL_VERSION = "sevilla_place_dish_signal_v1"
DEFAULT_RANKING_VERSION = "sevilla_hidden_gems_ranking_pilot_v1"
DEFAULT_ARTIFACT_RANKING_SCOPE = "sevilla_pilot"
DEFAULT_DB_RANKING_SCOPE = "other"

SCHEMA_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")
VALID_DB_RANKING_SCOPES = {
    "yelp_prototype",
    "sevilla_global",
    "sevilla_neighborhood",
    "manual_review",
    "other",
}
VALID_HIDDEN_GEM_TIERS = {
    "top_hidden_gem",
    "strong_hidden_gem",
    "promising_hidden_gem",
    "exploratory_hidden_gem",
    "not_selected",
}
VALID_EVIDENCE_TIERS = {"strong", "solid", "emerging", "weak"}
VALID_QUALITY_TIERS = {"high", "medium", "low"}
VALID_SENTIMENT_LABELS = {"positive", "neutral", "negative"}
VALID_RELIABILITY_TIERS = {"high", "medium", "low"}
VALID_HUMAN_REVIEW_STATUS = {"not_reviewed", "pending", "approved", "rejected", "corrected"}


# -----------------------------------------------------------------------------
# Stats
# -----------------------------------------------------------------------------

@dataclass
class InputStats:
    catalog_rows: int = 0
    aliases_rows: int = 0
    mention_rows: int = 0
    signal_rows: int = 0
    ranking_rows: int = 0


@dataclass
class LoadStats:
    model_versions_upserted: int = 0
    ai_runs_upserted: int = 0
    dishes_upserted: int = 0
    aliases_upserted: int = 0
    mentions_upserted: int = 0
    sentiments_upserted: int = 0
    signals_upserted: int = 0
    ranking_candidates_upserted: int = 0
    dry_run: bool = False


@dataclass
class SkipStats:
    catalog_missing_required: int = 0
    alias_missing_required: int = 0
    alias_missing_dish_mapping: int = 0
    mention_missing_required: int = 0
    mention_missing_review_mapping: int = 0
    mention_missing_place_mapping: int = 0
    mention_missing_dish_mapping: int = 0
    mention_invalid_sentiment: int = 0
    signal_missing_required: int = 0
    signal_missing_place_mapping: int = 0
    signal_missing_dish_mapping: int = 0
    ranking_missing_required: int = 0
    ranking_missing_place_mapping: int = 0
    ranking_missing_dish_mapping: int = 0
    ranking_missing_signal_mapping: int = 0


# -----------------------------------------------------------------------------
# Generic helpers
# -----------------------------------------------------------------------------

def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def validate_schema_name(schema: str) -> str:
    schema = str(schema).strip()
    if not SCHEMA_RE.match(schema):
        raise ValueError(f"Invalid PostgreSQL schema name: {schema!r}")
    return schema


def qname(schema: str, table: str) -> str:
    return f'"{validate_schema_name(schema)}"."{table}"'


def normalize_space(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and math.isnan(value):
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def normalize_lower(value: Any) -> str:
    return normalize_space(value).lower()


def truncate(value: Any, max_len: int) -> str | None:
    value = normalize_space(value)
    if not value:
        return None
    return value[:max_len]


def safe_int(value: Any) -> int | None:
    if value is None or value == "":
        return None
    try:
        if isinstance(value, float) and math.isnan(value):
            return None
        return int(float(value))
    except Exception:
        return None


def safe_float(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        if isinstance(value, float) and math.isnan(value):
            return None
        result = float(value)
        if math.isnan(result) or math.isinf(result):
            return None
        return result
    except Exception:
        return None


def safe_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    value_str = str(value).strip().lower()
    if value_str in {"true", "1", "yes", "y", "si", "sí"}:
        return True
    if value_str in {"false", "0", "no", "n"}:
        return False
    return default


def clamp_float(value: Any, min_value: float, max_value: float) -> float | None:
    value_float = safe_float(value)
    if value_float is None:
        return None
    return max(min_value, min(max_value, value_float))


def ratio(value: Any) -> float | None:
    return clamp_float(value, 0.0, 1.0)


def score_0_100(value: Any) -> float | None:
    return clamp_float(value, 0.0, 100.0)


def component(value: Any) -> float | None:
    return clamp_float(value, 0.0, 1.0)


def json_dumps(value: Any) -> str:
    return json.dumps(to_builtin(value), ensure_ascii=False)


def to_builtin(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, dict):
        return {str(k): to_builtin(v) for k, v in value.items()}
    if isinstance(value, list):
        return [to_builtin(v) for v in value]
    if isinstance(value, tuple):
        return [to_builtin(v) for v in value]
    if hasattr(value, "item"):
        try:
            return to_builtin(value.item())
        except Exception:
            pass
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
    return value


def parse_list_like(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, float) and math.isnan(value):
        return []
    if isinstance(value, str):
        value = value.strip()
        if not value:
            return []
        try:
            parsed = json.loads(value)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
        try:
            parsed = ast.literal_eval(value)
            if isinstance(parsed, list):
                return parsed
            if isinstance(parsed, tuple):
                return list(parsed)
        except Exception:
            pass
        return [value]
    return [value]


def safe_json_object(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return to_builtin(value)
    if isinstance(value, str) and value.strip():
        try:
            parsed = json.loads(value)
            if isinstance(parsed, dict):
                return to_builtin(parsed)
        except Exception:
            return {"raw": value}
    return {}


def save_report(path: Path, report: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(to_builtin(report), f, indent=2, ensure_ascii=False, allow_nan=False)
    print(f"Report saved to: {path}")


# -----------------------------------------------------------------------------
# File readers
# -----------------------------------------------------------------------------

def read_csv_rows(path: Path, max_rows: int | None = None) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for idx, row in enumerate(reader, start=1):
            if max_rows is not None and idx > max_rows:
                break
            rows.append(dict(row))
    return rows


def read_jsonl_rows(path: Path, max_rows: int | None = None) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for idx, line in enumerate(f, start=1):
            if max_rows is not None and idx > max_rows:
                break
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def read_artifact_rows(path: Path, max_rows: int | None = None) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Artifact not found: {path}")
    if path.suffix.lower() == ".jsonl":
        return read_jsonl_rows(path, max_rows=max_rows)
    if path.suffix.lower() == ".csv":
        return read_csv_rows(path, max_rows=max_rows)
    raise ValueError(f"Unsupported artifact format: {path}")


# -----------------------------------------------------------------------------
# Database helpers
# -----------------------------------------------------------------------------

def get_source_system_id(conn: Connection, schema: str, source_code: str) -> str:
    row = conn.execute(
        text(
            f"""
            SELECT source_system_id
            FROM {qname(schema, 'source_system')}
            WHERE source_code = :source_code
            """
        ),
        {"source_code": source_code},
    ).mappings().first()
    if row is None:
        raise RuntimeError(f"source_system not found for source_code={source_code!r}")
    return str(row["source_system_id"])


def upsert_model_version(
    conn: Connection,
    schema: str,
    *,
    model_code: str,
    model_name: str,
    model_type: str,
    task_name: str,
    version_label: str,
    description: str,
    language_scope: str = "es",
    config: dict[str, Any] | None = None,
    metrics: dict[str, Any] | None = None,
) -> str:
    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'ai_model_version')} (
                model_code,
                model_name,
                model_type,
                task_name,
                version_label,
                description,
                framework_name,
                base_model_name,
                language_scope,
                training_dataset_name,
                training_artifact_path,
                metrics_json,
                config_json,
                is_active
            ) VALUES (
                :model_code,
                :model_name,
                :model_type,
                :task_name,
                :version_label,
                :description,
                :framework_name,
                :base_model_name,
                :language_scope,
                :training_dataset_name,
                :training_artifact_path,
                CAST(:metrics_json AS jsonb),
                CAST(:config_json AS jsonb),
                TRUE
            )
            ON CONFLICT (model_code) DO UPDATE SET
                model_name = EXCLUDED.model_name,
                model_type = EXCLUDED.model_type,
                task_name = EXCLUDED.task_name,
                version_label = EXCLUDED.version_label,
                description = EXCLUDED.description,
                language_scope = EXCLUDED.language_scope,
                metrics_json = EXCLUDED.metrics_json,
                config_json = EXCLUDED.config_json,
                is_active = TRUE
            RETURNING ai_model_version_id
            """
        ),
        {
            "model_code": model_code,
            "model_name": model_name,
            "model_type": model_type,
            "task_name": task_name,
            "version_label": version_label,
            "description": description,
            "framework_name": "python",
            "base_model_name": None,
            "language_scope": language_scope,
            "training_dataset_name": "google_places_sevilla_reviews_pilot",
            "training_artifact_path": None,
            "metrics_json": json_dumps(metrics or {}),
            "config_json": json_dumps(config or {}),
        },
    ).mappings().one()
    return str(row["ai_model_version_id"])


def upsert_ai_run(
    conn: Connection,
    schema: str,
    *,
    run_code: str,
    run_type: str,
    input_artifacts: list[dict[str, Any]],
    output_artifacts: list[dict[str, Any]],
    config: dict[str, Any],
    metrics: dict[str, Any] | None = None,
    notes: str | None = None,
) -> str:
    now = utc_now()
    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'ai_pipeline_run')} (
                run_code,
                run_type,
                status,
                started_at,
                finished_at,
                duration_seconds,
                input_artifacts_json,
                output_artifacts_json,
                config_json,
                metrics_json,
                notes
            ) VALUES (
                :run_code,
                :run_type,
                'completed',
                :started_at,
                :finished_at,
                0,
                CAST(:input_artifacts_json AS jsonb),
                CAST(:output_artifacts_json AS jsonb),
                CAST(:config_json AS jsonb),
                CAST(:metrics_json AS jsonb),
                :notes
            )
            ON CONFLICT (run_code) DO UPDATE SET
                run_type = EXCLUDED.run_type,
                status = EXCLUDED.status,
                finished_at = EXCLUDED.finished_at,
                duration_seconds = EXCLUDED.duration_seconds,
                input_artifacts_json = EXCLUDED.input_artifacts_json,
                output_artifacts_json = EXCLUDED.output_artifacts_json,
                config_json = EXCLUDED.config_json,
                metrics_json = EXCLUDED.metrics_json,
                notes = EXCLUDED.notes
            RETURNING ai_pipeline_run_id
            """
        ),
        {
            "run_code": run_code,
            "run_type": run_type,
            "started_at": now,
            "finished_at": now,
            "input_artifacts_json": json_dumps(input_artifacts),
            "output_artifacts_json": json_dumps(output_artifacts),
            "config_json": json_dumps(config),
            "metrics_json": json_dumps(metrics or {}),
            "notes": notes,
        },
    ).mappings().one()
    return str(row["ai_pipeline_run_id"])


def load_existing_ids(conn: Connection, schema: str, table: str, id_column: str) -> set[str]:
    rows = conn.execute(text(f"SELECT {id_column} FROM {qname(schema, table)}")).mappings().all()
    return {str(row[id_column]) for row in rows}


def load_review_place_pairs(conn: Connection, schema: str) -> set[tuple[str, str]]:
    rows = conn.execute(
        text(
            f"""
            SELECT review_id, place_id
            FROM {qname(schema, 'review')}
            WHERE is_active = TRUE
              AND is_deleted_in_source = FALSE
            """
        )
    ).mappings().all()
    return {(str(row["review_id"]), str(row["place_id"])) for row in rows}


# -----------------------------------------------------------------------------
# Mapping and preparation
# -----------------------------------------------------------------------------

def alias_type_for_db(value: Any) -> str:
    value = normalize_lower(value)
    if value in {"canonical", "surface_variant", "translation", "manual_alias", "synonym", "misspelling"}:
        return value
    if value in {"manual_remap", "manual", "remap"}:
        return "manual_alias"
    if value in {"exact_alias", "surface", "variant"}:
        return "surface_variant"
    return "surface_variant"


def review_status_from_row(row: dict[str, Any]) -> str:
    if safe_bool(row.get("needs_manual_review_v1"), default=False):
        return "pending"
    status = normalize_lower(row.get("eligibility_status_v1"))
    if status == "eligible":
        return "pending"
    if status == "excluded":
        return "rejected"
    return "pending"


def quality_tier_for_db(value: Any) -> str | None:
    value = normalize_lower(value)
    if value in {"high", "medium", "low"}:
        return value
    if value in {"high_quality_signal", "strong_signal"}:
        return "high"
    if value in {"usable_signal", "emerging_signal", "solid_signal"}:
        return "medium"
    if value in {"weak_signal", "single_mention_signal", "noisy_signal"}:
        return "low"
    return None


def evidence_tier_for_db(value: Any) -> str | None:
    value = normalize_lower(value)
    return value if value in VALID_EVIDENCE_TIERS else None


def reliability_from_confidence(value: Any) -> str:
    conf = safe_float(value) or 0.0
    if conf >= 0.75:
        return "high"
    if conf >= 0.50:
        return "medium"
    return "low"


def sentiment_label_for_db(value: Any) -> str | None:
    value = normalize_lower(value)
    return value if value in VALID_SENTIMENT_LABELS else None


def hidden_gem_tier_for_db(value: Any) -> str:
    value = normalize_lower(value)
    return value if value in VALID_HIDDEN_GEM_TIERS else "not_selected"


def ranking_scope_for_db(value: str) -> str:
    value = normalize_lower(value)
    if value not in VALID_DB_RANKING_SCOPES:
        raise ValueError(
            f"Invalid DB ranking scope {value!r}. Current DB constraint normally allows: "
            f"{sorted(VALID_DB_RANKING_SCOPES)}. Use --db-ranking-scope other for sevilla_pilot."
        )
    return value


# -----------------------------------------------------------------------------
# Upserts
# -----------------------------------------------------------------------------

def upsert_dish(
    conn: Connection,
    schema: str,
    row: dict[str, Any],
    *,
    source_ai_run_id: str,
    source_model_version_id: str,
) -> str:
    dish_code = normalize_lower(row.get("dish_id_v1"))
    canonical = normalize_space(row.get("canonical_dish_name_es_v1")) or normalize_space(row.get("normalized_dish_name_es_v1"))
    normalized = normalize_lower(row.get("canonical_dish_name_es_v1")) or normalize_lower(row.get("normalized_dish_name_es_v1"))
    display = normalize_space(row.get("display_dish_name_es_v1")) or canonical
    family = truncate(row.get("dish_family_es_v1"), 100)
    review_status = review_status_from_row(row)

    db_row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish')} (
                dish_code,
                canonical_name,
                normalized_name,
                display_name,
                language_code,
                dish_family,
                description,
                source_ai_run_id,
                source_model_version_id,
                is_active,
                is_reviewed,
                review_status
            ) VALUES (
                :dish_code,
                :canonical_name,
                :normalized_name,
                :display_name,
                'es',
                :dish_family,
                :description,
                :source_ai_run_id,
                :source_model_version_id,
                TRUE,
                FALSE,
                :review_status
            )
            ON CONFLICT (dish_code) DO UPDATE SET
                canonical_name = EXCLUDED.canonical_name,
                normalized_name = EXCLUDED.normalized_name,
                display_name = EXCLUDED.display_name,
                language_code = EXCLUDED.language_code,
                dish_family = EXCLUDED.dish_family,
                description = EXCLUDED.description,
                source_ai_run_id = EXCLUDED.source_ai_run_id,
                source_model_version_id = EXCLUDED.source_model_version_id,
                is_active = TRUE,
                review_status = EXCLUDED.review_status
            RETURNING dish_id
            """
        ),
        {
            "dish_code": dish_code,
            "canonical_name": canonical,
            "normalized_name": normalized,
            "display_name": display,
            "dish_family": family,
            "description": json_dumps(
                {
                    "dish_group_es_v1": row.get("dish_group_es_v1"),
                    "dish_specificity_v1": row.get("dish_specificity_v1"),
                    "ranking_eligible_v1": safe_bool(row.get("ranking_eligible_v1")),
                    "eligibility_status_v1": row.get("eligibility_status_v1"),
                    "eligibility_reason_v1": row.get("eligibility_reason_v1"),
                    "catalog_quality_tier_v1": row.get("catalog_quality_tier_v1"),
                    "normalization_version": row.get("normalization_version"),
                }
            ),
            "source_ai_run_id": source_ai_run_id,
            "source_model_version_id": source_model_version_id,
            "review_status": review_status,
        },
    ).mappings().one()
    return str(db_row["dish_id"])


def upsert_alias(
    conn: Connection,
    schema: str,
    row: dict[str, Any],
    *,
    dish_id: str,
    source_ai_run_id: str,
    source_model_version_id: str,
) -> str:
    alias_text = normalize_space(row.get("alias_text"))
    alias_normalized = normalize_lower(row.get("alias_normalized")) or normalize_lower(alias_text)
    alias_type = alias_type_for_db(row.get("alias_type_v1"))

    db_row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish_alias')} (
                dish_id,
                alias_text,
                alias_normalized,
                alias_language_code,
                alias_type,
                alias_source,
                mention_count,
                review_count,
                business_count,
                avg_confidence,
                source_ai_run_id,
                source_model_version_id,
                is_active,
                is_reviewed
            ) VALUES (
                :dish_id,
                :alias_text,
                :alias_normalized,
                'es',
                :alias_type,
                :alias_source,
                :mention_count,
                :review_count,
                :business_count,
                :avg_confidence,
                :source_ai_run_id,
                :source_model_version_id,
                TRUE,
                FALSE
            )
            ON CONFLICT (dish_id, alias_normalized, alias_language_code) DO UPDATE SET
                alias_text = EXCLUDED.alias_text,
                alias_type = EXCLUDED.alias_type,
                alias_source = EXCLUDED.alias_source,
                mention_count = EXCLUDED.mention_count,
                review_count = EXCLUDED.review_count,
                business_count = EXCLUDED.business_count,
                avg_confidence = EXCLUDED.avg_confidence,
                source_ai_run_id = EXCLUDED.source_ai_run_id,
                source_model_version_id = EXCLUDED.source_model_version_id,
                is_active = TRUE
            RETURNING dish_alias_id
            """
        ),
        {
            "dish_id": dish_id,
            "alias_text": alias_text,
            "alias_normalized": alias_normalized,
            "alias_type": alias_type,
            "alias_source": truncate(row.get("normalization_version"), 100) or "sevilla_dish_normalization_v1",
            "mention_count": safe_int(row.get("mention_count")),
            "review_count": safe_int(row.get("review_count")),
            "business_count": safe_int(row.get("place_count")),
            "avg_confidence": clamp_float(row.get("avg_confidence"), 0.0, 1.0),
            "source_ai_run_id": source_ai_run_id,
            "source_model_version_id": source_model_version_id,
        },
    ).mappings().one()
    return str(db_row["dish_alias_id"])


def upsert_mention(
    conn: Connection,
    schema: str,
    row: dict[str, Any],
    *,
    dish_id: str,
    dish_alias_id: str | None,
    ai_pipeline_run_id: str,
    model_version_id: str,
) -> str:
    mention_text = normalize_space(row.get("dish_mention_text"))
    mention_normalized = truncate(row.get("dish_mention_normalized"), 255)
    confidence = clamp_float(row.get("confidence"), 0.0, 1.0)
    human_review_status = "pending" if safe_bool(row.get("needs_manual_review_v1"), default=False) else "not_reviewed"

    db_row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish_mention')} (
                review_id,
                place_id,
                dish_id,
                dish_alias_id,
                ai_pipeline_run_id,
                model_version_id,
                mention_text,
                mention_normalized,
                start_char,
                end_char,
                start_token,
                end_token,
                token_count,
                ner_confidence_mean,
                ner_confidence_min,
                ner_confidence_max,
                normalization_status,
                normalization_method,
                normalization_confidence,
                human_review_status,
                is_active
            ) VALUES (
                :review_id,
                :place_id,
                :dish_id,
                :dish_alias_id,
                :ai_pipeline_run_id,
                :model_version_id,
                :mention_text,
                :mention_normalized,
                :start_char,
                :end_char,
                NULL,
                NULL,
                NULL,
                :ner_confidence_mean,
                NULL,
                NULL,
                :normalization_status,
                :normalization_method,
                :normalization_confidence,
                :human_review_status,
                TRUE
            )
            ON CONFLICT (review_id, start_char, end_char, mention_normalized, ai_pipeline_run_id) DO UPDATE SET
                place_id = EXCLUDED.place_id,
                dish_id = EXCLUDED.dish_id,
                dish_alias_id = EXCLUDED.dish_alias_id,
                model_version_id = EXCLUDED.model_version_id,
                mention_text = EXCLUDED.mention_text,
                ner_confidence_mean = EXCLUDED.ner_confidence_mean,
                normalization_status = EXCLUDED.normalization_status,
                normalization_method = EXCLUDED.normalization_method,
                normalization_confidence = EXCLUDED.normalization_confidence,
                human_review_status = EXCLUDED.human_review_status,
                is_active = TRUE
            RETURNING dish_mention_id
            """
        ),
        {
            "review_id": normalize_space(row.get("review_id")),
            "place_id": normalize_space(row.get("place_id")),
            "dish_id": dish_id,
            "dish_alias_id": dish_alias_id,
            "ai_pipeline_run_id": ai_pipeline_run_id,
            "model_version_id": model_version_id,
            "mention_text": mention_text,
            "mention_normalized": mention_normalized,
            "start_char": safe_int(row.get("start_char")),
            "end_char": safe_int(row.get("end_char")),
            "ner_confidence_mean": confidence,
            "normalization_status": "normalized_rule_based_v2",
            "normalization_method": truncate(row.get("normalization_method_v1"), 100) or "sevilla_rule_based_v1",
            "normalization_confidence": confidence,
            "human_review_status": human_review_status,
        },
    ).mappings().one()
    return str(db_row["dish_mention_id"])


def upsert_sentiment(
    conn: Connection,
    schema: str,
    row: dict[str, Any],
    *,
    dish_mention_id: str,
    ai_pipeline_run_id: str,
    model_version_id: str,
) -> str:
    confidence = clamp_float(row.get("mention_sentiment_confidence_v1"), 0.0, 1.0)
    sentiment_method = "sevilla_hybrid_context_lexicon_v1"

    db_row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish_mention_sentiment')} (
                dish_mention_id,
                ai_pipeline_run_id,
                model_version_id,
                sentiment_label,
                sentiment_score,
                sentiment_confidence,
                sentiment_reliability_tier,
                sentiment_reason,
                sentiment_method,
                context_sentence,
                context_window,
                target_clause_context,
                near_mention_context,
                positive_terms,
                negative_terms,
                flags,
                is_training_candidate,
                human_review_status
            ) VALUES (
                :dish_mention_id,
                :ai_pipeline_run_id,
                :model_version_id,
                :sentiment_label,
                :sentiment_score,
                :sentiment_confidence,
                :sentiment_reliability_tier,
                :sentiment_reason,
                :sentiment_method,
                :context_sentence,
                :context_window,
                :target_clause_context,
                :near_mention_context,
                CAST(:positive_terms AS jsonb),
                CAST(:negative_terms AS jsonb),
                CAST(:flags AS jsonb),
                FALSE,
                :human_review_status
            )
            ON CONFLICT (dish_mention_id, ai_pipeline_run_id, sentiment_method) DO UPDATE SET
                model_version_id = EXCLUDED.model_version_id,
                sentiment_label = EXCLUDED.sentiment_label,
                sentiment_score = EXCLUDED.sentiment_score,
                sentiment_confidence = EXCLUDED.sentiment_confidence,
                sentiment_reliability_tier = EXCLUDED.sentiment_reliability_tier,
                sentiment_reason = EXCLUDED.sentiment_reason,
                context_sentence = EXCLUDED.context_sentence,
                context_window = EXCLUDED.context_window,
                target_clause_context = EXCLUDED.target_clause_context,
                near_mention_context = EXCLUDED.near_mention_context,
                positive_terms = EXCLUDED.positive_terms,
                negative_terms = EXCLUDED.negative_terms,
                flags = EXCLUDED.flags,
                human_review_status = EXCLUDED.human_review_status
            RETURNING dish_mention_sentiment_id
            """
        ),
        {
            "dish_mention_id": dish_mention_id,
            "ai_pipeline_run_id": ai_pipeline_run_id,
            "model_version_id": model_version_id,
            "sentiment_label": sentiment_label_for_db(row.get("mention_sentiment_label_v1")),
            "sentiment_score": clamp_float(row.get("mention_sentiment_score_v1"), -5.0, 5.0),
            "sentiment_confidence": confidence,
            "sentiment_reliability_tier": reliability_from_confidence(confidence),
            "sentiment_reason": truncate(row.get("sentiment_reason_v1"), 100),
            "sentiment_method": sentiment_method,
            "context_sentence": normalize_space(row.get("context_sentence")) or None,
            "context_window": normalize_space(row.get("window_context")) or None,
            "target_clause_context": normalize_space(row.get("context_used_v1")) or None,
            "near_mention_context": normalize_space(row.get("context_source_v1")) or None,
            "positive_terms": json_dumps(parse_list_like(row.get("positive_terms_v1"))),
            "negative_terms": json_dumps(parse_list_like(row.get("negative_terms_v1"))),
            "flags": json_dumps(parse_list_like(row.get("sentiment_flags_v1"))),
            "human_review_status": "pending" if confidence is not None and confidence < 0.45 else "not_reviewed",
        },
    ).mappings().one()
    return str(db_row["dish_mention_sentiment_id"])


def reliability_counts_from_signal(row: dict[str, Any]) -> tuple[int, int, int, float | None]:
    mention_count = safe_int(row.get("mention_count")) or 0
    confidence = safe_float(row.get("avg_sentiment_confidence")) or 0.0
    if mention_count <= 0:
        return 0, 0, 0, None
    if confidence >= 0.75:
        return mention_count, 0, 0, 1.0
    if confidence >= 0.50:
        return 0, mention_count, 0, 0.0
    return 0, 0, mention_count, 0.0


def upsert_signal(
    conn: Connection,
    schema: str,
    row: dict[str, Any],
    *,
    dish_id: str,
    ai_pipeline_run_id: str,
    signal_version: str,
) -> str:
    mention_count = safe_int(row.get("mention_count")) or 0
    high_rel, medium_rel, low_rel, high_ratio = reliability_counts_from_signal(row)
    flags = parse_list_like(row.get("top_sentiment_flags_v1"))
    if safe_int(row.get("low_confidence_flag_count")):
        flags.append("low_confidence_aggregate")
    if safe_int(row.get("service_flag_count")):
        flags.append("service_context_aggregate")
    if safe_int(row.get("price_flag_count")):
        flags.append("price_context_aggregate")

    bayesian_score = None
    pos_smooth = safe_float(row.get("smoothed_positive_ratio"))
    neg_smooth = safe_float(row.get("smoothed_negative_ratio"))
    if pos_smooth is not None and neg_smooth is not None:
        bayesian_score = clamp_float(pos_smooth - neg_smooth, -1.0, 1.0)

    db_row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish_place_signal')} (
                place_id,
                dish_id,
                ai_pipeline_run_id,
                signal_version,
                mention_count,
                review_count,
                positive_mentions,
                neutral_mentions,
                negative_mentions,
                positive_ratio,
                negative_ratio,
                avg_ner_confidence,
                avg_sentiment_confidence,
                avg_signal_weight,
                total_signal_weight,
                avg_rating,
                avg_sentiment_score_raw,
                confidence_weighted_sentiment,
                bayesian_sentiment_score,
                reliability_high_ratio,
                high_reliability_mentions,
                medium_reliability_mentions,
                low_reliability_mentions,
                aggregate_quality_tier,
                evidence_tier,
                is_rankable_candidate,
                quality_flags
            ) VALUES (
                :place_id,
                :dish_id,
                :ai_pipeline_run_id,
                :signal_version,
                :mention_count,
                :review_count,
                :positive_mentions,
                :neutral_mentions,
                :negative_mentions,
                :positive_ratio,
                :negative_ratio,
                NULL,
                :avg_sentiment_confidence,
                :avg_signal_weight,
                :total_signal_weight,
                :avg_rating,
                :avg_sentiment_score_raw,
                :confidence_weighted_sentiment,
                :bayesian_sentiment_score,
                :reliability_high_ratio,
                :high_reliability_mentions,
                :medium_reliability_mentions,
                :low_reliability_mentions,
                :aggregate_quality_tier,
                :evidence_tier,
                :is_rankable_candidate,
                CAST(:quality_flags AS jsonb)
            )
            ON CONFLICT (place_id, dish_id, ai_pipeline_run_id, signal_version) DO UPDATE SET
                mention_count = EXCLUDED.mention_count,
                review_count = EXCLUDED.review_count,
                positive_mentions = EXCLUDED.positive_mentions,
                neutral_mentions = EXCLUDED.neutral_mentions,
                negative_mentions = EXCLUDED.negative_mentions,
                positive_ratio = EXCLUDED.positive_ratio,
                negative_ratio = EXCLUDED.negative_ratio,
                avg_sentiment_confidence = EXCLUDED.avg_sentiment_confidence,
                avg_signal_weight = EXCLUDED.avg_signal_weight,
                total_signal_weight = EXCLUDED.total_signal_weight,
                avg_rating = EXCLUDED.avg_rating,
                avg_sentiment_score_raw = EXCLUDED.avg_sentiment_score_raw,
                confidence_weighted_sentiment = EXCLUDED.confidence_weighted_sentiment,
                bayesian_sentiment_score = EXCLUDED.bayesian_sentiment_score,
                reliability_high_ratio = EXCLUDED.reliability_high_ratio,
                high_reliability_mentions = EXCLUDED.high_reliability_mentions,
                medium_reliability_mentions = EXCLUDED.medium_reliability_mentions,
                low_reliability_mentions = EXCLUDED.low_reliability_mentions,
                aggregate_quality_tier = EXCLUDED.aggregate_quality_tier,
                evidence_tier = EXCLUDED.evidence_tier,
                is_rankable_candidate = EXCLUDED.is_rankable_candidate,
                quality_flags = EXCLUDED.quality_flags
            RETURNING dish_place_signal_id
            """
        ),
        {
            "place_id": normalize_space(row.get("place_id")),
            "dish_id": dish_id,
            "ai_pipeline_run_id": ai_pipeline_run_id,
            "signal_version": signal_version,
            "mention_count": mention_count,
            "review_count": safe_int(row.get("review_count")) or 0,
            "positive_mentions": safe_int(row.get("positive_count")) or 0,
            "neutral_mentions": safe_int(row.get("neutral_count")) or 0,
            "negative_mentions": safe_int(row.get("negative_count")) or 0,
            "positive_ratio": ratio(row.get("positive_ratio")),
            "negative_ratio": ratio(row.get("negative_ratio")),
            "avg_sentiment_confidence": clamp_float(row.get("avg_sentiment_confidence"), 0.0, 1.0),
            "avg_signal_weight": clamp_float(row.get("avg_aggregation_weight"), 0.0, 999999.0),
            "total_signal_weight": clamp_float(row.get("total_signal_weight"), 0.0, 999999999.0),
            "avg_rating": clamp_float(row.get("avg_rating"), 0.0, 5.0),
            "avg_sentiment_score_raw": clamp_float(row.get("weighted_sentiment_score"), -999.0, 999.0),
            "confidence_weighted_sentiment": clamp_float(row.get("weighted_sentiment_value"), -1.0, 1.0),
            "bayesian_sentiment_score": bayesian_score,
            "reliability_high_ratio": high_ratio,
            "high_reliability_mentions": high_rel,
            "medium_reliability_mentions": medium_rel,
            "low_reliability_mentions": low_rel,
            "aggregate_quality_tier": quality_tier_for_db(row.get("signal_quality_tier_v1")),
            "evidence_tier": evidence_tier_for_db(row.get("evidence_tier_v1")),
            "is_rankable_candidate": safe_bool(row.get("ranking_ready_v1"), default=False),
            "quality_flags": json_dumps(flags),
        },
    ).mappings().one()
    return str(db_row["dish_place_signal_id"])


def upsert_hidden_gem_candidate(
    conn: Connection,
    schema: str,
    row: dict[str, Any],
    *,
    dish_id: str,
    dish_place_signal_id: str | None,
    ai_pipeline_run_id: str,
    ranking_version: str,
    db_ranking_scope: str,
    artifact_ranking_scope: str,
) -> str:
    selected = safe_bool(row.get("selected_hidden_gem_v1"), default=False)
    tier = hidden_gem_tier_for_db(row.get("hidden_gem_tier_v1"))
    if selected and tier == "not_selected":
        tier = "exploratory_hidden_gem"
    if not selected:
        tier = "not_selected"

    selected_rank = safe_int(row.get("hidden_gem_global_rank_v1")) if selected else None
    base_raw = safe_float(row.get("hidden_gem_score_raw_v1"))
    if base_raw is not None and base_raw <= 1.0:
        base_score = base_raw * 100.0
    else:
        base_score = base_raw

    flags = parse_list_like(row.get("top_sentiment_flags_v1"))
    if not safe_bool(row.get("is_production_ready_v1"), default=False):
        flags.append("not_production_ready")
    if normalize_lower(row.get("ranking_scope_v1")) == "sevilla_pilot":
        flags.append("sevilla_pilot_scope")

    ranking_config = {
        "artifact_ranking_scope": normalize_space(row.get("ranking_scope_v1")) or artifact_ranking_scope,
        "db_ranking_scope": db_ranking_scope,
        "ranking_version_v1": normalize_space(row.get("ranking_version_v1")) or ranking_version,
        "candidate_pair_id_v1": row.get("candidate_pair_id_v1"),
        "rank_in_district_v1": safe_int(row.get("rank_in_district_v1")),
        "rank_in_neighborhood_v1": safe_int(row.get("rank_in_neighborhood_v1")),
        "rank_for_dish_v1": safe_int(row.get("rank_for_dish_v1")),
        "evidence_tier_v1": row.get("evidence_tier_v1"),
        "signal_quality_tier_v1": row.get("signal_quality_tier_v1"),
        "global_dish_signal_score_v1": safe_float(row.get("global_dish_signal_score_v1")),
        "global_popularity_score_v1": safe_float(row.get("global_popularity_score_v1")),
        "neighborhood_dish_place_count_v1": safe_int(row.get("neighborhood_dish_place_count_v1")),
        "is_production_ready_v1": safe_bool(row.get("is_production_ready_v1"), default=False),
    }

    db_row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'hidden_gem_candidate')} (
                place_id,
                dish_id,
                dish_place_signal_id,
                neighborhood_id,
                district_id,
                ai_pipeline_run_id,
                ranking_version,
                ranking_scope,
                hidden_gem_score,
                hidden_gem_score_base,
                hidden_gem_rank,
                hidden_gem_selected_rank,
                hidden_gem_tier,
                is_selected,
                local_sentiment_component,
                evidence_component,
                confidence_component,
                positive_balance_component,
                rarity_component,
                local_outperformance_component,
                hiddenness_component,
                preliminary_component,
                negative_penalty_factor,
                beverage_penalty_factor,
                noise_penalty_factor,
                low_evidence_penalty_factor,
                ranking_explanation,
                ranking_config_json,
                quality_flags,
                is_production_ready,
                human_review_status
            ) VALUES (
                :place_id,
                :dish_id,
                :dish_place_signal_id,
                :neighborhood_id,
                :district_id,
                :ai_pipeline_run_id,
                :ranking_version,
                :ranking_scope,
                :hidden_gem_score,
                :hidden_gem_score_base,
                :hidden_gem_rank,
                :hidden_gem_selected_rank,
                :hidden_gem_tier,
                :is_selected,
                :local_sentiment_component,
                :evidence_component,
                :confidence_component,
                :positive_balance_component,
                :rarity_component,
                :local_outperformance_component,
                :hiddenness_component,
                :preliminary_component,
                :negative_penalty_factor,
                :beverage_penalty_factor,
                :noise_penalty_factor,
                :low_evidence_penalty_factor,
                :ranking_explanation,
                CAST(:ranking_config_json AS jsonb),
                CAST(:quality_flags AS jsonb),
                :is_production_ready,
                :human_review_status
            )
            ON CONFLICT (place_id, dish_id, ai_pipeline_run_id, ranking_version, ranking_scope) DO UPDATE SET
                dish_place_signal_id = EXCLUDED.dish_place_signal_id,
                neighborhood_id = EXCLUDED.neighborhood_id,
                district_id = EXCLUDED.district_id,
                hidden_gem_score = EXCLUDED.hidden_gem_score,
                hidden_gem_score_base = EXCLUDED.hidden_gem_score_base,
                hidden_gem_rank = EXCLUDED.hidden_gem_rank,
                hidden_gem_selected_rank = EXCLUDED.hidden_gem_selected_rank,
                hidden_gem_tier = EXCLUDED.hidden_gem_tier,
                is_selected = EXCLUDED.is_selected,
                local_sentiment_component = EXCLUDED.local_sentiment_component,
                evidence_component = EXCLUDED.evidence_component,
                confidence_component = EXCLUDED.confidence_component,
                positive_balance_component = EXCLUDED.positive_balance_component,
                rarity_component = EXCLUDED.rarity_component,
                local_outperformance_component = EXCLUDED.local_outperformance_component,
                hiddenness_component = EXCLUDED.hiddenness_component,
                preliminary_component = EXCLUDED.preliminary_component,
                negative_penalty_factor = EXCLUDED.negative_penalty_factor,
                beverage_penalty_factor = EXCLUDED.beverage_penalty_factor,
                noise_penalty_factor = EXCLUDED.noise_penalty_factor,
                low_evidence_penalty_factor = EXCLUDED.low_evidence_penalty_factor,
                ranking_explanation = EXCLUDED.ranking_explanation,
                ranking_config_json = EXCLUDED.ranking_config_json,
                quality_flags = EXCLUDED.quality_flags,
                is_production_ready = EXCLUDED.is_production_ready,
                human_review_status = EXCLUDED.human_review_status
            RETURNING hidden_gem_candidate_id
            """
        ),
        {
            "place_id": normalize_space(row.get("place_id")),
            "dish_id": dish_id,
            "dish_place_signal_id": dish_place_signal_id,
            "neighborhood_id": normalize_space(row.get("neighborhood_id")) or None,
            "district_id": normalize_space(row.get("district_id")) or None,
            "ai_pipeline_run_id": ai_pipeline_run_id,
            "ranking_version": ranking_version[:50],
            "ranking_scope": db_ranking_scope,
            "hidden_gem_score": score_0_100(row.get("hidden_gem_score_v1")) or 0.0,
            "hidden_gem_score_base": score_0_100(base_score),
            "hidden_gem_rank": safe_int(row.get("hidden_gem_global_rank_v1")),
            "hidden_gem_selected_rank": selected_rank,
            "hidden_gem_tier": tier,
            "is_selected": selected,
            "local_sentiment_component": component(row.get("quality_component_v1")),
            "evidence_component": component(row.get("evidence_component_v1")),
            "confidence_component": component(row.get("confidence_component_v1")),
            "positive_balance_component": ratio(row.get("smoothed_positive_ratio")) or ratio(row.get("positive_ratio")),
            "rarity_component": component(row.get("global_hiddenness_component_v1")),
            "local_outperformance_component": component(row.get("neighborhood_uniqueness_component_v1")),
            "hiddenness_component": component(row.get("hiddenness_component_v1")),
            "preliminary_component": component((safe_float(row.get("preliminary_signal_score_v1")) or 0.0) / 100.0),
            "negative_penalty_factor": component(row.get("negative_penalty_component_v1")),
            "beverage_penalty_factor": 0.0,
            "noise_penalty_factor": component(row.get("signal_noise_penalty_v1")),
            "low_evidence_penalty_factor": component(1.0 - (safe_float(row.get("evidence_component_v1")) or 0.0)),
            "ranking_explanation": normalize_space(row.get("ranking_explanation_v1")) or None,
            "ranking_config_json": json_dumps(ranking_config),
            "quality_flags": json_dumps(flags),
            "is_production_ready": safe_bool(row.get("is_production_ready_v1"), default=False),
            "human_review_status": "pending" if selected else "not_reviewed",
        },
    ).mappings().one()
    return str(db_row["hidden_gem_candidate_id"])


# -----------------------------------------------------------------------------
# Main load
# -----------------------------------------------------------------------------

def analyze_or_load(
    *,
    catalog_path: Path,
    aliases_path: Path,
    mentions_path: Path,
    signals_path: Path,
    ranking_path: Path,
    report_path: Path | None,
    schema: str,
    source_code: str,
    db_ranking_scope: str,
    artifact_ranking_scope: str,
    signal_version: str,
    ranking_version: str,
    max_rows: int | None,
    dry_run: bool,
) -> dict[str, Any]:
    schema = validate_schema_name(schema)
    db_ranking_scope = ranking_scope_for_db(db_ranking_scope)

    print("Reading artifacts...")
    catalog_rows = read_artifact_rows(catalog_path, max_rows=max_rows)
    alias_rows = read_artifact_rows(aliases_path, max_rows=max_rows)
    mention_rows = read_artifact_rows(mentions_path, max_rows=max_rows)
    signal_rows = read_artifact_rows(signals_path, max_rows=max_rows)
    ranking_rows = read_artifact_rows(ranking_path, max_rows=max_rows)

    input_stats = InputStats(
        catalog_rows=len(catalog_rows),
        aliases_rows=len(alias_rows),
        mention_rows=len(mention_rows),
        signal_rows=len(signal_rows),
        ranking_rows=len(ranking_rows),
    )
    load_stats = LoadStats(dry_run=dry_run)
    skip_stats = SkipStats()

    input_artifacts = [
        {"artifact_type": "dish_catalog", "path": str(catalog_path)},
        {"artifact_type": "dish_aliases", "path": str(aliases_path)},
        {"artifact_type": "dish_mentions_with_sentiment", "path": str(mentions_path)},
        {"artifact_type": "place_dish_signals", "path": str(signals_path)},
        {"artifact_type": "hidden_gems_ranking", "path": str(ranking_path)},
    ]

    dish_code_to_db_id: dict[str, str] = {}
    alias_key_to_db_id: dict[tuple[str, str], str] = {}
    mention_source_id_to_db_id: dict[str, str] = {}
    signal_key_to_db_id: dict[tuple[str, str], str] = {}

    with engine.begin() as conn:
        # Validate base source exists.
        source_system_id = get_source_system_id(conn, schema, source_code)

        print("Loading existing DB references...")
        existing_places = load_existing_ids(conn, schema, "place", "place_id")
        existing_districts = load_existing_ids(conn, schema, "district", "district_id")
        existing_neighborhoods = load_existing_ids(conn, schema, "neighborhood", "neighborhood_id")
        existing_review_place_pairs = load_review_place_pairs(conn, schema)

        if dry_run:
            model_ids = {
                "detection": "DRY_RUN_DETECTION_MODEL_ID",
                "normalization": "DRY_RUN_NORMALIZATION_MODEL_ID",
                "sentiment": "DRY_RUN_SENTIMENT_MODEL_ID",
                "aggregation": "DRY_RUN_AGGREGATION_MODEL_ID",
                "ranking": "DRY_RUN_RANKING_MODEL_ID",
            }
            run_ids = {
                "catalog": "DRY_RUN_CATALOG_RUN_ID",
                "mentions": "DRY_RUN_MENTION_RUN_ID",
                "sentiment": "DRY_RUN_SENTIMENT_RUN_ID",
                "aggregation": "DRY_RUN_AGGREGATION_RUN_ID",
                "ranking": "DRY_RUN_RANKING_RUN_ID",
            }
        else:
            model_ids = {
                "detection": upsert_model_version(
                    conn,
                    schema,
                    model_code=DEFAULT_DISH_DETECTION_MODEL_CODE,
                    model_name="Sevilla Dish Detection Hybrid v1",
                    model_type="hybrid",
                    task_name="dish_detection",
                    version_label="v1",
                    description="Hybrid Spanish/Sevilla dish candidate detection using lexicon and regex patterns.",
                    config={"source_code": source_code, "artifact": str(mentions_path)},
                ),
                "normalization": upsert_model_version(
                    conn,
                    schema,
                    model_code=DEFAULT_DISH_NORMALIZATION_MODEL_CODE,
                    model_name="Sevilla Dish Normalization Hybrid v1",
                    model_type="hybrid",
                    task_name="dish_normalization",
                    version_label="v1",
                    description="Rule-based Spanish dish normalization and local catalog construction for Sevilla pilot.",
                    config={"source_code": source_code, "artifact": str(catalog_path)},
                ),
                "sentiment": upsert_model_version(
                    conn,
                    schema,
                    model_code=DEFAULT_SENTIMENT_MODEL_CODE,
                    model_name="Sevilla Mention Sentiment Hybrid v1",
                    model_type="hybrid",
                    task_name="mention_sentiment",
                    version_label="v1",
                    description="Spanish hybrid aspect-level sentiment over dish mentions.",
                    config={"source_code": source_code, "artifact": str(mentions_path)},
                ),
                "aggregation": upsert_model_version(
                    conn,
                    schema,
                    model_code=DEFAULT_AGGREGATION_MODEL_CODE,
                    model_name="Sevilla Signal Aggregation v1",
                    model_type="aggregation",
                    task_name="signal_aggregation",
                    version_label="v1",
                    description="Aggregation of dish mentions into place-dish signals for Sevilla pilot.",
                    config={"source_code": source_code, "artifact": str(signals_path)},
                ),
                "ranking": upsert_model_version(
                    conn,
                    schema,
                    model_code=DEFAULT_RANKING_MODEL_CODE,
                    model_name="Sevilla Hidden Gems Ranking Pilot v1",
                    model_type="ranking",
                    task_name="hidden_gems_ranking",
                    version_label="v1",
                    description="Pilot Hidden Gems ranking for Sevilla based on Google Places reviews.",
                    config={"source_code": source_code, "artifact": str(ranking_path), "db_ranking_scope": db_ranking_scope},
                ),
            }
            load_stats.model_versions_upserted = len(model_ids)

            run_ids = {
                "catalog": upsert_ai_run(
                    conn,
                    schema,
                    run_code=DEFAULT_CATALOG_RUN_CODE,
                    run_type="dish_normalization",
                    input_artifacts=[{"artifact_type": "dish_catalog", "path": str(catalog_path)}, {"artifact_type": "dish_aliases", "path": str(aliases_path)}],
                    output_artifacts=[],
                    config={"source_code": source_code, "loader": "load_sevilla_ai_pilot_outputs"},
                    metrics={"catalog_rows": len(catalog_rows), "alias_rows": len(alias_rows)},
                    notes="Import of Sevilla dish catalog and aliases from pilot artifacts.",
                ),
                "mentions": upsert_ai_run(
                    conn,
                    schema,
                    run_code=DEFAULT_MENTION_RUN_CODE,
                    run_type="dish_detection",
                    input_artifacts=[{"artifact_type": "dish_mentions", "path": str(mentions_path)}],
                    output_artifacts=[],
                    config={"source_code": source_code, "loader": "load_sevilla_ai_pilot_outputs"},
                    metrics={"mention_rows": len(mention_rows)},
                    notes="Import of Sevilla ranking-ready dish mentions from pilot artifacts.",
                ),
                "sentiment": upsert_ai_run(
                    conn,
                    schema,
                    run_code=DEFAULT_SENTIMENT_RUN_CODE,
                    run_type="mention_sentiment",
                    input_artifacts=[{"artifact_type": "dish_mentions_with_sentiment", "path": str(mentions_path)}],
                    output_artifacts=[],
                    config={"source_code": source_code, "loader": "load_sevilla_ai_pilot_outputs"},
                    metrics={"mention_rows": len(mention_rows)},
                    notes="Import of Sevilla mention-level sentiment from pilot artifacts.",
                ),
                "aggregation": upsert_ai_run(
                    conn,
                    schema,
                    run_code=DEFAULT_AGGREGATION_RUN_CODE,
                    run_type="signal_aggregation",
                    input_artifacts=[{"artifact_type": "place_dish_signals", "path": str(signals_path)}],
                    output_artifacts=[],
                    config={"source_code": source_code, "loader": "load_sevilla_ai_pilot_outputs", "signal_version": signal_version},
                    metrics={"signal_rows": len(signal_rows)},
                    notes="Import of aggregated Sevilla place-dish signals from pilot artifacts.",
                ),
                "ranking": upsert_ai_run(
                    conn,
                    schema,
                    run_code=DEFAULT_RANKING_RUN_CODE,
                    run_type="hidden_gems_ranking",
                    input_artifacts=input_artifacts,
                    output_artifacts=[],
                    config={
                        "source_code": source_code,
                        "loader": "load_sevilla_ai_pilot_outputs",
                        "artifact_ranking_scope": artifact_ranking_scope,
                        "db_ranking_scope": db_ranking_scope,
                        "ranking_version": ranking_version,
                    },
                    metrics={"ranking_rows": len(ranking_rows)},
                    notes="Import of Sevilla Hidden Gems pilot ranking. Stored as DB ranking_scope='other' unless configured otherwise.",
                ),
            }
            load_stats.ai_runs_upserted = len(run_ids)

        # Catalog
        print("Processing dish catalog...")
        for row in tqdm(catalog_rows, desc="dish catalog"):
            dish_code = normalize_lower(row.get("dish_id_v1"))
            if not dish_code or not normalize_space(row.get("canonical_dish_name_es_v1")):
                skip_stats.catalog_missing_required += 1
                continue
            if dry_run:
                dish_code_to_db_id[dish_code] = f"DRY_DISH_{dish_code}"
                load_stats.dishes_upserted += 1
            else:
                dish_db_id = upsert_dish(
                    conn,
                    schema,
                    row,
                    source_ai_run_id=run_ids["catalog"],
                    source_model_version_id=model_ids["normalization"],
                )
                dish_code_to_db_id[dish_code] = dish_db_id
                load_stats.dishes_upserted += 1

        # Aliases
        print("Processing dish aliases...")
        for row in tqdm(alias_rows, desc="dish aliases"):
            dish_code = normalize_lower(row.get("dish_id_v1"))
            alias_norm = normalize_lower(row.get("alias_normalized")) or normalize_lower(row.get("alias_text"))
            if not dish_code or not alias_norm:
                skip_stats.alias_missing_required += 1
                continue
            dish_db_id = dish_code_to_db_id.get(dish_code)
            if dish_db_id is None:
                skip_stats.alias_missing_dish_mapping += 1
                continue
            if dry_run:
                alias_key_to_db_id[(dish_db_id, alias_norm)] = f"DRY_ALIAS_{dish_code}_{alias_norm}"
                load_stats.aliases_upserted += 1
            else:
                alias_db_id = upsert_alias(
                    conn,
                    schema,
                    row,
                    dish_id=dish_db_id,
                    source_ai_run_id=run_ids["catalog"],
                    source_model_version_id=model_ids["normalization"],
                )
                alias_key_to_db_id[(dish_db_id, alias_norm)] = alias_db_id
                load_stats.aliases_upserted += 1

        # Mentions + sentiment
        print("Processing mentions and sentiment...")
        for row in tqdm(mention_rows, desc="mentions/sentiment"):
            mention_source_id = normalize_space(row.get("mention_id"))
            review_id = normalize_space(row.get("review_id"))
            place_id = normalize_space(row.get("place_id"))
            dish_code = normalize_lower(row.get("dish_id_v1"))
            mention_text = normalize_space(row.get("dish_mention_text"))
            sentiment_label = sentiment_label_for_db(row.get("mention_sentiment_label_v1"))
            if not mention_source_id or not review_id or not place_id or not dish_code or not mention_text:
                skip_stats.mention_missing_required += 1
                continue
            if (review_id, place_id) not in existing_review_place_pairs:
                skip_stats.mention_missing_review_mapping += 1
                continue
            if place_id not in existing_places:
                skip_stats.mention_missing_place_mapping += 1
                continue
            dish_db_id = dish_code_to_db_id.get(dish_code)
            if dish_db_id is None:
                skip_stats.mention_missing_dish_mapping += 1
                continue
            if sentiment_label is None:
                skip_stats.mention_invalid_sentiment += 1
                continue
            alias_key = (dish_db_id, normalize_lower(row.get("dish_mention_normalized")))
            alias_db_id = alias_key_to_db_id.get(alias_key)
            if dry_run:
                mention_db_id = f"DRY_MENTION_{mention_source_id}"
                mention_source_id_to_db_id[mention_source_id] = mention_db_id
                load_stats.mentions_upserted += 1
                load_stats.sentiments_upserted += 1
            else:
                mention_db_id = upsert_mention(
                    conn,
                    schema,
                    row,
                    dish_id=dish_db_id,
                    dish_alias_id=alias_db_id,
                    ai_pipeline_run_id=run_ids["mentions"],
                    model_version_id=model_ids["detection"],
                )
                upsert_sentiment(
                    conn,
                    schema,
                    row,
                    dish_mention_id=mention_db_id,
                    ai_pipeline_run_id=run_ids["sentiment"],
                    model_version_id=model_ids["sentiment"],
                )
                mention_source_id_to_db_id[mention_source_id] = mention_db_id
                load_stats.mentions_upserted += 1
                load_stats.sentiments_upserted += 1

        # Signals
        print("Processing place-dish signals...")
        for row in tqdm(signal_rows, desc="place-dish signals"):
            place_id = normalize_space(row.get("place_id"))
            dish_code = normalize_lower(row.get("dish_id_v1"))
            if not place_id or not dish_code:
                skip_stats.signal_missing_required += 1
                continue
            if place_id not in existing_places:
                skip_stats.signal_missing_place_mapping += 1
                continue
            dish_db_id = dish_code_to_db_id.get(dish_code)
            if dish_db_id is None:
                skip_stats.signal_missing_dish_mapping += 1
                continue
            if dry_run:
                signal_db_id = f"DRY_SIGNAL_{place_id}_{dish_code}"
                signal_key_to_db_id[(place_id, dish_db_id)] = signal_db_id
                load_stats.signals_upserted += 1
            else:
                signal_db_id = upsert_signal(
                    conn,
                    schema,
                    row,
                    dish_id=dish_db_id,
                    ai_pipeline_run_id=run_ids["aggregation"],
                    signal_version=signal_version,
                )
                signal_key_to_db_id[(place_id, dish_db_id)] = signal_db_id
                load_stats.signals_upserted += 1

        # Ranking candidates
        print("Processing Hidden Gems candidates...")
        for row in tqdm(ranking_rows, desc="hidden-gem candidates"):
            place_id = normalize_space(row.get("place_id"))
            dish_code = normalize_lower(row.get("dish_id_v1"))
            if not place_id or not dish_code:
                skip_stats.ranking_missing_required += 1
                continue
            if place_id not in existing_places:
                skip_stats.ranking_missing_place_mapping += 1
                continue
            dish_db_id = dish_code_to_db_id.get(dish_code)
            if dish_db_id is None:
                skip_stats.ranking_missing_dish_mapping += 1
                continue
            signal_db_id = signal_key_to_db_id.get((place_id, dish_db_id))
            # We allow missing signal_id, but count it because it reduces traceability.
            if signal_db_id is None:
                skip_stats.ranking_missing_signal_mapping += 1
            if normalize_space(row.get("neighborhood_id")) and normalize_space(row.get("neighborhood_id")) not in existing_neighborhoods:
                # Keep loading: FK allows NULL, but artifact should normally match.
                row = dict(row)
                row["neighborhood_id"] = None
            if normalize_space(row.get("district_id")) and normalize_space(row.get("district_id")) not in existing_districts:
                row = dict(row)
                row["district_id"] = None
            if dry_run:
                load_stats.ranking_candidates_upserted += 1
            else:
                upsert_hidden_gem_candidate(
                    conn,
                    schema,
                    row,
                    dish_id=dish_db_id,
                    dish_place_signal_id=signal_db_id,
                    ai_pipeline_run_id=run_ids["ranking"],
                    ranking_version=ranking_version,
                    db_ranking_scope=db_ranking_scope,
                    artifact_ranking_scope=artifact_ranking_scope,
                )
                load_stats.ranking_candidates_upserted += 1

    report = {
        "script": "load_sevilla_ai_pilot_outputs",
        "generated_at": utc_now().isoformat(),
        "schema": schema,
        "source_code": source_code,
        "dry_run": dry_run,
        "ranking_scope": {
            "artifact_ranking_scope": artifact_ranking_scope,
            "db_ranking_scope": db_ranking_scope,
            "note": "The current DB constraint may not allow 'sevilla_pilot'; by default this loader stores it in ranking_config_json and uses db_ranking_scope='other'.",
        },
        "paths": {
            "catalog_path": str(catalog_path),
            "aliases_path": str(aliases_path),
            "mentions_path": str(mentions_path),
            "signals_path": str(signals_path),
            "ranking_path": str(ranking_path),
        },
        "input_stats": asdict(input_stats),
        "load_stats": asdict(load_stats),
        "skip_stats": asdict(skip_stats),
        "checks": {
            "has_catalog_rows": input_stats.catalog_rows > 0,
            "has_alias_rows": input_stats.aliases_rows > 0,
            "has_mention_rows": input_stats.mention_rows > 0,
            "has_signal_rows": input_stats.signal_rows > 0,
            "has_ranking_rows": input_stats.ranking_rows > 0,
            "dishes_loaded_or_validated": load_stats.dishes_upserted > 0,
            "aliases_loaded_or_validated": load_stats.aliases_upserted > 0,
            "mentions_loaded_or_validated": load_stats.mentions_upserted > 0,
            "sentiments_loaded_or_validated": load_stats.sentiments_upserted > 0,
            "signals_loaded_or_validated": load_stats.signals_upserted > 0,
            "ranking_loaded_or_validated": load_stats.ranking_candidates_upserted > 0,
            "no_missing_review_mapping": skip_stats.mention_missing_review_mapping == 0,
            "no_missing_place_mapping": (
                skip_stats.mention_missing_place_mapping == 0
                and skip_stats.signal_missing_place_mapping == 0
                and skip_stats.ranking_missing_place_mapping == 0
            ),
            "no_missing_dish_mapping": (
                skip_stats.alias_missing_dish_mapping == 0
                and skip_stats.mention_missing_dish_mapping == 0
                and skip_stats.signal_missing_dish_mapping == 0
                and skip_stats.ranking_missing_dish_mapping == 0
            ),
            "no_invalid_sentiment": skip_stats.mention_invalid_sentiment == 0,
        },
    }

    if report_path:
        save_report(report_path, report)

    print(json.dumps(to_builtin(report["checks"]), indent=2, ensure_ascii=False))
    print(json.dumps(to_builtin(report["load_stats"]), indent=2, ensure_ascii=False))
    print(json.dumps(to_builtin(report["skip_stats"]), indent=2, ensure_ascii=False))

    return report


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Load Sevilla AI pilot outputs into PostgreSQL.")
    parser.add_argument("--catalog-path", type=Path, default=DEFAULT_CATALOG_PATH)
    parser.add_argument("--aliases-path", type=Path, default=DEFAULT_ALIASES_PATH)
    parser.add_argument("--mentions-path", type=Path, default=DEFAULT_MENTIONS_PATH)
    parser.add_argument("--signals-path", type=Path, default=DEFAULT_SIGNALS_PATH)
    parser.add_argument("--ranking-path", type=Path, default=DEFAULT_RANKING_PATH)
    parser.add_argument("--report-path", type=Path, default=DEFAULT_REPORT_PATH)
    parser.add_argument("--schema", default=DEFAULT_SCHEMA)
    parser.add_argument("--source-code", default=DEFAULT_SOURCE_CODE)
    parser.add_argument("--db-ranking-scope", default=DEFAULT_DB_RANKING_SCOPE, choices=sorted(VALID_DB_RANKING_SCOPES))
    parser.add_argument("--artifact-ranking-scope", default=DEFAULT_ARTIFACT_RANKING_SCOPE)
    parser.add_argument("--signal-version", default=DEFAULT_SIGNAL_VERSION)
    parser.add_argument("--ranking-version", default=DEFAULT_RANKING_VERSION)
    parser.add_argument("--max-rows", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        analyze_or_load(
            catalog_path=args.catalog_path,
            aliases_path=args.aliases_path,
            mentions_path=args.mentions_path,
            signals_path=args.signals_path,
            ranking_path=args.ranking_path,
            report_path=args.report_path,
            schema=args.schema,
            source_code=args.source_code,
            db_ranking_scope=args.db_ranking_scope,
            artifact_ranking_scope=args.artifact_ranking_scope,
            signal_version=args.signal_version,
            ranking_version=args.ranking_version,
            max_rows=args.max_rows,
            dry_run=args.dry_run,
        )
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()
