"""Load dish mentions and mention-level sentiment into PostgreSQL.

This script imports the downstream AI artifact generated by notebook 09:

    dish_mentions_with_sentiment_hybrid_v1.jsonl

It loads two tables:

    hidden_gems.dish_mention
    hidden_gems.dish_mention_sentiment

Prerequisites:

1. The AI schema must exist: db/ddl/07_ai_module.sql.
2. The dish catalog and aliases must already be loaded.
3. Yelp core places and reviews must already be loaded so that:

       artifact review_id  -> hidden_gems.review.source_review_id
       artifact business_id -> hidden_gems.review.source_place_record_id
       artifact business_id -> hidden_gems.place_source_ref.source_record_id

Recommended execution from repository root.

PowerShell dry-run:
    python -m scripts.load_ai_mentions_and_sentiment `
      --mentions-path data/artifacts/ai/sentiment/dish_mentions_with_sentiment_hybrid_v1.jsonl `
      --dry-run

PowerShell real load:
    python -m scripts.load_ai_mentions_and_sentiment `
      --mentions-path data/artifacts/ai/sentiment/dish_mentions_with_sentiment_hybrid_v1.jsonl

Optional report:
    python -m scripts.load_ai_mentions_and_sentiment `
      --mentions-path data/artifacts/ai/sentiment/dish_mentions_with_sentiment_hybrid_v1.jsonl `
      --report-path data/artifacts/ai/sentiment/load_ai_mentions_and_sentiment_report.json

The script is idempotent: mention rows are upserted by
(review_id, start_char, end_char, mention_normalized, ai_pipeline_run_id), and
sentiment rows are upserted by (dish_mention_id, ai_pipeline_run_id, sentiment_method).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from sqlalchemy import text
from sqlalchemy.engine import Connection

try:
    from tqdm.auto import tqdm
except Exception:  # pragma: no cover
    def tqdm(iterable: Iterable, **_: Any):
        return iterable

from src.db.database import engine


# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

DEFAULT_SCHEMA = "hidden_gems"
DEFAULT_SOURCE_CODE = "yelp_open_dataset"
DEFAULT_MENTIONS_RUN_CODE = "ai_run_yelp_dish_mentions_v1_import"
DEFAULT_SENTIMENT_RUN_CODE = "ai_run_yelp_mention_sentiment_hybrid_v1_import"
DEFAULT_DETECTION_MODEL_CODE = "dish_ner_transformer_v1"
DEFAULT_SENTIMENT_MODEL_CODE = "mention_sentiment_hybrid_v1_1"

SCHEMA_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")

VALID_SENTIMENT_LABELS = {"positive", "neutral", "negative"}
VALID_RELIABILITY_TIERS = {"high", "medium", "low"}
VALID_HUMAN_REVIEW_STATUS = {"not_reviewed", "pending", "approved", "rejected", "corrected"}


# -----------------------------------------------------------------------------
# Data classes
# -----------------------------------------------------------------------------

@dataclass
class InputStats:
    rows_total: int = 0
    rows_considered: int = 0
    invalid_json_lines: int = 0
    skipped_missing_required_fields: int = 0
    skipped_missing_review_mapping: int = 0
    skipped_business_mismatch: int = 0
    skipped_missing_dish_mapping: int = 0
    skipped_invalid_sentiment: int = 0


@dataclass
class LoadStats:
    mentions_upserted: int = 0
    sentiments_upserted: int = 0
    dry_run: bool = False


# -----------------------------------------------------------------------------
# Generic helpers
# -----------------------------------------------------------------------------


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def validate_schema_name(schema: str) -> str:
    schema = str(schema).strip()
    if not SCHEMA_RE.match(schema):
        raise ValueError(f"Invalid PostgreSQL schema name: {schema!r}")
    return schema


def qname(schema: str, table: str) -> str:
    schema = validate_schema_name(schema)
    return f'"{schema}"."{table}"'


def normalize_space(value: Any) -> str:
    if value is None:
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def normalize_lower(value: Any) -> str:
    return normalize_space(value).lower()


def truncate(value: Any, max_len: int) -> str | None:
    value = normalize_space(value)
    if not value:
        return None
    return value[:max_len]


def safe_int(value: Any) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(float(value))
    except Exception:
        return None


def safe_float(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except Exception:
        return None


def safe_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    value_str = str(value).strip().lower()
    if value_str in {"true", "1", "yes", "y"}:
        return True
    if value_str in {"false", "0", "no", "n"}:
        return False
    return default


def clamp_float(value: Any, min_value: float, max_value: float) -> float | None:
    value = safe_float(value)
    if value is None:
        return None
    return max(min_value, min(max_value, value))


def parse_list_like(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, str):
        value = value.strip()
        if not value:
            return []
        try:
            parsed = json.loads(value)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            if not inner:
                return []
            return [part.strip().strip("'").strip('"') for part in inner.split(",") if part.strip()]
        return [value]
    return [value]


def json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, default=str)


def save_report(path: Path, report: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False, default=str)
    print(f"Report saved to: {path}")


def iter_jsonl(path: Path, max_rows: int | None = None) -> Iterable[tuple[int, dict[str, Any] | None]]:
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            if max_rows is not None and line_no > max_rows:
                break
            line = line.strip()
            if not line:
                continue
            try:
                yield line_no, json.loads(line)
            except json.JSONDecodeError:
                yield line_no, None


# -----------------------------------------------------------------------------
# Database helpers
# -----------------------------------------------------------------------------


def get_source_system_id(conn: Connection, schema: str, source_code: str) -> str:
    row = conn.execute(
        text(
            f"""
            SELECT source_system_id
            FROM {qname(schema, 'source_system')}
            WHERE source_code = :source_code
            """
        ),
        {"source_code": source_code},
    ).mappings().first()

    if row is None:
        raise RuntimeError(f"source_system not found for source_code={source_code!r}")

    return str(row["source_system_id"])


def get_model_version_id(conn: Connection, schema: str, model_code: str) -> str:
    row = conn.execute(
        text(
            f"""
            SELECT ai_model_version_id
            FROM {qname(schema, 'ai_model_version')}
            WHERE model_code = :model_code
            """
        ),
        {"model_code": model_code},
    ).mappings().first()

    if row is None:
        raise RuntimeError(f"ai_model_version not found for model_code={model_code!r}")

    return str(row["ai_model_version_id"])


def upsert_ai_pipeline_run(
    conn: Connection,
    schema: str,
    *,
    run_code: str,
    run_type: str,
    input_artifacts: list[dict[str, Any]],
    config: dict[str, Any],
    metrics: dict[str, Any] | None = None,
    notes: str | None = None,
) -> str:
    now = utc_now()
    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'ai_pipeline_run')} (
                run_code,
                run_type,
                status,
                started_at,
                finished_at,
                duration_seconds,
                input_artifacts_json,
                output_artifacts_json,
                config_json,
                metrics_json,
                notes
            )
            VALUES (
                :run_code,
                :run_type,
                'completed',
                :started_at,
                :finished_at,
                0,
                CAST(:input_artifacts_json AS jsonb),
                CAST(:output_artifacts_json AS jsonb),
                CAST(:config_json AS jsonb),
                CAST(:metrics_json AS jsonb),
                :notes
            )
            ON CONFLICT (run_code) DO UPDATE SET
                run_type = EXCLUDED.run_type,
                status = EXCLUDED.status,
                finished_at = EXCLUDED.finished_at,
                duration_seconds = EXCLUDED.duration_seconds,
                input_artifacts_json = EXCLUDED.input_artifacts_json,
                config_json = EXCLUDED.config_json,
                metrics_json = EXCLUDED.metrics_json,
                notes = EXCLUDED.notes
            RETURNING ai_pipeline_run_id
            """
        ),
        {
            "run_code": run_code,
            "run_type": run_type,
            "started_at": now,
            "finished_at": now,
            "input_artifacts_json": json_dumps(input_artifacts),
            "output_artifacts_json": json_dumps([]),
            "config_json": json_dumps(config),
            "metrics_json": json_dumps(metrics or {}),
            "notes": notes,
        },
    ).mappings().one()

    return str(row["ai_pipeline_run_id"])


def load_review_mapping(conn: Connection, schema: str, source_system_id: str) -> dict[str, dict[str, str]]:
    print("Loading review mapping from database...")
    rows = conn.execute(
        text(
            f"""
            SELECT
                r.source_review_id,
                r.source_place_record_id,
                r.review_id,
                r.place_id
            FROM {qname(schema, 'review')} r
            WHERE r.source_system_id = :source_system_id
              AND r.source_review_id IS NOT NULL
              AND r.source_place_record_id IS NOT NULL
            """
        ),
        {"source_system_id": source_system_id},
    ).mappings().all()

    mapping: dict[str, dict[str, str]] = {}
    for row in rows:
        mapping[str(row["source_review_id"])] = {
            "review_id": str(row["review_id"]),
            "place_id": str(row["place_id"]),
            "source_place_record_id": str(row["source_place_record_id"]),
        }

    print(f"Review mapping loaded: {len(mapping):,}")
    return mapping


def load_dish_mapping(conn: Connection, schema: str) -> dict[str, str]:
    print("Loading dish mapping from database...")
    rows = conn.execute(
        text(
            f"""
            SELECT dish_id, normalized_name
            FROM {qname(schema, 'dish')}
            WHERE is_active = TRUE
            """
        )
    ).mappings().all()

    mapping = {str(row["normalized_name"]).strip().lower(): str(row["dish_id"]) for row in rows}
    print(f"Dish mapping loaded: {len(mapping):,}")
    return mapping


def load_alias_mapping(conn: Connection, schema: str) -> dict[tuple[str, str], str]:
    print("Loading dish alias mapping from database...")
    rows = conn.execute(
        text(
            f"""
            SELECT dish_alias_id, dish_id, alias_normalized
            FROM {qname(schema, 'dish_alias')}
            WHERE is_active = TRUE
            """
        )
    ).mappings().all()

    mapping: dict[tuple[str, str], str] = {}
    for row in rows:
        key = (str(row["dish_id"]), str(row["alias_normalized"]).strip().lower())
        mapping[key] = str(row["dish_alias_id"])

    print(f"Dish alias mapping loaded: {len(mapping):,}")
    return mapping


# -----------------------------------------------------------------------------
# Row preparation
# -----------------------------------------------------------------------------


def validate_and_prepare_record(
    record: dict[str, Any],
    *,
    review_mapping: dict[str, dict[str, str]],
    dish_mapping: dict[str, str],
    alias_mapping: dict[tuple[str, str], str],
    mentions_run_id: str,
    sentiment_run_id: str,
    detection_model_version_id: str,
    sentiment_model_version_id: str,
    strict_business_match: bool,
) -> tuple[dict[str, Any] | None, dict[str, Any] | None, str | None]:
    """Return (mention_params, sentiment_params, skip_reason)."""

    source_review_id = normalize_space(record.get("review_id"))
    source_business_id = normalize_space(record.get("business_id"))
    canonical_name = normalize_lower(record.get("canonical_dish_name_v2"))
    mention_text = normalize_space(record.get("dish_mention_text"))
    mention_normalized = normalize_lower(record.get("dish_mention_normalized"))

    if not source_review_id or not source_business_id or not canonical_name or not mention_text:
        return None, None, "missing_required_fields"

    review_info = review_mapping.get(source_review_id)
    if review_info is None:
        return None, None, "missing_review_mapping"

    if strict_business_match and review_info["source_place_record_id"] != source_business_id:
        return None, None, "business_mismatch"

    dish_id = dish_mapping.get(canonical_name)
    if dish_id is None:
        return None, None, "missing_dish_mapping"

    sentiment_label = normalize_lower(record.get("mention_sentiment_label_final"))
    if sentiment_label not in VALID_SENTIMENT_LABELS:
        return None, None, "invalid_sentiment"

    sentiment_method = truncate(record.get("sentiment_method_final"), 100) or "hybrid_context_lexicon_v1_1"
    reliability_tier = normalize_lower(record.get("sentiment_reliability_tier"))
    if reliability_tier not in VALID_RELIABILITY_TIERS:
        reliability_tier = None

    human_review_status = normalize_lower(record.get("human_review_status")) or "not_reviewed"
    if human_review_status not in VALID_HUMAN_REVIEW_STATUS:
        human_review_status = "not_reviewed"

    alias_id = alias_mapping.get((dish_id, mention_normalized))

    mention_params = {
        "review_id": review_info["review_id"],
        "place_id": review_info["place_id"],
        "dish_id": dish_id,
        "dish_alias_id": alias_id,
        "ai_pipeline_run_id": mentions_run_id,
        "model_version_id": detection_model_version_id,
        "mention_text": mention_text,
        "mention_normalized": truncate(mention_normalized, 255),
        "start_char": safe_int(record.get("start_char")),
        "end_char": safe_int(record.get("end_char")),
        "start_token": safe_int(record.get("start_token")),
        "end_token": safe_int(record.get("end_token")),
        "token_count": safe_int(record.get("token_count")),
        "ner_confidence_mean": clamp_float(record.get("confidence_mean"), 0.0, 1.0),
        "ner_confidence_min": clamp_float(record.get("confidence_min"), 0.0, 1.0),
        "ner_confidence_max": clamp_float(record.get("confidence_max"), 0.0, 1.0),
        "normalization_status": truncate(normalize_lower(record.get("normalization_status_v2")) or "unknown", 50),
        "normalization_method": truncate(record.get("normalization_method_v2"), 100),
        "normalization_confidence": None,
        "human_review_status": human_review_status,
    }

    sentiment_params = {
        "ai_pipeline_run_id": sentiment_run_id,
        "model_version_id": sentiment_model_version_id,
        "sentiment_label": sentiment_label,
        "sentiment_score": clamp_float(record.get("mention_sentiment_score_final"), -5.0, 5.0),
        "sentiment_confidence": clamp_float(record.get("mention_sentiment_confidence_final"), 0.0, 1.0),
        "sentiment_reliability_tier": reliability_tier,
        "sentiment_reason": truncate(record.get("sentiment_reason_final"), 100),
        "sentiment_method": sentiment_method,
        "context_sentence": normalize_space(record.get("sentence_context")) or None,
        "context_window": normalize_space(record.get("window_context")) or None,
        "target_clause_context": normalize_space(record.get("target_clause_context_v11")) or None,
        "near_mention_context": normalize_space(record.get("near_mention_context_v11")) or None,
        "positive_terms": json_dumps(parse_list_like(record.get("positive_terms_v11"))),
        "negative_terms": json_dumps(parse_list_like(record.get("negative_terms_v11"))),
        "flags": json_dumps(parse_list_like(record.get("sentiment_flags_final"))),
        "is_training_candidate": safe_bool(record.get("is_sentiment_training_candidate"), default=False),
        "human_review_status": human_review_status,
    }

    return mention_params, sentiment_params, None


# -----------------------------------------------------------------------------
# Insert/upsert helpers
# -----------------------------------------------------------------------------


def upsert_dish_mention(conn: Connection, schema: str, params: dict[str, Any]) -> str:
    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish_mention')} (
                review_id,
                place_id,
                dish_id,
                dish_alias_id,
                ai_pipeline_run_id,
                model_version_id,
                mention_text,
                mention_normalized,
                start_char,
                end_char,
                start_token,
                end_token,
                token_count,
                ner_confidence_mean,
                ner_confidence_min,
                ner_confidence_max,
                normalization_status,
                normalization_method,
                normalization_confidence,
                human_review_status
            )
            VALUES (
                :review_id,
                :place_id,
                :dish_id,
                :dish_alias_id,
                :ai_pipeline_run_id,
                :model_version_id,
                :mention_text,
                :mention_normalized,
                :start_char,
                :end_char,
                :start_token,
                :end_token,
                :token_count,
                :ner_confidence_mean,
                :ner_confidence_min,
                :ner_confidence_max,
                :normalization_status,
                :normalization_method,
                :normalization_confidence,
                :human_review_status
            )
            ON CONFLICT (review_id, start_char, end_char, mention_normalized, ai_pipeline_run_id)
            DO UPDATE SET
                place_id = EXCLUDED.place_id,
                dish_id = EXCLUDED.dish_id,
                dish_alias_id = EXCLUDED.dish_alias_id,
                model_version_id = EXCLUDED.model_version_id,
                mention_text = EXCLUDED.mention_text,
                start_token = EXCLUDED.start_token,
                end_token = EXCLUDED.end_token,
                token_count = EXCLUDED.token_count,
                ner_confidence_mean = EXCLUDED.ner_confidence_mean,
                ner_confidence_min = EXCLUDED.ner_confidence_min,
                ner_confidence_max = EXCLUDED.ner_confidence_max,
                normalization_status = EXCLUDED.normalization_status,
                normalization_method = EXCLUDED.normalization_method,
                normalization_confidence = EXCLUDED.normalization_confidence,
                human_review_status = EXCLUDED.human_review_status,
                is_active = TRUE
            RETURNING dish_mention_id
            """
        ),
        params,
    ).mappings().one()

    return str(row["dish_mention_id"])


def upsert_dish_mention_sentiment(
    conn: Connection,
    schema: str,
    *,
    dish_mention_id: str,
    params: dict[str, Any],
) -> str:
    final_params = dict(params)
    final_params["dish_mention_id"] = dish_mention_id

    row = conn.execute(
        text(
            f"""
            INSERT INTO {qname(schema, 'dish_mention_sentiment')} (
                dish_mention_id,
                ai_pipeline_run_id,
                model_version_id,
                sentiment_label,
                sentiment_score,
                sentiment_confidence,
                sentiment_reliability_tier,
                sentiment_reason,
                sentiment_method,
                context_sentence,
                context_window,
                target_clause_context,
                near_mention_context,
                positive_terms,
                negative_terms,
                flags,
                is_training_candidate,
                human_review_status
            )
            VALUES (
                :dish_mention_id,
                :ai_pipeline_run_id,
                :model_version_id,
                :sentiment_label,
                :sentiment_score,
                :sentiment_confidence,
                :sentiment_reliability_tier,
                :sentiment_reason,
                :sentiment_method,
                :context_sentence,
                :context_window,
                :target_clause_context,
                :near_mention_context,
                CAST(:positive_terms AS jsonb),
                CAST(:negative_terms AS jsonb),
                CAST(:flags AS jsonb),
                :is_training_candidate,
                :human_review_status
            )
            ON CONFLICT (dish_mention_id, ai_pipeline_run_id, sentiment_method)
            DO UPDATE SET
                model_version_id = EXCLUDED.model_version_id,
                sentiment_label = EXCLUDED.sentiment_label,
                sentiment_score = EXCLUDED.sentiment_score,
                sentiment_confidence = EXCLUDED.sentiment_confidence,
                sentiment_reliability_tier = EXCLUDED.sentiment_reliability_tier,
                sentiment_reason = EXCLUDED.sentiment_reason,
                context_sentence = EXCLUDED.context_sentence,
                context_window = EXCLUDED.context_window,
                target_clause_context = EXCLUDED.target_clause_context,
                near_mention_context = EXCLUDED.near_mention_context,
                positive_terms = EXCLUDED.positive_terms,
                negative_terms = EXCLUDED.negative_terms,
                flags = EXCLUDED.flags,
                is_training_candidate = EXCLUDED.is_training_candidate,
                human_review_status = EXCLUDED.human_review_status
            RETURNING dish_mention_sentiment_id
            """
        ),
        final_params,
    ).mappings().one()

    return str(row["dish_mention_sentiment_id"])


# -----------------------------------------------------------------------------
# Main load
# -----------------------------------------------------------------------------


def analyze_or_load(
    *,
    mentions_path: Path,
    schema: str,
    source_code: str,
    mentions_run_code: str,
    sentiment_run_code: str,
    max_rows: int | None,
    strict_business_match: bool,
    dry_run: bool,
) -> dict[str, Any]:
    if not mentions_path.exists():
        raise FileNotFoundError(f"Mentions file not found: {mentions_path}")

    schema = validate_schema_name(schema)

    input_stats = InputStats()
    load_stats = LoadStats(dry_run=dry_run)

    input_artifacts = [
        {
            "artifact_type": "dish_mentions_with_sentiment",
            "path": str(mentions_path),
        }
    ]

    with engine.begin() as conn:
        source_system_id = get_source_system_id(conn, schema, source_code)
        detection_model_version_id = get_model_version_id(conn, schema, DEFAULT_DETECTION_MODEL_CODE)
        sentiment_model_version_id = get_model_version_id(conn, schema, DEFAULT_SENTIMENT_MODEL_CODE)

        review_mapping = load_review_mapping(conn, schema, source_system_id)
        dish_mapping = load_dish_mapping(conn, schema)
        alias_mapping = load_alias_mapping(conn, schema)

        if dry_run:
            mentions_run_id = "DRY_RUN_MENTIONS_RUN_ID"
            sentiment_run_id = "DRY_RUN_SENTIMENT_RUN_ID"
        else:
            mentions_run_id = upsert_ai_pipeline_run(
                conn,
                schema,
                run_code=mentions_run_code,
                run_type="dish_detection",
                input_artifacts=input_artifacts,
                config={
                    "source_code": source_code,
                    "strict_business_match": strict_business_match,
                    "loader": "load_ai_mentions_and_sentiment",
                    "phase": "dish_mention_import",
                },
                notes="Import of dish mentions from Yelp AI prototype artifact. Not Sevilla production output.",
            )
            sentiment_run_id = upsert_ai_pipeline_run(
                conn,
                schema,
                run_code=sentiment_run_code,
                run_type="mention_sentiment",
                input_artifacts=input_artifacts,
                config={
                    "source_code": source_code,
                    "strict_business_match": strict_business_match,
                    "loader": "load_ai_mentions_and_sentiment",
                    "phase": "mention_sentiment_import",
                },
                notes="Import of mention-level sentiment from Yelp AI prototype artifact. Not Sevilla production output.",
            )

        iterator = tqdm(iter_jsonl(mentions_path, max_rows=max_rows), desc="Processing mentions")
        for _, record in iterator:
            input_stats.rows_total += 1

            if record is None:
                input_stats.invalid_json_lines += 1
                continue

            input_stats.rows_considered += 1

            mention_params, sentiment_params, skip_reason = validate_and_prepare_record(
                record,
                review_mapping=review_mapping,
                dish_mapping=dish_mapping,
                alias_mapping=alias_mapping,
                mentions_run_id=mentions_run_id,
                sentiment_run_id=sentiment_run_id,
                detection_model_version_id=detection_model_version_id,
                sentiment_model_version_id=sentiment_model_version_id,
                strict_business_match=strict_business_match,
            )

            if skip_reason is not None:
                if skip_reason == "missing_required_fields":
                    input_stats.skipped_missing_required_fields += 1
                elif skip_reason == "missing_review_mapping":
                    input_stats.skipped_missing_review_mapping += 1
                elif skip_reason == "business_mismatch":
                    input_stats.skipped_business_mismatch += 1
                elif skip_reason == "missing_dish_mapping":
                    input_stats.skipped_missing_dish_mapping += 1
                elif skip_reason == "invalid_sentiment":
                    input_stats.skipped_invalid_sentiment += 1
                continue

            if dry_run:
                load_stats.mentions_upserted += 1
                load_stats.sentiments_upserted += 1
                continue

            assert mention_params is not None
            assert sentiment_params is not None

            dish_mention_id = upsert_dish_mention(conn, schema, mention_params)
            upsert_dish_mention_sentiment(
                conn,
                schema,
                dish_mention_id=dish_mention_id,
                params=sentiment_params,
            )

            load_stats.mentions_upserted += 1
            load_stats.sentiments_upserted += 1

    report = {
        "schema": schema,
        "source_code": source_code,
        "mentions_path": str(mentions_path),
        "max_rows": max_rows,
        "strict_business_match": strict_business_match,
        "dry_run": dry_run,
        "input_stats": asdict(input_stats),
        "load_stats": asdict(load_stats),
        "readiness_after_this_step": {
            "dish_mentions_loaded_or_validated": load_stats.mentions_upserted,
            "dish_mention_sentiments_loaded_or_validated": load_stats.sentiments_upserted,
            "ready_for_signal_loader_if_no_skips": (
                input_stats.skipped_missing_review_mapping == 0
                and input_stats.skipped_business_mismatch == 0
                and input_stats.skipped_missing_dish_mapping == 0
                and input_stats.skipped_invalid_sentiment == 0
            ),
        },
    }

    return report


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Load dish mentions and mention sentiment into the Hidden Gems AI schema."
    )
    parser.add_argument(
        "--mentions-path",
        type=Path,
        required=True,
        help="Path to dish_mentions_with_sentiment_hybrid_v1.jsonl.",
    )
    parser.add_argument(
        "--schema",
        default=DEFAULT_SCHEMA,
        help="PostgreSQL schema name. Default: hidden_gems.",
    )
    parser.add_argument(
        "--source-code",
        default=DEFAULT_SOURCE_CODE,
        help="Source system code used to map review.source_review_id. Default: yelp_open_dataset.",
    )
    parser.add_argument(
        "--mentions-run-code",
        default=DEFAULT_MENTIONS_RUN_CODE,
        help="ai_pipeline_run.run_code for dish mention import.",
    )
    parser.add_argument(
        "--sentiment-run-code",
        default=DEFAULT_SENTIMENT_RUN_CODE,
        help="ai_pipeline_run.run_code for mention sentiment import.",
    )
    parser.add_argument(
        "--max-rows",
        type=int,
        default=None,
        help="Optional maximum number of JSONL lines to process.",
    )
    parser.add_argument(
        "--no-strict-business-match",
        action="store_true",
        help="Allow loading a mention even if artifact business_id does not match review.source_place_record_id.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and count rows without writing to the database.",
    )
    parser.add_argument(
        "--report-path",
        type=Path,
        default=None,
        help="Optional path to save a JSON report.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        report = analyze_or_load(
            mentions_path=args.mentions_path,
            schema=args.schema,
            source_code=args.source_code,
            mentions_run_code=args.mentions_run_code,
            sentiment_run_code=args.sentiment_run_code,
            max_rows=args.max_rows,
            strict_business_match=not args.no_strict_business_match,
            dry_run=args.dry_run,
        )

        print("\n" + "=" * 96)
        print("Load AI mentions and sentiment report")
        print("=" * 96)
        print(json.dumps(report, indent=2, ensure_ascii=False, default=str))

        if args.report_path is not None:
            save_report(args.report_path, report)

        return 0

    except Exception as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
